### ISSUE TITLE
Please add support for RFXCOM Blinds T15 Motostar

### ISSUE THREAD

**Issue by track53** [domoticz/domoticz#3359] opened 2019-06-28 17:13 UTC
Hi,
Since the firmware 1039 (Pro2)
In Domotics seems the blinds T15 RFU has change.
Now it's Blinds T15 Motorstar, my blinds (Motostar) works fine with RFXmngr (open/close/stop/confirm) ID and Code unit, but in Domoticz it's always Blinds T15 RFU and no working with the blinds Motostar and missed button stop/confirm and not possible to choose code unite.

I don't no if I can help you for change that :(

THX

**Comment by gizmocuz** [comment] 2019-07-28 11:59
Could you show how this device is displayed in the devices tab ?

And could you show the settings you use in the RFXMngr application ?

**Comment by track53** [comment] 2019-07-28 17:39
> Could you show how this device is displayed in the devices tab ?
> 
> And could you show the settings you use in the RFXMngr application ?

Hi @gizmocuz , yes no problem : 

In RFMngr 
![volet_rfxcom](https://user-images.githubusercontent.com/52329161/62010758-244ca600-b16f-11e9-9a19-c9ae7b6be5a6.PNG)

In Domoticz
![volet_dcz1](https://user-images.githubusercontent.com/52329161/62010768-36c6df80-b16f-11e9-931d-5aad79017bca.PNG)


Thanks for your interest and your help.

**Comment by gizmocuz** [comment] 2019-07-28 18:35
@track53 , OK , it looks like you miss the Unit Code option... 
But when you use ID 00 01, and add the device, could you post a screenshot of the devices tab where this device is shown ?

**Comment by track53** [comment] 2019-07-28 19:56
I can't take new screenshot, I have not the rfxcom for next 15 days :/ but I have it, I try to using differnet ID in Domoticz 00 01 or 01 00 02 01 .... no change.
And the command are not good. only open/close in Domoticz wherase I have open / close / stop and confirm to rfxmngr.
I can send  an screnshot when I do the test.
![volet_dcz2](https://user-images.githubusercontent.com/52329161/62012124-59aebf00-b182-11e9-87bb-b85007bb4746.PNG)

**Comment by gizmocuz** [comment] 2019-07-28 20:32
This is not a screenshot from the devices tab (setup-> devices)

**Comment by track53** [comment] 2019-07-29 17:20
Too bad, I have not another screenshot and the RFXcom it was a friend who had lent him before to trying before I buy it, it was working. Maybe He can loan me after his holidays.

**Comment by track53** [comment] 2019-07-29 17:47
I have recreate without the usb rfxcom, I have same screen I think : 
![volet](https://user-images.githubusercontent.com/52329161/62069861-840f8380-b239-11e9-8c26-b0c42eddf994.PNG)

**Comment by gizmocuz** [comment] 2019-07-30 15:27
I think the problem is the unit code of 0
You could change this with a database editor like "sqlite expert personal edition"
I hope to find some time to fix this u less someone else beats me to it

**Comment by track53** [comment] 2019-07-30 17:21
@gizmocuz , ok I have find the entry to the domoticz.db , I have change the 0 by 1.
Now, I hope see my collegue that have the rfxcom and take it to trying next week. ;)

**Comment by track53** [comment] 2019-08-02 17:46
@gizmocuz , 
Hi, I have trying to day  (another guy has lent me an rfxcom), with change ID directly in the sql base that works fine :D :D.  I have take a test with 2 blinds and 2 differents ID that seems works very good.

**Comment by gizmocuz** [comment] 2019-08-02 17:48
Thanks for the feedback... Did you change the ID or the unit?

**Comment by track53** [comment] 2019-08-02 17:51
> Thanks for the feedback... Did you change the ID or the unit?

Exactly I have change the unit, sorry.

**Comment by gizmocuz** [comment] 2019-08-12 13:31
Great!, Soon a new beta will be out where you can choose the Unit code.
But 0 = All, i would have expected it would have worked

**Comment by track53** [comment] 2019-08-31 09:17
Hi Gizmocuz,
I have installed the last beta, and I have create a new one blinds and now we can choose the code Unit and it's works fine. :+1: 

Thank you very much.

**Comment by gizmocuz** [comment] 2019-08-31 09:24
Thanks for the feedback ! Closing issue...

**Closed as completed by gizmocuz** 2019-08-31 09:24 UTC
