### ISSUE TITLE
Devices with a temperature sensor began to show 29-30 degrees less than they actually are

### ISSUE THREAD

**Issue by kovainfo** [domoticz/domoticz#5422] opened 2022-11-19 06:08 UTC
Domoticz 2022.2 (14727)
After the update, zigbee2mqtt Devices with a temperature sensor (such as ZNCZ04LM, RTCGQ11LM, LLKZMK11LM and so on) began to show 29-30 degrees less than they actually are

<img width="1199" alt="Снимок экрана 2022-11-19 в 09 02 07" src="https://user-images.githubusercontent.com/36986231/202837101-e057a68b-b32b-40e0-925a-737f19a74a7d.png">

**Comment by svde** [comment] 2022-11-19 07:56
Duplicate of https://github.com/domoticz/domoticz/issues/5409 ?

**Comment by kovainfo** [comment] 2022-11-19 08:44
> Duplicate of #5409 ?

not quite
as I understand it, at first they solved one problem, but in the process of solving I got a second one.

**Comment by gizmocuz** [comment] 2022-11-19 16:33
Should be solved with the latest beta 14742

**Closed as completed by gizmocuz** 2022-11-19 16:33 UTC

**Comment by kovainfo** [comment] 2022-11-19 16:51
> Should be solved with the latest beta 14742

it's worked!
