### ISSUE TITLE
Log button on devices tab stopped working and Setpoint line disappeared in day graph for EvoHome Heating devicetypes  

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4408] opened 2020-10-20 15:34 UTC
Latest Beta, (Build 12494) on Linux Debian, RPI/4  and Windows but also failing on earlier versions. 

Browser cache and Appcache cleared but do not solve the issue. 
Nothing in the domoticzlog. 
Warning about deprecated tooltip in console window of browser developer mode. 
Log Button on devices tab does work for other thermostats

Also reported on [Forum post](https://www.domoticz.com/forum/viewtopic.php?f=6&t=34263)

@michahagg @LarsenDX ; could this be related to one of your recent PR's?

**Comment by michahagg** [comment] 2020-10-20 19:34
Hi rwaaren,

Thanks for reporting this issue and for pointing to the forum!

> Latest Beta, (Build 12494) on Linux Debian, RPI/4 and Windows but also failing on earlier versions.
> 
> Browser cache and Appcache cleared but do not solve the issue.
> Nothing in the domoticzlog.
> Warning about deprecated tooltip in console window of browser developer mode.

This warning message would also appear with the AngularJS version the Domoticz UI was using previously. In the version currently used $tooltip is stil deprecated, not yet removed.

> Log Button on devices tab does work for other thermostats
> 
> Also reported on [Forum post](https://www.domoticz.com/forum/viewtopic.php?f=6&t=34263)
> 
> @michahagg @LarsenDX ; could this be related to one of your recent PR's?

This could well be caused by my PR. I will look into this!

Could you please state the browser you are using and it's version? Thank you.

**Comment by rwaaren** [comment] 2020-10-20 20:11
> Could you please state the browser you are using and it's version? Thank you.

Google chrome: Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by michahagg** [comment] 2020-10-22 23:00
@rwaaren the setpoint line had indeed disappeared. But with my latest additions to the PR (#4382) the line is present again. Please wait for it to be merged.

**Comment by rwaaren** [comment] 2020-10-23 00:04
@michahagg Thx. 
I added / fetched your development repo to mine to have a sneak preview 😀

**Comment by brucemiranda** [comment] 2020-10-23 15:57
I thought I was going mad and broke something. Especially since I worked on introducing DHW Setpoints in Evohome and then couldn't see them on the graph!

**Closed as completed** 2020-11-15 15:17 UTC
