### ISSUE TITLE
Session ID not found

### ISSUE THREAD

**Issue by squadramunter** [domoticz/domoticz#3123] opened 2019-03-22 20:30 UTC
Hello I have a problem.

My Domoticz says Error: CheckAuthToken() : session id not found at the command line.

I am currently using the beta version of Domoticz.

I hope you guys can help me with this problem.

**Comment by gizmocuz** [comment] 2019-03-25 07:45
Are you still able to work with domoticz ?

**Comment by Olifant1990** [comment] 2019-03-25 11:14
I am running into a session bug too sometimes.
Something to do with a cookie expiration thing I guess.
My situation:

Latest Beta of domoticz, Windows 10 64 bit and accessing with firefox, latest 64 bit.
When I log in first time, is ok.
Then I click logout and go surfing the internet for a while, leaving firefox open.
When I go back to domoticz, I have to login again, but not possible: domoticz offline page apears.
Only way to get back is open developer tools, go to storage and delete all local cookies, go back to login page and then I am back.
In the log is then indeed this visible: Error: CheckAuthToken(27c750f1911a309c20c8fe438b0e186b_NmIwODhkNTctNWRlMS00NTc1LWI3YWYtN2I5MDMxMjQ0MmRi) : session id not found

Maybe same situation?

**Comment by squadramunter** [comment] 2019-03-26 17:14
What Olifant1990 explain is exact the problem I am facing right now.

I don't know why or what is cousing this problem.

**Comment by ulfh2018** [comment] 2019-03-28 07:55
Just same error message, but no problems logging in after logging out. Using Windows 10 64 bit, Google Chrom and latest beta version of Domoticz running on RPi. (Raspbian stretch light)

**Comment by ulfh2018** [comment] 2019-03-28 08:04
Same problem, but no problem logging in after logging out. Latest version of Beta, running of RPi with Raspbian Stretch Light. Browser is Google Chrome, running on Windows 10 64 bit. Error occures just after logging in

**Comment by Olifant1990** [comment] 2019-03-28 08:10
there have to be a specific time between logout and login action ;)
It seems to be a cookie expiration time or something.
So, logout. Then, when expired, go back and login, then you get a offline message or something.

**Comment by ulfh2018** [comment] 2019-03-29 07:57
I tried to log out for a long time, but still was able to log in, though the error message is the same. Only problem I have with offline message is when I upgrade to a newer version from Domoticz. I cannot log in again, and have to reboot my RPi to make it work.

**Comment by Olifant1990** [comment] 2019-03-29 08:17
But did you keep the browser running when logged out?

**Comment by ulfh2018** [comment] 2019-03-29 09:21
Yes, i certainly did. Tried on 2 different browsers (not at the same time) and from 2  differen machines. Same result each time.

**Comment by morilm** [comment] 2019-04-06 21:31
Hi

I do confirm same issue on Domoticz Beta v4.10602.

2019-04-06 16:23:15.975 Error: CheckAuthToken() : session id not found
2019-04-06 16:23:16.178 Error: CheckAuthToken() : session id not found
2019-04-06 16:23:23.948 Error: CheckAuthToken() : session id not found
2019-04-06 16:23:26.304 Error: CheckAuthToken() : session id not found
2019-04-06 16:23:29.909 Error: CheckAuthToken() : session id not found
2019-04-06 16:23:35.160 Error: CheckAuthToken() : session id not found
2019-04-06 16:23:36.614 Error: CheckAuthToken() : session id not found
2019-04-06 16:23:41.158 Error: CheckAuthToken() : session id not found
2019-04-06 16:23:47.164 Error: CheckAuthToken() : session id not found
2019-04-06 16:23:47.172 Error: CheckAuthToken() : session id not found
2019-04-06 16:23:52.234 Error: CheckAuthToken() : session id not found
2019-04-06 16:23:58.162 Error: CheckAuthToken() : session id not found
2019-04-06 16:23:58.203 Error: CheckAuthToken() : session id not found

No issues accessing Domoticz or running any action or device.

**Comment by astrapowerrr** [comment] 2019-05-03 06:27
I have the same running version 4.10629

`2019-05-02 15:57:52.384 Error: CheckAuthToken(93261ae4bfb3e7b90e8a7dd977529ce3_Y2RlZDdiZTItNmE5Ny00ZjI1LThjYmItNDVjMGE3MmVmYjAy) : auth token mismatch
2019-05-02 15:57:52.404 Error: CheckAuthToken(93261ae4bfb3e7b90e8a7dd977529ce3_YzczNGZkM2MtYWQzMC00NjhjLWFjYWEtZTdjNGE0Mjc4ZGYw) : session id not found`

only appear on fresh startup.

as i believe i had toon thermostaat app installed on previos version.
did recently a fresh clean install on my pi.
and deleted the toon thermostaat from my hardware and devices.
but i believe this still has to do with toon.
i also still have a script running somewhere in my database i have to remove.
but thats another milestone to fix for me.

**Comment by Olifant1990** [comment] 2019-05-03 06:54
I do not have a Toon Thermostat, so this has nothing sololy to do with the session problem.

Maybe I have some clues, I also have a phpliteadmin installed on my server, reachable at the same domain name. If I have logged in here, I have the session problem with logging in to Domoticz afterwards. Maybe it is some kind of session interference? Maybe Domoticz should invalidate the session sooner and create a new one when logging in?

@gizmocuz Do you have a clue somewhere? Seeing all these findings?

**Comment by Olifant1990** [comment] 2019-05-03 07:06
I have tried something:

- Logged in to Domoticz. -> 1 cookie is saved with the name "SID".
- Logged out, and logged back in in Domoticz. No problem yet.
- Logged out from Domoticz
- Logged in to phpliteadmin -> added 1 cookie, called "PHPSESSID", so now I have two cookies, SID and PHPSESSID
- Refreshed login page of Domoticz, seeing my two cookies, logged in and got offline page. Not able to login.
- Removed cookie with name PHPSESSID and refreshed page. And then I am able to get in Domoticz.

**Comment by Olifant1990** [comment] 2019-05-03 07:10
Which is actually strange, because Domoticz is not using PHP btw...

**Comment by gizmocuz** [comment] 2019-05-03 07:50
@Olifant1990 , domoticz can actually use the linux/windows PHP interpreter ... but no, this seems to have nothing to do with the cookie issue

What i suspect is that the cookie from phpmyadmin "PHPSESSID" contains the string SID,
and probably domoticz is searching for SID, founds the wrong cookie, and stops

I suspect cWebem.cpp, line 1590, probably my own fault... i think this should be

if (fpos == 0)

and line 1936 should be changed as well

While we are there... why not rename the session to DMZSID as well

And it needed to be changed at the websockethandler as well

Made some changes in the latest beta version (10672) could you guys test if this solves the issue ?

**Comment by Olifant1990** [comment] 2019-05-03 08:01
That seems to be a very logic explanation for the problem!
Will test it at sunday.

**Comment by gizmocuz** [comment] 2019-05-03 08:26
@Olifant1990 , thanks ! If it is possible to test sooner, that would be great. Was thinking about making a new stable release this weekend... but we could do this of course the next weekend as well ;)

**Comment by Olifant1990** [comment] 2019-05-03 08:43
@gizmocuz Don't hang me on it, but will try to test it this evening

**Comment by astrapowerrr** [comment] 2019-05-03 08:56
I updated from my workplace. But now i cannot connect anymore. Only local if I use VNC. Remotely it says Domoticz offline. 

In the log I don’t see the auth error anymore

**Comment by gizmocuz** [comment] 2019-05-03 09:05
Please try the new beta while testing ( 10674)

**Comment by gizmocuz** [comment] 2019-05-03 09:26
@astrapowerrr , are you using beta 10674 ? Could you try clearing the browser cache and cookies ?

**Comment by gizmocuz** [comment] 2019-05-03 09:27
Only change now is the logout handling and session name has been changed

**Comment by astrapowerrr** [comment] 2019-05-03 10:12
Updated to 10674 and did cleared cache and cookies. Also tried new browser en restarted pi about 3 times. But I can’t access from outside. Only when I VNC and use it local

**Comment by gizmocuz** [comment] 2019-05-03 10:31
Then i suspect it's a firewall issue... i can't seem to think of any way it can be related to the patched code... sorry...

**Comment by astrapowerrr** [comment] 2019-05-03 10:38
I will see this weekend when I am at home.

**Comment by Brackbouille** [comment] 2019-05-03 11:00
Hi Guys,
The session ID problem doesn't appea anymore after updated to 10674.
Thanks a lot for your work
Have a nice we

**Comment by gizmocuz** [comment] 2019-05-03 11:35
Thanks for testing! And @Olifant1990 for finding the duplicate string issue !
If someone else could also verify if this is solved, then please close the issue

**Comment by astrapowerrr** [comment] 2019-05-03 18:33
Found my stupidnes cleared cache for only 7 days.. not all..
So after deleting all. It’s up and running. And rebooted many times but no errors anymore in my log.
So I can confirm that it’s solved!

Thanks

**Comment by gizmocuz** [comment] 2019-05-03 18:57
Thanks for the feedback!

**Comment by kofec** [comment] 2019-05-06 14:26
I have this issue with latest stable version but this is not critical for me. Let wait if others also see this issue. I didn't have this issue with beta V4.10676.
```
2019-05-06 15:31:48.912 Status: Domoticz V4.10693 (c)2012-2019 GizMoCuz
2019-05-06 15:31:48.912 Status: Build Hash: b97777b, Date: 2019-05-06 11:27:06
2019-05-06 15:31:48.913 Status: Startup Path: /usr/share/domoticz/
2019-05-06 15:31:49.004 Sunrise: 05:08:00 SunSet: 20:05:00
2019-05-06 15:31:49.005 Day length: 14:57:00 Sun at south: 12:37:00
2019-05-06 15:31:49.005 Civil twilight start: 04:31:00 Civil twilight end: 20:43:00
2019-05-06 15:31:49.006 Nautical twilight start: 03:42:00 Nautical twilight end: 21:32:00
2019-05-06 15:31:49.006 Astronomical twilight start: 02:42:00 Astronomical twilight end: 22:32:00
2019-05-06 15:31:49.270 Active notification Subsystems: email (1/13)
2019-05-06 15:31:49.286 Starting shared server on: :::6144
2019-05-06 15:31:49.239 Status: PluginSystem: Started, Python version '3.7.2'.
2019-05-06 15:31:49.274 Status: WebServer(HTTP) started on address: :: with port 8080
2019-05-06 15:31:49.282 Status: Proxymanager started.
 2019-05-06 16:21:15.800 Active notification Subsystems: email (1/13)
2019-05-06 16:21:15.804 Status: Incoming connection from: 192.168.1.1
2019-05-06 16:21:15.679 Error: CheckAuthToken(ID=69f8f55f30d4cc644c106c599bdff603_YzYzMTJmYjAtZjg3ZC00NGYyLThmYzUtMWVlZjcyMzY0ZjQw) : session id not found
2019-05-06 16:21:16.247 Status: Incoming connection from: 192.168.1.1
2019-05-06 16:21:16.245 Error: CheckAuthToken(ID=918bbeab7c36f7b9c96e0e52a30ccb2e_YjdkZmYxZjQtMjIzOS00MjRhLWJlODYtMGJlYmVjYTQyYjY4) : session id not found
2019-05-06 16:21:23.981 Error: CheckAuthToken(ID=918bbeab7c36f7b9c96e0e52a30ccb2e_YjdkZmYxZjQtMjIzOS00MjRhLWJlODYtMGJlYmVjYTQyYjY4) : session id not found
2019-05-06 16:21:24.358 Error: CheckAuthToken(ID=918bbeab7c36f7b9c96e0e52a30ccb2e_YjdkZmYxZjQtMjIzOS00MjRhLWJlODYtMGJlYmVjYTQyYjY4) : session id not found
2019-05-06 16:21:24.452 Error: CheckAuthToken(ID=918bbeab7c36f7b9c96e0e52a30ccb2e_YjdkZmYxZjQtMjIzOS00MjRhLWJlODYtMGJlYmVjYTQyYjY4) : session id not found
2019-05-06 16:21:24.904 Error: CheckAuthToken(ID=918bbeab7c36f7b9c96e0e52a30ccb2e_YjdkZmYxZjQtMjIzOS00MjRhLWJlODYtMGJlYmVjYTQyYjY4) : session id not found
2019-05-06 16:21:25.074 Error: CheckAuthToken(ID=918bbeab7c36f7b9c96e0e52a30ccb2e_YjdkZmYxZjQtMjIzOS00MjRhLWJlODYtMGJlYmVjYTQyYjY4) : session id not found
2019-05-06 16:21:25.664 Error: CheckAuthToken(ID=918bbeab7c36f7b9c96e0e52a30ccb2e_YjdkZmYxZjQtMjIzOS00MjRhLWJlODYtMGJlYmVjYTQyYjY4) : session id not found
2019-05-06 16:21:27.493 Status: Incoming connection from: 10.2.2.254
2019-05-06 16:21:27.790 Error: CheckAuthToken(ID=f0f5abd1473409adc7b765241b39c622_ZWM3ZTEwZjAtMjA0Zi00ZmU0LWI5YzUtM2I5ZDVhN2Y4YzMx) : session id not found
2019-05-06 16:21:28.094 Error: CheckAuthToken(ID=f0f5abd1473409adc7b765241b39c622_ZWM3ZTEwZjAtMjA0Zi00ZmU0LWI5YzUtM2I5ZDVhN2Y4YzMx) : session id not found
2019-05-06 16:21:29.330 Error: CheckAuthToken(ID=f0f5abd1473409adc7b765241b39c622_ZWM3ZTEwZjAtMjA0Zi00ZmU0LWI5YzUtM2I5ZDVhN2Y4YzMx) : session id not found
2019-05-06 16:21:29.488 Error: CheckAuthToken(ID=f0f5abd1473409adc7b765241b39c622_ZWM3ZTEwZjAtMjA0Zi00ZmU0LWI5YzUtM2I5ZDVhN2Y4YzMx) : session id not found
2019-05-06 16:21:29.783 Error: CheckAuthToken(ID=f0f5abd1473409adc7b765241b39c622_ZWM3ZTEwZjAtMjA0Zi00ZmU0LWI5YzUtM2I5ZDVhN2Y4YzMx) : session id not found
2019-05-06 16:21:33.403 Error: CheckAuthToken(ID=f0f5abd1473409adc7b765241b39c622_ZWM3ZTEwZjAtMjA0Zi00ZmU0LWI5YzUtM2I5ZDVhN2Y4YzMx) : session id not found
2019-05-06 16:21:35.324 Error: CheckAuthToken(ID=918bbeab7c36f7b9c96e0e52a30ccb2e_YjdkZmYxZjQtMjIzOS00MjRhLWJlODYtMGJlYmVjYTQyYjY4) : session id not found
2019-05-06 16:21:38.676 Error: CheckAuthToken(ID=f0f5abd1473409adc7b765241b39c622_ZWM3ZTEwZjAtMjA0Zi00ZmU0LWI5YzUtM2I5ZDVhN2Y4YzMx) : session id not found
2019-05-06 16:21:44.220 Error: CheckAuthToken(ID=f0f5abd1473409adc7b765241b39c622_ZWM3ZTEwZjAtMjA0Zi00ZmU0LWI5YzUtM2I5ZDVhN2Y4YzMx) : session id not found
2019-05-06 16:21:45.453 Error: CheckAuthToken(ID=918bbeab7c36f7b9c96e0e52a30ccb2e_YjdkZmYxZjQtMjIzOS00MjRhLWJlODYtMGJlYmVjYTQyYjY4) : session id not found
2019-05-06 16:21:47.299 Error: CheckAuthToken(ID=918bbeab7c36f7b9c96e0e52a30ccb2e_YjdkZmYxZjQtMjIzOS00MjRhLWJlODYtMGJlYmVjYTQyYjY4) : session id not found 
```

**Comment by Olifant1990** [comment] 2019-05-06 14:31
@kofec That is correct. The stable is behind the beta version 4.10674.
So: in your beta version (4.10676) it is solved indeed.
The next stable release will have this fix too when the beta turns into a new stable ;)

**Comment by kofec** [comment] 2019-05-06 16:04
@Olifant1990 
Lates stable is Domoticz V4.10693 (above logs) so probably should include fix :-)

**Comment by gizmocuz** [comment] 2019-05-06 16:55
I am having some issues building the stable... it's 10659, history number is not correct.
It will be announced soon
But do try the beta and see if that solves the issue, i thought it should also have been solved in 10659

**Comment by kofec** [comment] 2019-05-06 18:56
The issue was seen on source code (https://github.com/domoticz/domoticz/archive/4.10693.tar.gz). I though it will be next stable.
I tried latest development branch and I don't see/have this issue(log is clean):
```
2019-05-06 20:51:09.080 Status: Domoticz V4.10700 (c)2012-2019 GizMoCuz
2019-05-06 20:51:09.080 Status: Build Hash: 785c6b1e, Date: 2019-05-06 09:01:03
2019-05-06 20:51:09.081 Status: Startup Path: /usr/share/domoticz/
2019-05-06 20:51:09.514 Status: PluginSystem: Started, Python version '3.7.2'.
2019-05-06 20:51:09.549 Status: WebServer(HTTP) started on address: :: with port 8080
2019-05-06 20:51:09.561 Status: TCPServer: shared server started...
2019-05-06 20:51:09.563 Status: RxQueue: queue worker started...
2019-05-06 20:51:11.596 Status: Hardware Monitor: Started
2019-05-06 20:51:11.621 Status: EventSystem: reset all events...
2019-05-06 20:51:11.621 Status: Pinger: Worker started...
2019-05-06 20:51:11.624 Status: dzVents: Write file: /var/lib/domoticz/scripts/dzVents/generated_scripts/Ping lost notification.lua
2019-05-06 20:51:11.625 Status: EventSystem: reset all device statuses...
2019-05-06 20:51:11.826 Status: PluginSystem: Entering work loop.
2019-05-06 20:51:11.954 Status: Python EventSystem: Initalizing event module.
2019-05-06 20:51:11.957 Status: EventSystem: Started
2019-05-06 20:51:11.958 Status: EventSystem: Queue thread started...
2019-05-06 20:51:16.684 Status: Incoming connection from: 192.168.1.46
```

**Comment by kofec** [comment] 2019-05-06 19:03
Should I try https://github.com/domoticz/domoticz/archive/4.10659.tar.gz ?
I'm testing on openwrt environment on many platforms like kirkwood and mipsel.

**Comment by miniche** [comment] 2019-05-08 16:14
Same problem for me after update Domoticz using the "Update Domoticz" menu item, on a RaspberryPi.

Domoticz is started and the web service available. After login, the message "Domoticz offline" is displayed.
In logs files, i can read:

`2019-05-08 18:06:12.039  Error: CheckAuthToken(ID=SESSION_HASH) : session id not found`

Previous installed version: 4.9700
New: 4.10659

I followed the tip here to be: https://github.com/domoticz/domoticz/issues/3185#issuecomment-490231030

Now, I can access to the web pages, but if i enable the authentification again, same problem...

**Comment by szymonskirgajllo** [comment] 2019-05-08 19:12
@miniche do beta update, this problem was fixed in 4.10693 

in command line:
./updatebeta 

enjoy ;)

**Comment by BlomTbl** [comment] 2019-05-09 07:50
I had the same problem after updating Domiticz to the latest stable version 4.10659. After updating to the 4.10693 version the error is gone.

**Comment by gizmocuz** [comment] 2019-05-09 09:47
People we know... and yes you got the same problem as everybody else..
A new release is in the make...

**Closed as completed by gizmocuz** 2019-05-09 09:47 UTC

**Comment by miniche** [comment] 2019-05-09 10:14
@szymonskirgajllo Thanks for the tip, even if I'm not a big fan to use a beta update for a home automation system... I've closed the remote access and only keep the local one right now. Events/anything else works well.

@gizmocuz Happy to see you are aware of this bug :) I know Domoticz is an open source / contribution free software, and many thanks to the domoticz team for the awesome work!

But, I'm very disappointed to have no warning message (Twitter, on the website, on the Domoticz interface itself) if the team is aware of this incident. If people (as me) use everyday Domoticz for home automation, any bug as this one can be very annoying...
Do you have removed this version / ability to perform an upgrade for all other people, before submit the new release?

**Comment by gizmocuz** [comment] 2019-05-10 04:57
@miniche , the problem was that the announcement of a new stable release was not supposed to go out.
(Someone posted this a bit to early!)
It's fixed in the latest stable/beta release 

Next to that, there where lot's of solutions provided on the forum
