### ISSUE TITLE
FIBARO System FGS223 Double Relay not handled correctly 

### ISSUE THREAD

**Issue by SiskoBen** [domoticz/domoticz#3265] opened 2019-05-24 07:22 UTC
I'm running on Domoticz beta v4.10822 and my "FIBARO System FGS223 Double Relay" does get picked up by Domiticz but some how the second relay is not updating and cannot be switched.

Before the OZW update to 1.6 it would work correctly.

Attached ozwcache file, domoticz log file (both with and without the ZWave controller debug on) and screenshots with nodes and devices.

[Fibaro FGS223 in Domoticz v4.10822.zip](https://github.com/domoticz/domoticz/files/3215584/Fibaro.FGS223.in.Domoticz.v4.10822.zip)

Best regards,
Arjan

**Comment by gizmocuz** [comment] 2019-05-24 07:40
@SiskoBen , thanks for the log!

I am unable to test this week (i have one myself) but i noticed this log message:

> 2019-05-24 08:53:26.399 Error, Node009, Received a MultiChannelEncap for endpoint 1 for Command Class 50, which we can't find 

I was testing with my node/switch last Sunday and was experiencing something similar.

I thought that my switch was malfunctioning .... i only got updates for the first switch, nothing was received for the second switch.

Sounds like the issue you have?

Hope to test this again next week.

If you are able to compile and debug the openzwave library/domoticz in the mean time that would be great!

**Comment by SiskoBen** [comment] 2019-05-24 08:12
@gizmocuz , 
Yes, that sounds exactly like the issue i have. only switch 1 updates and switch 2 does not.
Unfortunately I am not able to compile but I am happy to test any new versions to narrow down the root cause.

**Comment by SiskoBen** [comment] 2019-05-24 10:09
@gizmocuz , I was investigating some more and after reading some forumposts i thought i'd look in the OZW control panel to see what it thinks the FGS223 device is. Indeed when selected it only showed 1 switch. Then i did a "Refresh Node Info" on that device from within the OZW control panel and after that the device was suddenly recognized as having 2 switches! Both worked and updated as expected now.
I have no idea why this suddenly started to work. attached the OZW cache and log files from after every thing started to work again for the FGS223.
[Fibaro FGS223 in Domoticz v4.10826.zip](https://github.com/domoticz/domoticz/files/3216317/Fibaro.FGS223.in.Domoticz.v4.10826.zip)

**Comment by gizmocuz** [comment] 2019-05-25 09:38
I think this would have also happened when you selected the node from the Domoticz/ozw/hardware setup and pressed the refresh node info button (center button)
I think it is because when upgrading to the 1.6 library, the 1.6 library does not use the cache (with all known settings) from the 1.4 library but builds a new cache file.
You can test this by stopping Domoticz, deleting the zwcache* file in the config folder and launching Domoticz again
Before you do so, could you select the controller node first (node 1) set the timeout (parameter 5 from my mind, to 10000), and parameter 6 to true, then press apply at the bottom, then repeat the above steps
Maybe the timeout (3000) is to short... to short to receive a expected response form this node
... curious...

**Comment by SiskoBen** [comment] 2019-05-25 11:10
timeouts seem to have disappeared now, see logs and new cache
[Fibaro FGS223 in Domoticz.v4.10826.debug.ozwcache deleted.zip](https://github.com/domoticz/domoticz/files/3219320/Fibaro.FGS223.in.Domoticz.v4.10826.debug.ozwcache.deleted.zip)

**Comment by SiskoBen** [comment] 2019-05-26 05:43
Well strangely i now noticed that this FGS223 (node9) does go 'dead' periodically (and gets revived) with a 'exact' periode of 1 hour. See attached log file and screenshot of a filtered log file.
[Fibaro FGS223 in Domoticz.Revived every hour.zip](https://github.com/domoticz/domoticz/files/3220023/Fibaro.FGS223.in.Domoticz.Revived.every.hour.zip)
I tried to change the two settings (58 and 59) that were 3600 seconds each to 1200 and 900 seconds respectively but i was not able to do it. The OZW control panel doesn't let me change these settings, the Domoticz one does let me change it and 'apply' but they don't get updated on the device (even after 8 hours)

**Comment by gizmocuz** [comment] 2019-05-26 11:13
The timeout parameter I was referring to was from the controller (node 1)

**Comment by SiskoBen** [comment] 2019-05-26 18:09
@gizmocuz , yes i changed the timeout parameter 5 and 6 of the controler as suggested by you. Weirdly the Node 9 is revived every hour and shortly after it goes 'dead', but when a dzvents script is acting on it (even when it is assumed dead) it does actually switch the relays as requested. Maybe the issue is that the two contacts it is switching don't carry any current and thus produce no wattage and thus never report usage except for the default report every 3600 seconds (which is what i wanted to test by setting those to something else than 3600 seconds but it apparently is not possible.

(edits: spelling/grammar)

**Comment by gizmocuz** [comment] 2019-05-30 09:29
@SiskoBen , is it possible to test with beta 10850+ ... there have been some changes. Maybe it will now pickup your second relay. I have a FGD211 and here the second relay does not work, but i suspect thats another issue. I can't help with the node goes dead issue, thats unrelated to the new OZW version (i think).

**Comment by SiskoBen** [comment] 2019-05-30 09:40
@gizmocuz , I managed to change (last saturday) the default report intervals. with great difficulty i might add. I could only do it through the OZW control panel and then only by being very quick to change the value in the box, and clicking the submit button. It appears that the OZW control panel is refreshing that page every second and replacing the value every time. Anyway i changed it and the regular revivals after every 1 hour stopped, now revivals are irregular (5, 15, 20, 70, 45, 10 minutes apart) and the accompanying dead message now is only 5-10 minutes before so the node is now only dead for 5-10 minutes. it might very well be unrelated to the new OZW 1.6 version as i had issues with this node before (although not so regular at 1 hour intervals) and i though it was due to actual reception issues. I will install the newest beta soon and see if that changes anything.

**Comment by SiskoBen** [comment] 2019-05-30 10:31
i updated to v4.10854 and now the ozw cp reports 5 switches (instance 0,1,2,3,127) instead of 2

**Comment by gizmocuz** [comment] 2019-05-30 11:42
Okey, so it's all working now ? you can use the double relays ? The names of the new switches might tell you what they are...

**Comment by SiskoBen** [comment] 2019-05-30 15:43
@gizmocuz , well no (the types were "Switch" and the instance as mentioned 0, 1, 2, 3 and 127 all on node 9, there was no "name" to tell me what they were), i did a refresh node info (to get rid of the erroneous 3 switches in node 9 to get it to show only 2 switches as it should be) and then it only detected just 1 switch. I let it like that for a few hours until the dzvent needed to switch the second switch to see if it would do it, but it didn't. I now did a refresh node info again and now there are 2 switches in node 9 again and the dzvents could succesfully switch them. OZW seems to be very flacky in it's ability to detect properties of ZWave devices on the ZWave network. I am afraid that next time Domoticz is restarted (manualy of after an update) that i have to pray it will pick up all devices as they should, otherwise i wil have to spend time again to "refresh node info" until every thing is working as it should and not touch it again.
For example i had one of the 3 identical Wall plugs report speed in meters per second a few hours ago (how is that in heavens name possible? I have no ZWave device in my network that is even capable of measuring anything in meters per second). Clearly it (probably OZW's fault) is an inaccurate and most of all inconsistent piece of code that is very difficult to get consistent results from. 
Anyway it is now working again.

**Comment by petergebruers** [comment] 2019-05-30 15:47
> For example i had one of the 3 identical Wall plugs report speed in meters per second a few hours ago (how is that in heavens name possible? I have no ZWave device in my network that is even capable of measuring anything in meters per second). Clearly it (probably OZW's fault) is an inaccurate and most of all inconsistent piece of code that is very difficult to get consistent results from.

It has been reported, though it is quite rare. No explanation yet. If you have a full OZW_Log from (before) the moment it happened, it might help diagnose the issue. The OZW issues where you can post your log and discuss this is:

https://github.com/OpenZWave/open-zwave/issues/1687

**Comment by SiskoBen** [comment] 2019-05-30 16:42
@petergebruers , Thanks, i just checked but it appears that the log file (i do have debugging on) is deleted last time Domoticz/OZW started as i now only have a file there of 1MB while i previously had a log of over 25MB. I'm suspecting this is a result of the flacky code as well (to delete log files upon start) making it difficult to diagnose issues.

**Comment by gizmocuz** [comment] 2019-05-30 20:20
@SiskoBen , yes the driver deletes the log on restart
That's probably by design
But since you are reporting here on GitHub feel free to debug the code
Anyway it's not a Domoticz issue so I'm closing this

**Closed as completed by gizmocuz** 2019-05-30 20:20 UTC

**Comment by petergebruers** [comment] 2019-05-31 07:29
For sake of completeness...

OZW does support appending the log file, but it is not the default, it is considered an option for debugging. Debug logging on a large production network will make these files grow fast.

You can enable this by editing the file Config/options.xml and adding this line:

```
<Option name="AppendLogFile" value="true" />
```

Domoticz does not have a GUI/BUI to set this option, I don't think any software has a GUI for this right now. I don't think it needs one, it is an advanced setting anyway.

A full list of setting is here:

https://github.com/OpenZWave/open-zwave/wiki/Config-Options

As a contributor to OpenZWave, I understand it would be nice to have something like "last 5 logs", it is on my agenda, but due to limited resources I don't think that is going to happen soon.

Please refrain from truncating the log while OpenZWave is running, it doesn't handle that.

**Comment by gizmocuz** [comment] 2019-05-31 08:33
I know and I think it is a good thing. Specially when users keep the debug seeing accidentally on.
