### ISSUE TITLE
New Feature Read only device [2020.2 stable]

### ISSUE THREAD

**Issue by D4r1s** [domoticz/domoticz#4306] opened 2020-08-27 16:00 UTC
Hi,
I would like to report request for "read only devices", such as PIR Sensors or Door contact (for them there is no possibility for chagne the status over the www interface) with customise icon. 
It would very helpfull if we can only show the status of the device without change it. 
For example rain sensor, could be change only by external sensor not by www. 
Thanks.

**Comment by kiddigital** [comment] 2020-08-30 07:39
@D4r1s , can you provide a more clear example of what you would like to see? Is it 'just' not showing some buttons? Or do you mean a 'lock' on these devices so they cannot be updates through calling the update method over http? Or something else? It is (for me at least) not really clear what you are requesting.

One or more examples (edited screenshots, flow descriptions, etc) would help a lot.

**Comment by gizmocuz** [comment] 2020-08-30 07:45
@D4r1s , when you press 'Edit' on the Door Contact sensor and change it's type to 'Door Contact' you are not allowed to 'switch' that sensor anymore

**Comment by D4r1s** [comment] 2020-08-30 07:54
@kiddigital 
It will very difficult to show. I try to explain more. Read only means that it will be possible to change status over http request  I can't find in domoticz type of hardware with features:
- status could be change over http request (SendToHTTP 1.1.1.x,8080,/json.htm?type=command&param=switchlight&idx=52&switchcmd=Toggle)
- status can't be change via webrowser (8080) 
- the icon of  the device could be configurable 
Similar behaviur right now have montion sensors by I can't change the icon. 

For exmaple I want to see status of the heating pump but I can't steering it.

@gizmocuz 
Yes, you are right. I tried this with montion sensors but with them  I can't change the icon. 
Me appologise. Thank You for Your time. Problem is solved.

**Comment by gizmocuz** [comment] 2020-08-30 07:56
@D4r1s , yes the status should still be possible to update via the JSON API (it could be a dummy sensor)
Yes some icons you can not change, and this is by design. It clearly is a Motion Sensor.

Closing the issue, please use the Forum

**Closed as completed by gizmocuz** 2020-08-30 07:56 UTC

**Comment by D4r1s** [comment] 2020-08-30 08:54
After all a found the problem with door contact the status could be only closed and open, but for switch  I wish on and off.
