### ISSUE TITLE
Greenwave Powernode 6 not switching in v4.10988

### ISSUE THREAD

**Issue by MarcusKlerks** [domoticz/domoticz#3527] opened 2019-07-13 08:18 UTC
With v4.10988 the Greenwave powernode 6 doesn't switch anymore. Both the hardware properties page in Domoticz as well as the Current Values page in the Z-Wave Control Panel shows that only the first switch (of 6) is recognized. The others aren't listed in Domoticz/inactive in the Control Panel. This first switch does work but with an error in the Domoticz log (Error: ZWave: Node not found! (NodeID: 4, 0x04)).
Reverted to v4.10982 for now where the hardware is working ok.

**Comment by petergebruers** [comment] 2019-07-13 09:57
Thank you for your feedback.

I've issued a warning about this update. With some explanation about what it does.

https://github.com/domoticz/domoticz/issues/3530



> the Current Values page in the Z-Wave Control Panel shows that only the first switch (of 6) is recognized. The others aren't listed in Domoticz/inactive in the Control Panel

Thanks, that is useful information.

**Comment by JurikRistjouw** [comment] 2019-07-13 11:07
i tried editing zwcfg_0xxxx.xml with the suggested xmlns. It also reflects now in ozwcache_0xxx.xml so i guess i did it right, but devices are not switchable. Powerupdate works fine.

**Comment by petergebruers** [comment] 2019-07-13 11:23
Thanks. zwcfg is for stable version with OZW 1.4 and Domoticz beta uses ozwcache* so what you did may be right but nevertheless won't work. I think your best bet is to run an older beta or the stable. BTW the problem is being investigated upstream (OpenZWave).

**Comment by JurikRistjouw** [comment] 2019-07-16 20:52
After all os updates and latest beta 11010. All werkz. Thanx

**Comment by gizmocuz** [comment] 2019-07-18 05:16
Also tested this, all works again. Closing issue

**Closed as completed by gizmocuz** 2019-07-18 05:16 UTC
