### ISSUE TITLE
[Question] Why Google fonts?

### ISSUE THREAD

**Issue by anonimno1** [domoticz/domoticz#4320] opened 2020-09-05 12:35 UTC
Today for a few hours I didn't have Internet access at my home. During this time I noticed, that the webpage of my Domoticz setup takes long to load. This is normally not the case.
Reason I found is that Domoticz tries to connect to the font api from Google? Because I had no net, he just tried and tried until it ran into a timeout and then show normally the webpage.

Why does Domoticz use this? Google is not known to be privacy friendly and if running without internet access, we have an additional delay.
Can this be turned off?

**Comment by gizmocuz** [comment] 2020-09-06 10:54
@anonimno1, is this with the 'default' theme ?

**Comment by anonimno1** [comment] 2020-09-06 12:32
Yes it is.

**Comment by gizmocuz** [comment] 2020-09-06 12:35
@anonimno1 , I think this is related to the high charts library ?
Except this library, the frontpage example used fonts.googleapis ...
No other page

**Comment by anonimno1** [comment] 2020-09-06 12:53
Calling the Dashboard page I see the call to Google. 
Can this be turned of?

**Comment by gizmocuz** [comment] 2020-09-06 13:31
I think this is caused by the inclusion of js\highcharts\themes\dark-unica.js

No this is a third-party library that can be overwritten in the feature

Don't know why this would block so long on your system if you don't have internet

One option is to resolve fonts.googleapis.com in the hostfile to 0.0.0.0 (or googleapis.com) that should directly continue

**Comment by anonimno1** [comment] 2020-09-06 17:09
So I added 
0.0.0.0 fonts.googleapis.com 
to my /etc/hosts
Will cap the net later (my family needs it now) and test.

**Comment by kovainfo** [comment] 2020-09-07 17:54
> Don't know why this would block so long on your system if you don't have internet

The latency is due to the DNS cache. If the Internet provider has an accident or the Internet is absent for any other reason, then requests in the local network continue to arrive at the address from which the answer is expected. If you restart the router, then the cache will be cleared, and everything will work. But this is certainly not a good case for work. 

> One option is to resolve fonts.googleapis.com in the hostfile to 0.0.0.0 (or googleapis.com) that should directly continue

not a very neat solution (albeit a working one), maybe cleaning up the charting libraries in the future?

**Comment by gizmocuz** [comment] 2020-09-08 06:04
@kovainfo , No we can't it is a third party library and will be overwritten when there is a update
Great it's solved for you, closing issue

**Closed as completed by gizmocuz** 2020-09-08 06:04 UTC
