### ISSUE TITLE
Crash when sending level to Z-wave Fibaro shutter

### ISSUE THREAD

**Issue by jputcu** [domoticz/domoticz#3303] opened 2019-06-08 12:33 UTC
* FreeBSD 12.0-RELEASE-p3 FreeBSD 12.0-RELEASE-p3 GENERIC  i386
* Domoticz V4.10874, from github, compiled in Debug
* OpenZwave from github, Version 1.6-733-g16748885-dirty
* "FIBARO System FGRM222 Roller Shutter Controller 2"
~~~~
2019-06-08 14:27:40.837  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SWITCH BINARY, Label: Switch, Instance: 1, Index: 0
2019-06-08 14:27:40.838  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SWITCH MULTILEVEL, Label: Step Size, Instance: 1, Index: 6
2019-06-08 14:27:40.838  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SWITCH MULTILEVEL, Label: Inc, Instance: 1, Index: 7
2019-06-08 14:27:40.838  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SWITCH MULTILEVEL, Label: Dec, Instance: 1, Index: 8
2019-06-08 14:27:40.838  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SWITCH MULTILEVEL, Label: Level, Instance: 1, Index: 0
2019-06-08 14:27:40.839  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SWITCH MULTILEVEL, Label: Open, Instance: 1, Index: 1
2019-06-08 14:27:40.839  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SWITCH MULTILEVEL, Label: Close, Instance: 1, Index: 2
2019-06-08 14:27:40.839  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SCENE ACTIVATION, Label: Scene, Instance: 1, Index: 0
2019-06-08 14:27:40.840  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SCENE ACTIVATION, Label: Duration, Instance: 1, Index: 1
2019-06-08 14:27:40.840  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SENSOR MULTILEVEL, Label: Power, Instance: 1, Index: 4
2019-06-08 14:27:40.840  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: METER, Label: Energy, Instance: 1, Index: 0
2019-06-08 14:27:40.840  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: METER, Label: Power, Instance: 1, Index: 8
2019-06-08 14:27:40.841  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: METER, Label: Exporting, Instance: 1, Index: 32
2019-06-08 14:27:40.842  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: MANUFACTURER PROPRIETARY, Label: Venetian Blind slat position, Instance: 1, Index: 0
2019-06-08 14:27:40.842  Status: OpenZWave: Unhandled class: 0x91 (MANUFACTURER PROPRIETARY), NodeID: 2 (0x02), Index: 0, Instance: 1
2019-06-08 14:27:40.843  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: MANUFACTURER PROPRIETARY, Label: Venetian blind tilt position, Instance: 1, Index: 1
2019-06-08 14:27:40.843  Status: OpenZWave: Unhandled class: 0x91 (MANUFACTURER PROPRIETARY), NodeID: 2 (0x02), Index: 1, Instance: 1
~~~~

Segmentation fault generating a core dump

~~~~
(gdb) bt full
#0  0x093feb7b in OpenZWave::Internal::CC::SwitchMultilevel::SetLevel(unsigned char, unsigned char) ()
No symbol table info available.
#1  0x093fe809 in OpenZWave::Internal::CC::SwitchMultilevel::SetValue(OpenZWave::Internal::VC::Value const&) ()
No symbol table info available.
#2  0x09409524 in OpenZWave::Internal::VC::Value::Set() ()
No symbol table info available.
#3  0x09402430 in OpenZWave::Internal::VC::ValueByte::Set(unsigned char) ()
No symbol table info available.
#4  0x093954d2 in OpenZWave::Manager::SetValue(OpenZWave::ValueID const&, unsigned char) ()
No symbol table info available.
#5  0x08bca1c2 in COpenZWave::SwitchLight (this=0x2a4bd180, nodeID=2, instanceID=1, commandClass=38, value=21) at ../hardware/OpenZWave.cpp:1347
        pDevice = 0x2bf596fc
        bHandleAsBinary = false
        vID = {m_id = 38371345, m_id1 = 0, m_homeId = 3810423520}
        svalue = 21 '\025'
        pNode = 0x2bf598c8
        ex = <error reading variable>
#6  0x08eb1238 in ZWaveBase::WriteToHardware (this=0x2a4bd180, pdata=0xfb6d9200 "\033\364I", length=28 '\034') at ../hardware/ZWaveBase.cpp:910
        pSwitch = 0xfb6d9200
        ID1 = 0 '\000'
        ID4 = 1 '\001'
        cmnd = 2
        indexID = 0
        ID2 = 0 '\000'
        nodeID = 2
        ID3 = 2 '\002'
        level = 21
        instanceID = 1
        svalue = 21
        l = {__m_ = @0x2a4bd208}
        pDevice = 0x2bf596fc
        packettype = 244 '\364'
        subtype = 73 'I'
#7  0x0823aba1 in MainWorker::WriteToHardware (this=0x983ad68 <m_mainworker>, HwdID=2, pdata=0xfb6d9200 "\033\364I", length=28 '\034')
    at ../main/mainworker.cpp:1736
        hindex = 1
...
~~~~

**Comment by petergebruers** [comment] 2019-06-08 12:44
Please try OpenZwave master >= Version 1.6-737-g067d4285, a few commits were pushed very recently to fix issues with SwitchMultiLevel

**Comment by gizmocuz** [comment] 2019-06-08 13:29
You also need to use this in combination with the latest Domoticz code (committed a minute ago)

**Comment by TheUlpio** [comment] 2019-06-08 13:52
I've noticed the same issue after a server power loss in v4.10856. Restoring database from the previous hourly backup has solved for me. Maybe a database corruption issue or I've got a crush?

**Comment by petergebruers** [comment] 2019-06-08 14:04
And the (Domoticz) user, who reported the issue with Multilevel,  quite recently said that the latest master of OZW does not solve his crash or not all crashes. It's being discussed in the OZW google group, so I'll repeat the gist here:

The original question was:
```
I experience coredumps of the OpenZwave library when setting a new level for my Fibaro FGD212 dimmer.
No coredumps when using a Fibaro FGD211 dimmer.
I use openzwave in combination with Domoticz.
```

The main reason for the crash in this case was the FGD212 supports a more recent version of the Set command, and OZW took the wrong path in the code. This was fixed by Fishwaldo on master, but there is still a gremlin... I've got an idea.

If you want to help... Can you please try the "segv" branch of my fork https://github.com/petergebruers/open-zwave

This is what I expect you to see... Instead of crashing, the OZW_Log.txt will show " Duration Value is missing, setting default." 

I was able to set a breakpoint on that line and hit it... But then when I restart ozwcp this no longer happens. IMHO it does not solve the cause, ie the missing Duration value, but avoids the crash...

I am taking an educated guess the FGRM222 might use the same CC and version, but I am not sure.

**Comment by jputcu** [comment] 2019-06-08 14:46
I've now updated Domoticz and Openzwave (1.6-737-g067d4285-dirty) to the latest.

To start fresh I removed all devices from the node, and ask to refresh it's node info which gave the following:
~~~~
OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SWITCH MULTILEVEL, Label: Level, Instance: 1, Index: 0
2019-06-08 16:32:45.744  (Z-wave) Light/Switch (Level)
2019-06-08 16:32:45.745  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SWITCH MULTILEVEL, Label: Bright, Instance: 1, Index: 1
2019-06-08 16:32:45.745  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SWITCH MULTILEVEL, Label: Dim, Instance: 1, Index: 2
2019-06-08 16:32:45.746  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SWITCH BINARY, Label: Switch, Instance: 1, Index: 0
2019-06-08 16:32:45.822  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: MANUFACTURER PROPRIETARY, Label: Venetian Blind slat position, Instance: 1, Index: 0
2019-06-08 16:32:45.822  Status: OpenZWave: Unhandled class: 0x91 (MANUFACTURER PROPRIETARY), NodeID: 2 (0x02), Index: 0, Instance: 1
2019-06-08 16:32:45.822  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: MANUFACTURER PROPRIETARY, Label: Venetian blind tilt position, Instance: 1, Index: 1
2019-06-08 16:32:45.822  Status: OpenZWave: Unhandled class: 0x91 (MANUFACTURER PROPRIETARY), NodeID: 2 (0x02), Index: 1, Instance: 1
2019-06-08 16:32:45.868  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: METER, Label: Unknown, Instance: 1, Index: 0
2019-06-08 16:32:45.868  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SCENE ACTIVATION, Label: Scene, Instance: 1, Index: 0
2019-06-08 16:32:45.868  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SCENE ACTIVATION, Label: Duration, Instance: 1, Index: 1
2019-06-08 16:32:46.148  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: METER, Label: Power, Instance: 1, Index: 8
2019-06-08 16:32:46.148  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: METER, Label: Exporting, Instance: 1, Index: 32
2019-06-08 16:32:46.536  (Z-wave) Light/Switch (Level)
2019-06-08 16:32:46.574  (Z-wave) Light/Switch (Level)
2019-06-08 16:32:46.611  OpenZWave: Value_Added: Node: 2 (0x02), CommandClass: SENSOR MULTILEVEL, Label: Power, Instance: 1, Index: 4
~~~~

Configured the level switch to be a "Blinds percentage".
Then I tried to select a certain opening percentage but get the crash.

Starting Domoticz again I can change the percentage without a crash but I only hear the relay click without doing anything:
~~~~
Status: User: Admin initiated a switch command (7/Rolluik/Set Level)
2019-06-08 16:35:51.161  OpenZWave: Domoticz has send a Switch command!, Level: 57, NodeID: 2 (0x02)
...
Status: User: Admin initiated a switch command (7/Rolluik/Set Level)
2019-06-08 16:36:17.236  OpenZWave: Domoticz has send a Switch command!, Level: 23, NodeID: 2 (0x02)
~~~~

On the other hand, open and close works:
~~~~
Status: User: Admin initiated a switch command (7/Rolluik/Off)
2019-06-08 16:36:26.511  OpenZWave: Domoticz has send a Switch command!, Level: 0, NodeID: 2 (0x02)
~~~

I will now try the "segv" branch.

**Comment by jputcu** [comment] 2019-06-08 15:23
The "segv" branch doesn't crash Domoticz.
Perhaps the crash is more related to the fact I removed and re-added the devices for that node?
The other part of the issue is the level is translated to ON or OFF, no matter what level it is always fully closed and 0 is fully open.

**Comment by jputcu** [comment] 2019-06-08 15:57
Went back to OpenZwave 1.6-737-g067d4285-dirty, and indeed, everything works (setting aside for a moment that I can only fully open/close the blinds) but when I remove the devices for the node and refresh the node, sending a level to the newly discovered level switch gets me a segmentation fault.

**Comment by petergebruers** [comment] 2019-06-08 18:36
@jputcu thanks you for trying that special branch, it confirms this is related to the FGD212 crash. The problem is understood, I've contacted @Fishwaldo and he is thinking about a permanent fix (my branch suppresses the symptoms only). Yes, add/remove is part of the cause of the issue.

I don't think the postioning problem is related, but I am rarely 100% sure :)

I'd check if the FGRM has still parameter 10 "operating mode" set to 1 = Blind mode with positioning and set p 29. Forced Roller Shutter calibration to 1 then check if Roller Shutter performs the calibration process, completing full cycle - up, down and up again.

**Comment by jputcu** [comment] 2019-06-08 20:18
Thanks Peter, the calibration did the trick!
So actually this issue could be referenced to the "add/remove" issue and be closed?

**Comment by petergebruers** [comment] 2019-06-09 06:48
Quite so. The "segv" fix is not yet in OZW master, if you're on master, then remove then add back that node you still get a segv crash. But after restarting Domoticz it should be OK. The cause of the segv in that particular case is a timing/sequence issue that happens only when a node is added. Justin is working on a fix...

**Comment by petergebruers** [comment] 2019-06-13 10:14
FYI a (possible) proper fix is available on the Dev branch (committed a few days ago as commit 1acab8f).. We need more tests & testers because it changes the "interview" order which might change the behavior of devices when freshly added, when you request a NIF or delete the ozwcache file

https://github.com/OpenZWave/open-zwave/tree/Dev

**Comment by boscorelly** [comment] 2019-06-13 11:23
@jiputcu do you have homebridge ? I have the same problem it seems (see linked issue before). 
I am unable to set a percentage through Domoticz, but it works perfectly when i ask Siri to do it !

**Comment by jputcu** [comment] 2019-06-13 17:50
@boscorelly, I don't have a homebridge, but the percentage issue was solved with a calibration.

**Comment by boscorelly** [comment] 2019-06-14 07:38
With the latest domoticz beta update ?

**Comment by jputcu** [comment] 2019-06-15 08:50
Yes, it was 10881 with the latest OpenZwave at that time.

**Closed as completed** 2022-02-15 16:31 UTC
