### ISSUE TITLE
[translation] - french

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz#5435] opened 2022-11-30 09:20 UTC
Hello @gizmocuz , 

it seems I can't see all translations that are available in Transifex : 
![image](https://user-images.githubusercontent.com/35136439/204755573-cd3c69a0-ef56-4947-a5e3-39cb91e75ca9.png)

![image](https://user-images.githubusercontent.com/35136439/204755694-fe3a8181-bafb-464c-a124-077b52f23668.png)

![image](https://user-images.githubusercontent.com/35136439/204756508-de6a9e31-379d-4d9e-a289-5939ec87811c.png)
vs
![image](https://user-images.githubusercontent.com/35136439/204756658-0ae38b73-01a4-4d19-a3a0-cf96e91fabf7.png)

For the button "Add a plan", I have suggested y new translation, as I see "plan" as a kind of room in a house. Only a suggestion

**Comment by gizmocuz** [comment] 2022-12-02 13:01
Thanks for spotting, this was caused by a typo. Fixed in beta 14792

**Closed as completed by gizmocuz** 2022-12-02 13:01 UTC

**Comment by rezzalex** [comment] 2022-12-02 13:17
Thanks @gizmocuz 

spotted another one : 

![image](https://user-images.githubusercontent.com/35136439/205301484-681f4095-b200-4410-9691-a1d286b4540e.png)

![image](https://user-images.githubusercontent.com/35136439/205301580-68fae251-ee40-4fe7-89d3-bde8b36a048d.png)

**Comment by gizmocuz** [comment] 2022-12-02 13:43
You need to translate them on transifex as they are in the system

**Comment by rezzalex** [comment] 2022-12-02 13:44
Already done

**Comment by gizmocuz** [comment] 2022-12-02 15:16
Could you translate the six missing translations as well?

**Comment by rezzalex** [comment] 2022-12-02 15:22
Done on my side, but hard to have the context, I don't know where to find those texts in the DZ UI

**Comment by gizmocuz** [comment] 2022-12-02 15:27
There two left, you should see them in the met Setup (Applications)
