### ISSUE TITLE
ZWave powerplug sometimes reports wrong values

### ISSUE THREAD

**Issue by RDols** [domoticz/domoticz#4277] opened 2020-07-29 18:20 UTC
I have quite some powerplugs, most of them are Neo Coolcam plugs. Yes the cheap china stuff. And a few Fibaro plugs. Start using them about 3 years ago, a graduadly got more of them. I always had problems that sometimes i had usages of MWh. Even with todays beta this happens. Not only with the Neo plugs, also with the Fibaro plugs. In the past i just deleted those values. But with the increasing number of plugs this is not fun anymore. So i decided to see if i can find out why. Got the latest Domoticz and OpenZWave source from github and made a windows debug build.  (ow, normally i run on a raspberry pi). Until now i identified 3 problems.

1. One of my more recent plugs is broken. It simpy reports wrong values sometimes.
2. During startup and "refresh node info" a value of "0" sometimes occur.
3. During startup and "refresh node info" the scaleMultiply is sometimes not set yet (still has the default value of 1) when a (valid) value is received.

I will try to fix 2 and 3. but will take a little time, i'm limited in time.

I pretty sure there is more, but not sure if it's domoticz or the OpenZWave stack.

Don't know if more people have the same issues?

**Comment by SargonofAssyria** [comment] 2020-08-02 19:05
I have sometimes that issue too, but only (as far as know) with the newer Coolcam plugs.

**Comment by RDols** [comment] 2020-08-02 19:32
I guess you have extreme negative values (e.g. -21474832.82)?
(hint: Add 21474836.48 and probably you get the correct value).

That's looks like a issue with the Newer CoolCam plugs (0x1027 / 0x0200).

https://github.com/OpenZWave/open-zwave/issues/2333

**Comment by SargonofAssyria** [comment] 2020-08-03 14:50
Tnx, I look into that.

**Comment by gizmocuz** [comment] 2020-08-11 14:49
Maybe we could write a sanity check for this in the code ?

**Comment by sincze** [comment] 2020-08-11 15:17
Does this illustrate the issue? 
![image](https://user-images.githubusercontent.com/5776333/89915353-88b19a80-dbf6-11ea-9663-d5ec612cbfc0.png)

**Comment by RDols** [comment] 2020-08-11 23:01
Yes thats typically the new neo plug. You see extreme high day to day 
value. Also the spikes.

Look in the openzwave issue i posted earlier. I put some more information 
there.

Still thinking how to solve this on a acceptable way.

Buy in short:
The plug has about a 2.7x too high kwh value. 50% of the power reports are 
erroneous. RF is very poor.

Op 11 augustus 2020 17:18:16 schreef sincze <notifications@github.com>:

**Comment by RDols** [comment] 2020-08-11 23:28
I think it should be solved (partially) in both open zwave and domoticz. 
But how far is acceptable?

In my domoticz debug build i made a simple trap that stores last value and 
compares the new one with this, only accepting small changes. But sometimes 
there is a big (valid) jump in value or counter is dialed back a bit ( dont 
know why). So it needs to be little more complex.

The newer neo coolcam plugs have a faulty KWh report value. About 2.7x to 
high, not sure yet, but it looks a fixed factor. How to handle this? 
Specific code for these plugs? Maybe a lua/dzvents script that 
filters/mutates vaues before its stored?

Hmmmm.....i think i might have an idea...create a dummy meter for every 
plug. When an zwave plug has a new KWh value filter/correct this with an 
dzvents script and store it in the dummy device.

I curious about your thoughts about this. If someone else a contribution on 
this topic, please feel welcome to join this discussion.

Regards, Richard




Op 11 augustus 2020 16:49:57 schreef gizmocuz <notifications@github.com>:

**Comment by chatainsim** [comment] 2020-08-18 16:14
For me, almost all my powerplug, neo coolcam and Hank stop reports all consumption value.

**Comment by RDols** [comment] 2020-08-23 16:53
> Maybe we could write a sanity check for this in the code ?

@gizmocuz 
I'm still working on this. In my local debug build i have an check build into the ZWave interface that validates a new KWh meter value, and some known issues (like unrealistic values).

What the check does is remember the last received 5 value's (even if they were wrong, so a jump in the value's does not cause a lockup). Take the median of these 5. And check if the average power between the median and new value does not exceed 10KWatt.

I also going to do a pull request in the Open Zwave repository, but that will only add some basic checks on the message that are missing. This will not solve the coolcam plug problems.

I still need to do a little refactoring and cleanup before it's ready for a pull-request. Also need to know if you think this is acceptable solution.

Regards,
  Richard Dols

**Comment by RicardP** [comment] 2020-08-24 20:29
Handling of bogus data reports should of course be fixed by at the root cause. If a crappy devices is malfuctional it should be fixed or claim money back from the supplier. I do not want "sanity" checks of my data.

**Comment by RDols** [comment] 2020-08-25 20:16
@RicardP 
Thanks, for your input. I welcome it. I (partially) agree what you say. When possible fix it at the source. But there is also something as a circle of influence. Looking what is needed to "fix" the newer CoolCam plugs im absolutely not convinced that's worth doing, and could have some side effect in the future. Even after this fix, it's horrible. It's "spontaniously" switches off/on. 

The more general filter that im testing with, filters out outliers and is a more serious candidate for a PR. There are more sources of outliers, not only faulty reports/devices. e.g. I have seen reports of two different meters merged together resulting in a valid checksum and structure, impossible messages and values (btw, these are filtered by OpenZWave stack). Not only with the coolcam plugs, but also with fibaro and qubino equipment.

@gizmocuz 
Maybe you can shine some light on this matter?

**Comment by gizmocuz** [comment] 2020-09-13 06:19
@RDols , I think you could check if the power reported is above 6K, and if so skip the reading. (6000/230V is a fuse of 26 Amps, and I don't think anyone will have this)
Still this is not a fault from OpenZWave or Domoticz.
I bought myself a Neo Coolcam powerplug and will do some testing

**Comment by RDols** [comment] 2020-09-13 19:33
@gizmocuz , I found so many problems with the new version of plug (0x1027 / 0x0200). I'm going to dig a deep hole, throw them in, burn it and doing a ritual dance. I have 3 plugs, two different firmware versions. All have the same problems:
- 50% false value in KWH counter (typically negative values)
- KWH counter runs 3x to fast
- KWH dials itself back (sometimes serveral KWH), always after replugging, but also spontaniously
- A few times a day it turns itself off for a second. (reboot???)
- Every few days the whole plug hangs. Needs a replug to get it working again.
- Horrible contribution to your zwave network. (the older plugs have the same problems btw). A route through a plug is not stable.

Looking at other power reporting devices. I'm not 100% where the problem comes from. Maybe the ZWave stick i use. I have this a few years, no firmware updates. No way it does not contains bugs. Mixing up 2 messages is not something that happens in the air, it's either a router or the stick. The checksum is a parity checker. It's very easy to masquarade an error. But i don't know if over the air is also an parity check or CRC16. But what it is, it happes before openzwave and domoticz.

**Comment by jellewie** [comment] 2021-03-17 12:17
Not sure If this is completely the right place, but https://www.domoticz.com/forum/viewtopic.php?f=24&t=33679&p=271170#p271170

The '**WR01ZE**' sends a "32bit Integer" in "Electric - kWh:" but a "Signed 32bit Integer" is displayed
The value is incremental, So the power used since start/reset (and does NOT reset every week/month time!)

**Manual compensation fix** (Not completely proven, but are within 2% margin of error with my data, can definitely be a rounding error)
```
Where 'x' is the value in 'Week' stats of a day in Domotics "IP/#/Devices/57/Log" log
Where 'y' is the value of 'RAW: Electric kWh' in 'IP/ozwcp/cp.html -> Current Values'

kWh since start = x-(2/100*2^30)
y = x*(-100)
x = y/(-100)
```


**Links:**
- https://www.domoticz.com/forum/viewtopic.php?t=33679 (linked before)
- https://www.domoticz.com/forum/viewtopic.php?t=28987
- https://community.openhab.org/t/strange-numbers-in-kwh-meter-display-of-nas-wr01ze/97988
- https://tweakers.net/productreview/233142/neo-coolcam-power-plug.html

**Comment by waltervl** [comment] 2022-02-15 16:15
Closing this old issue. OpenZwave is deprecated and succeeded by ZwaveJS2MQTT https://www.domoticz.com/wiki/ZwaveJS2MQTT

**Closed as completed** 2022-02-16 22:29 UTC
