### ISSUE TITLE
Safari floor plan doesn't work

### ISSUE THREAD

**Issue by acaonweb** [domoticz/domoticz#5201] opened 2022-03-21 22:36 UTC
It's impossible move devices on floor plane because crosshairs is not usable

**Comment by gizmocuz** [comment] 2022-03-22 07:08
@acaonweb , when you report a issue, you should have seen the guidelines.
In these guidelines it was requested to enter some more information than you just did
Is this on mobule device like a iPAD/iPhone or on a actual mac PC ?
If the first, then this is by design (mobile device). On a mac PC it should work.
I'm using the EDGE browser on all my devices without issues, but for sure I am not going to configure a system on a mobile device, it's to small and can cause issues.

**Comment by acaonweb** [comment] 2022-03-22 07:20
Sorry you're right, my fault 
Safari, on iMac with MacOS Monterrey 

I've reported (probably on domoticz forum) years ago. 
But the function isn't needed on mobile/iPad for the reasons you said 
On macOS, Chrome works, but not on safari. Crosshair is only a red vertical line. 

Thanx.

**Comment by gizmocuz** [comment] 2022-03-22 07:29
I'm afraid I am unable to assist you hear as the first thing I always did was install another browser
These days 'Edge', it's blazing fast and based on Chromium. It also can be installed on all devices and makes it perfect for syncing or working across multiple devices

https://www.microsoft.com/en-us/edge?r=1

If it works on Chrome/Firefox/Edge then I think the issue should be fixed by Safari 

If you know some JS code, please have a look in the **FloorplanEditController.js** file , it could be there is a issue in this file that needs to be solved specifically for Safari

**Closed as completed** 2022-04-05 18:18 UTC
Labels: PendingFeedback
