### ISSUE TITLE
[Python Plugins Framework] Memory leak

### ISSUE THREAD

**Issue by stas-demydiuk** [domoticz/domoticz#4929] opened 2021-09-07 16:36 UTC
I have migrated [my python plugin](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin) to an extended version of python plugins framework and after that several users have reported that now they have a memory leakage in Domoticz caused by the updated plugin

Unfortunately, I don't have many details to provide. I went through the code but unfortunately haven't found anything that could cause the issue from the plugin side, code and overall approach are pretty the same comparing to the previous plugin version without the memory leak. 2 key changes are:
- plugin now uses `DomoticzEx` module
- plugin started widely using `Domoticz.Configuration()` feature

One of the users also mentioned that he saw similar issues with some other plugins that use `Domoticz.Configuration()` feature.

@dnpwwo, I wonder if you could please take a look or suggest how to better debug the issue to find the root cause.

Link to the original issue: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/698

**Comment by stas-demydiuk** [comment] 2021-09-07 16:41
Not sure, but maybe #4881 may somehow be related as well.

**Comment by pipiche38** [comment] 2021-09-07 17:26
I have stopped using Configuration() due to that memory leak , which exists already in the 2021.1 stable version

It is easy to duplicate as soon as you start saving a big chunck of data. Last point the leak is happening in the Domoticz side, as if you stop the plugin the leak remain allocated.

https://domoticz.com/forum/viewtopic.php?f=65&t=36956

**Comment by kiddigital** [comment] 2021-09-08 04:56
@pipiche38 for ease of reproducing the memory leak, could you post your test Python plug-in?

**Comment by pipiche38** [comment] 2021-09-08 06:36
Plugin is quiet basic,  but is available on the forum
https://domoticz.com/forum/viewtopic.php?p=279372#p279372

**Comment by dnpwwo** [comment] 2021-09-08 06:47
I will have a look. 
It has some non-standard things but I never changed it because it seemed to work (functionally it least).

**Comment by pipiche38** [comment] 2021-09-08 08:20
> I will have a look.
> It has some non-standard things but I never changed it because it seemed to work (functionally it least).

let me know if I can do anything.

**Comment by dnpwwo** [comment] 2021-09-09 07:01
Pushed a fix, looks like the JSON Protocol in the framework has always had a leak :(

**Comment by pipiche38** [comment] 2021-09-09 12:10
well done @dnpwwo , it is fixed on my end , happy to be able to move forward using the Domoticz DB to store plugin Configurations

**Comment by Eddie-BS** [comment] 2021-09-10 06:52
problem solved here, running for at least 16 hours and still under 90MB

**Closed as completed** 2021-09-10 23:29 UTC
