### ISSUE TITLE
Names not showing up in OZWCP

### ISSUE THREAD

**Issue by Vinisz** [domoticz/domoticz#3218] opened 2019-05-15 09:23 UTC
After upgrade to OZW 1.6, names configured in Domoticz are not showing up anymore in the OpenZwave Control panel.

Version: 4.10752
Build Hash: 4c51a84c
Compile Date: 2019-05-15 10:42:34
dzVents Version: 2.4.20
Python Version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]

**Comment by gizmocuz** [comment] 2019-05-15 09:27
Maybe this is caused by the creation of the new cache file by the 1.6 library
If you name them again, is that working ? (try a restart as well)

**Comment by Vinisz** [comment] 2019-05-15 09:47
Hi, when putting the name in again in domoticz, it is updated in OZWCP as well.
However, I also tried a reboot after that and then the new entered name is lost again (and also the old ones did not re-appear)

**Comment by Vinisz** [comment] 2019-05-15 09:55
btw, I upgraded first and put a databse from a previous version back, does this have impact or is the DB itself unchanged after the upgrade ?

**Comment by stuiow** [comment] 2019-05-18 18:13
I have also noted a similar behaviour.
All nodes have been given names in z-wave hardware screen.
Those names were copied over to OZW successfully.
However, on reboot, some of the names go missing. (they are generally battery powered devices like smoke alarms, PIR's and door sensors.
Running 4.10778 beta.
m,ight also add that the devices manufacturer and descriptions also go missing, but some of these got collected later on in the day automatically.

**Comment by gizmocuz** [comment] 2019-05-19 07:13
Double checked this, the names are stored in the database, tested this with the latest beta (10793) and the problem did not arise ... 
Still a problem ?

**Comment by nixalsschrott** [comment] 2019-05-22 11:53
Dear friends,

I can confirm this issue for several beta releases now. I actually tested with 4.10806 and before with 4.10779. I also assume the issue was raised with open zw v1.6.
I am running Domoticz on Synology DS918+ (apollolake).
In the beginning I also experienced problems with a stopping Domoticz installation and several functions not working (also scenes).
I several times did the Test&Heal and also refresh node info via zw Control Panel. Functions are working again, but the names are still missing.
![68C2010A-0167-4DC6-9E29-9C238050E267](https://user-images.githubusercontent.com/41418189/58172400-c5fbd680-7c98-11e9-8117-6dceace07965.png)

Kind regards
matty

**Comment by xztraz** [comment] 2019-05-22 14:14
DOMOTICZ V4.10806

![image](https://user-images.githubusercontent.com/25690871/58181675-8212cc80-7cac-11e9-9e04-875e9e74e40a.png)
![image](https://user-images.githubusercontent.com/25690871/58181705-8e972500-7cac-11e9-8e77-976a267f6037.png)

unknown is a fibaro FGD-212 (dimmer 2)

**Comment by gizmocuz** [comment] 2019-05-22 15:09
@nixalsschrott, have you tried giving them a name again ?

**Comment by nixalsschrott** [comment] 2019-05-22 15:16
No, I did not give new names since in devices tab the names are still existent.
I am also using the names in scenes and events, so I am a bit afraid to break the syntax.
I am still hoping that somehow the names could sync/refresh back without renaming.

![CEA3A79D-9C70-46BC-96CB-CBB4317A1953](https://user-images.githubusercontent.com/41418189/58186517-57794180-7cb5-11e9-9c15-9fcd8e38a45f.png)

**Comment by gizmocuz** [comment] 2019-05-22 15:18
@nixalsschrott , the names in the zwave/hardware setup for the nodes has nothing to do with the names you give it internally in domoticz actually

**Comment by nixalsschrott** [comment] 2019-05-22 20:13
Well, I just tried to manually give names via OpenZWave Control Panel. Unfortunately Domoticz surprisingly stopped again (this problem was already discussed elsewhere and seems still not be solved) and after restart all given names where erased again.

**Comment by gizmocuz** [comment] 2019-05-23 08:53
@nixalsschrott , can you give the names in the Domoticz hardware setup ? (and not via the control panel)

**Comment by xztraz** [comment] 2019-05-23 11:28
i think if a sensor have other faults the name gets screwed up..

my fibaro dimmer for example.
i can rename it. restart domoticz. it still have the name but if i push refresh on that node it gets "unknown" as a name

nodes that works doesn't change name when refreshed

before resfresh
![image](https://user-images.githubusercontent.com/25690871/58249280-b777f280-7d5e-11e9-92b5-865a7170329a.png)

after refresh
![image](https://user-images.githubusercontent.com/25690871/58249290-c068c400-7d5e-11e9-82d4-c0ea8cc98584.png)


log when doing a "refresh node info"
```
May 23 13:23:14 raspberrypi domoticz: OpenZWave: Node Removed. HomeID: 3698476673, NodeID: 11 (0x0b)
May 23 13:23:14 raspberrypi domoticz: OpenZWave: New Node added. HomeID: 3698476673, NodeID: 11 (0x0b)
May 23 13:23:15 raspberrypi domoticz: OpenZWave: Unhandled class: 0x2B (SCENE ACTIVATION), NodeID: 11 (0x0b), Index: 0, Instance: 1
May 23 13:23:15 raspberrypi domoticz: OpenZWave: Unhandled class: 0x2B (SCENE ACTIVATION), NodeID: 11 (0x0b), Index: 1, Instance: 1
May 23 13:23:16 raspberrypi domoticz: OpenZWave: Received timeout notification from HomeID: 3698476673, NodeID: 11 (0x0b)

```

**Comment by xztraz** [comment] 2019-05-23 16:38
i need to push refresh and shortly after refresh node info then i get unknown as a name. 
Edit. it's actually quite random i find. just pushing refresh and refresh node info on random modules seem to give unknown. sometimes need to reload page to see that

**Comment by nixalsschrott** [comment] 2019-05-27 11:50
> @nixalsschrott , can you give the names in the Domoticz hardware setup ? (and not via the control panel)

OK. I did enter the names as suggested. After restart most of the names still exist, only one is lost again. Actually testing with V4.10806.

From my point of view meanwhile all functions work, switches, scenes and groups. Also status is reflected correctly for every device. I also did not experience any unexpected shutdown.

Kind regards
Matty

**Comment by gizmocuz** [comment] 2019-05-27 12:31
Thanks for the feedback, closing issue

**Closed as completed by gizmocuz** 2019-05-27 12:31 UTC

**Comment by xztraz** [comment] 2019-05-28 16:46
If pushing refresh node info on a node names get reset to unknown in DOMOTICZ V4.10841 still. but i'll start a new issue
