### ISSUE TITLE
crash after using device

### ISSUE THREAD

**Issue by Lyr3x** [domoticz/domoticz#1710] opened 2017-07-23 15:58 UTC
Domoticz Version: 3.8114
RPI 2

After using a device domoticz freezes immediately (wihtout any log entry), since the update to the latest version.

**Comment by hvbommel** [comment] 2017-07-23 16:39
See forum, a user variables fix is waiting to be merged. In case you use indeed user variables the problem is known and will be fixed in one of the upcoming versions. If so for now revert to V3.8100. If you are not using user variable you may be looking at a different problem.

**Closed as completed** 2017-07-23 17:22 UTC
