### ISSUE TITLE
Master device change not sent to websocket

### ISSUE THREAD

**Issue by MAkerboom** [domoticz/domoticz#3768] opened 2019-12-01 14:59 UTC
If a slave devices changes state and triggers the master device state. The master device change isn't pushed to the websocket.

**Comment by gizmocuz** [comment] 2019-12-03 07:23
@MAkerboom , you have to be way more specific as my tests are working...

What type of slave hardware/device are you using ? Maybe it is a hardware/plugin that is directly poking/peeking in the database and does not use the standard ways to update it's status

What i tested:
- I setup a 'Slave' Domoticz and a 'Master' Domoticz
- My 'Master' Domoticz is connecting to the slave (via the Domoticz remote Server hardware type)
- On the 'Slave' i added a Dummy hardware, and created a dummy switch
- On the master i made sure 'accept new devices' is enabled in the settings
- On the slave i toggled the on/off status of the switch, this shows up in the log of the master
- On the master I added the remote switch that is received from the devices page
- On the master i opened the switches tab, and am looking at the remote switch
- When i toggle the switch on the slave, i see the status updating immediately on the master
- Same when i do this on the master, i see the status changing on the slave

**Comment by MAkerboom** [comment] 2019-12-03 19:29
@gizmocuz 
I'm sorry, I didn't mean a master/slave instance of Domoticz.

Following master device (Televisie) changes when the slave device ($Televisie) is updated. But only the slave device update is sent to the webservice updating the GUI. (changes to $televisie are done by the PING device)

![image](https://user-images.githubusercontent.com/4593646/70082823-829d0000-160b-11ea-92fe-5a58b4c9f973.png)

**Comment by MAkerboom** [comment] 2020-03-03 21:04
> @MAkerboom , you have to be way more specific as my tests are working...
> 
> What type of slave hardware/device are you using ? Maybe it is a hardware/plugin that is directly poking/peeking in the database and does not use the standard ways to update it's status

@gizmocuz : Isn't the domoticz core updating the status directly in the database?
https://github.com/domoticz/domoticz/blob/a06400e0528f3583a3f51f54a4488a8cd25c0a6d/main/SQLHelper.cpp#L4117

And this [TODO](https://github.com/domoticz/domoticz/blob/a06400e0528f3583a3f51f54a4488a8cd25c0a6d/main/SQLHelper.cpp#L4201) pointing to the spot where the EventSystem needs to be notified?

**Comment by rhuijben** [comment] 2020-06-29 07:04
I see a similar issue. I have lights in my living room which can be switched on/off by multiple KAKU switches, which are recorded via RFLink. When I switch these lights on by the switches marked as slave device in domoticz the UI doesn't get the required notification to show the light as switched.

**Comment by rhuijben** [comment] 2020-06-29 07:05
It looks like this is a regression with the introduction of the websockets in the UI. If you just refresh the page things work just fine.

**Comment by waltervl** [comment] 2022-02-18 22:37
I close this old topic. If someone has an issue with master/slave devices and/or master slave Domoticz instances please create a new one.

**Closed as completed by waltervl** 2022-02-18 22:37 UTC
