### ISSUE TITLE
Neighbours Graph not working

### ISSUE THREAD

**Issue by candrea77** [domoticz/domoticz#3951] opened 2020-02-26 21:42 UTC
On my system (100+ zwave device) Neighbours graph isn't working.
At first stage it seems to work but after a while it stop to work

Latest image is completely blank , z wave isn't fully initialized yet.

See attachments 

![ZWAVE-10sec](https://user-images.githubusercontent.com/26028217/75390720-06077e00-58e9-11ea-853e-6eb0eaee5a59.PNG)
![ZWAVE-60sec](https://user-images.githubusercontent.com/26028217/75390723-06a01480-58e9-11ea-9125-7307a83cfefd.PNG)
![ZWAVE-120sec](https://user-images.githubusercontent.com/26028217/75390724-0738ab00-58e9-11ea-898b-e565bb114952.PNG)
![ZWAVE-180sec](https://user-images.githubusercontent.com/26028217/75390726-0738ab00-58e9-11ea-9507-9bbf9ee6202d.PNG)
![ZWAVE-300sec](https://user-images.githubusercontent.com/26028217/75390727-07d14180-58e9-11ea-90cf-56bd43014461.PNG)
![ZWAVE-360sec](https://user-images.githubusercontent.com/26028217/75390728-07d14180-58e9-11ea-9c40-404c899da163.PNG)

**Comment by gizmocuz** [comment] 2020-03-03 12:26
I think it is related to the amount of nodes you have...
Maybe we have to look for another representation ?

**Comment by candrea77** [comment] 2020-03-03 19:48
Yes, I can use ozwcp to see Neighbours
I just reported it as an issue because this function do not work after update to this new version.

Peace and love

**Comment by gizmocuz** [comment] 2020-03-04 06:57
@candrea77 , could you post a screenshot of how this looks with this many nodes ? (the control panel)

**Comment by dannybloe** [comment] 2020-03-04 07:46
I have about 50 nodes and also not seeing anything. Maybe we just should increase the max for the chart and have the user decide if the chart is useful for him or not. Then in the future we could look at other ways to visualise the mesh. At least something like a message should be displayed when the max is reached so you know there's not some kind of bug.

**Comment by gizmocuz** [comment] 2020-03-04 07:50
@dannybloe , the problem is that the lines are also getting to small
I am looking for an good/final alternative way to represent the neighborhood nodes somehow
Maybe a 'table' is the answer ?
Users will report problems when they have 51 nodes...
Open for suggestions...

**Comment by candrea77** [comment] 2020-03-04 10:40
This is a screenshot of my actual graph after zwave initialization.

![Nodi](https://user-images.githubusercontent.com/26028217/75871516-f7e7bf00-5e0c-11ea-91e6-c3cbd36817af.PNG)

**Comment by dannybloe** [comment] 2020-03-04 10:41
Well, I don't mind not showing the graph when there are too many nodes (until we have a solution). Was just suggesting that in that case just show a message telling there are too many nodes so the user knows this is by design.

**Comment by gizmocuz** [comment] 2020-03-04 13:20
@candrea77 , sorry I meant a screenshot from the control panel

**Comment by candrea77** [comment] 2020-03-04 15:44
here you are .... is at 100% zoom , it does not fit into the entire screen (FHD)
![ozwcp](https://user-images.githubusercontent.com/26028217/75896452-68a3d100-5e37-11ea-953b-f3c3bf3c959e.PNG)

**Comment by gizmocuz** [comment] 2020-03-05 14:08
Wow ;) thank you ! Okey I don't think this is a solution ;)

**Comment by marmooooo** [comment] 2020-04-01 11:29
in case it helps with the investigation, I repro it as well with **61 nodes.** When looking into the debugging console of the browser I see this: 

_Highcharts expects point configuration to be numbers or arrays in turbo mode
This error occurs if the series.data option contains object configurations and the number of points exceeds the turboThreshold. It can be fixed by either setting turboThreshold to a higher value._

In case it might be relevant. Thanks.
-m

**Comment by Kahuna711** [comment] 2020-05-06 20:50
My neighbor graph is complete empty, too. I have about 87 nodes and I already exceeded the highest node number (232) one time! 
Second strange problem is that my controller Aeotec Z-Stick Gen 5 doesn't show neighbors with node id >= 61 (see screenshot). There are definitely nodes with id# >= 61 in direct range of the controller.  These behavior have some of the other device nodes, too. 

When I use Silabs PC Contoller Software with the Z-Stick the neighbor map is much more complete - many more neightbors with node# >= 61 are shown. 
<img width="1525" alt="ZWaveConsole" src="https://user-images.githubusercontent.com/48985894/81227160-3efc5700-8fec-11ea-8599-11fa9c9abb61.png">
<img width="1165" alt="neighborgraph" src="https://user-images.githubusercontent.com/48985894/81228384-4cb2dc00-8fee-11ea-8b63-51f3eac60e22.png">

**Comment by waltervl** [comment] 2022-02-15 16:03
As OpenZwave is deprecated and succeeded by ZwaveJS2MQTT this issue will not be fixed.

**Closed as completed by waltervl** 2022-02-15 16:03 UTC
