### ISSUE TITLE
Smart P1 Meter daily graphs rounding issue 

### ISSUE THREAD

**Issue by DGA45** [domoticz/domoticz#5576] opened 2023-01-29 09:41 UTC
I have current meters measuring current consumption in A of several devices.
Since I also wanted to have the kWh yearly reports with costs and year per year comparison from the Smart P1 Meter devices, I created corresponding virtual Smart P1 Meter devices, fed using a simple dzVents script, like this:
```
local power = device.current * 230            
local kWhdeviceName = string.gsub(device.name, "%(A%)", "(kWh)")
local oldUpdate = domoticz.devices(kWhdeviceName).lastUpdate.dDate
local timeUpdate = domoticz.time.dDate
local delta_time = (timeUpdate - oldUpdate) -- seconds
local kWhcounter1 = domoticz.devices(kWhdeviceName).usage1
local kWhcounter2 = domoticz.devices(kWhdeviceName).usage2                    
if (isHP) then
    kWhcounter1 = kWhcounter1 + power*delta_time / 3600  -- per hour
else
    kWhcounter2 = kWhcounter2 + power*delta_time / 3600  -- per hour
end
domoticz.devices(kWhdeviceName).updateP1(kWhcounter1, kWhcounter2, 0, 0, power, 0)
```

I have one device most of the time asleep with a current consumption of 0.06A.
The graph of the corresponding current meter device in domoticz is perfectly flat:
![Counter daily log flat current](https://user-images.githubusercontent.com/59612603/215317485-a52e76fd-16be-4e8d-a4d2-0f5531d90e2a.PNG)

However, the corresponding Smart P1 Meter show glitches:
![Counter daily log rounding issue](https://user-images.githubusercontent.com/59612603/215317480-b603b4e0-4a05-44a1-9d01-317c0481c19c.PNG)

The problem is due to the fact that Smart P1 Meter counters are internally float, but reported as integers in the JSON Rest API day report.
In the above graph, before 9:10, the ShortLogInterval was 5 minutes.
Every 5 minutes, we have 0.06A * 230 = 13,8W, thus 13.8W * 5/60 = 1,15 kWh.
As the report rounds values to integers, it displays only 12W and from time to time 24W (since 1LSB on the kWh counter represents 12W at 5 minutes step).
After 9:10, I changed the ShortLogInterval to 2 minutes, and now we have 13.8W * 2/60 = 0,46 kWh.
Thus, the graph displays values only once every 2 minutes step , but with higher values since now 1LSB from the kWh counter represents 30W at 2 minutes step).

Is it possible to report counters and values in float so that the graphs, but also other reports based on the daily JSON API will be more accurate ?

**Comment by gizmocuz** [comment] 2023-01-29 09:56
`Since I also wanted to have the kWh yearly reports with costs and year per year comparison from the Smart P1 Meter devices`

Should you not use a general kWh device type instead of a P1 meter type that was designed for a P1 meter?

**Comment by DGA45** [comment] 2023-01-29 10:05
Drawback is that it has only one counter, while P1 Smart Meter has 2 which I am using to log total of kWh as per T1 / T2 costs.
The Smart P1 Meter is very good for that, since you also have the T1/ T2 ratio in the log / year reports

**Comment by gizmocuz** [comment] 2023-01-29 10:12
Well you are not measuring on a P1 meter so you should use the kWh device type
It makes absolutely no use to display floating point values for the P1 meter.
The usage on a P1 meter is not < 1 Watt, it is quite some more and can go up to 17 kWh
You are also talking about 0.06A of some 'several devices' in Ampere. Not sure how much the voltage is, but you go from Amps to Watts I assume.
I would use a general kWh device type as this does allow you to have a much more accuracy...

**Comment by DGA45** [comment] 2023-01-29 10:27
Unfortunately, the JSON API daily report of Generic kWh is only exporting hour per hour, not as per the shortlog interval:
```
	"CostEnergy" : 1821,
	"CostEnergyR1" : 800,
	"CostEnergyR2" : 800,
	"CostEnergyT2" : 1360,
	"CostGas" : 6218,
	"CostWater" : 16473,
	"Divider" : 1000.0,
	"DividerEnergy" : 1000.0,
	"DividerWater" : 100.0,
	"ValueQuantity" : "",
	"ValueUnits" : "",
	"method" : 0,
	"result" : 
	[
		{
			"d" : "2023-01-22 12:00",
			"v" : "0.000"
		},
		{
			"d" : "2023-01-22 13:00",
			"v" : "10.000"
		},
		{
			"d" : "2023-01-22 14:00",
			"v" : "10.000"
		},
		{
			"d" : "2023-01-22 15:00",
			"v" : "10.000"
		},
		{
			"d" : "2023-01-22 16:00",
			"v" : "10.000"
		},
		{
			"d" : "2023-01-22 17:00",
			"v" : "0.000"
```

**Comment by gizmocuz** [comment] 2023-01-29 10:34
when I issue this for a kWh device:

http://<ip address:port>/json.htm?idx=IDX&method=1&range=day&sensor=counter&type=graph

I receive shortlog values

"result" : 
	[
		{
			"d" : "2023-01-24 09:05",
			"v" : "83.000"
		},
		{
			"d" : "2023-01-24 09:10",
			"v" : "82.000"
		},
		{
			"d" : "2023-01-24 09:15",
			"v" : "80.000"
		},

**Comment by gizmocuz** [comment] 2023-01-29 10:36
And you can also use a additional Watt device?

**Comment by DGA45** [comment] 2023-01-29 10:40
Ok, I missed the "method=1", thanks.
Do you know how I could "easily" migrate my existing virtual Smart P1 Meters to Generic kWh without loosing existing history (apart the T1/T2 values which would be summed) ? I am afraid it must be thru sqlite and some SQL magics ?

**Comment by gizmocuz** [comment] 2023-01-29 10:42
I'm afraid you have to use (for instance) SQLite Expert Personal edition and do some SQL magic(First make a backup)
I would advice to first get some values (and one or two daily values) with the new device type, and then start working on your SQL script

**Comment by waltervl** [comment] 2023-02-01 07:36
Closing this issue. If further questions please use the forum https://www.domoticz.com/forum/

**Closed as completed by waltervl** 2023-02-01 07:36 UTC
Labels: question
