### ISSUE TITLE
problem with Enocean device

### ISSUE THREAD

**Issue by titi234** [domoticz/domoticz#4860] opened 2021-06-14 07:53 UTC
Hi,

From the release 2021.1 I have a problem with my Enocean device, with each check it creates a new device and not update the existing with the same ID but new IDX and unit member. Do you have a solution ?

Thanks

**Comment by gizmocuz** [comment] 2021-06-14 09:08
Did you try the beta version ?

**Comment by labelette91** [comment] 2021-06-15 17:41
hi,
there is a regression when adding the rssi level in commit SHA-1: d21a535841d5ef812132185e527f9505b5e18049
Enocean: First implementation of RSSI reporting in device list

For temperature sensor / rfx sensor / occupancy sensor , the RSI field value is used for the enOcean byte0 device addresses.

cdt

**Comment by labelette91** [comment] 2021-06-15 18:01
find the correction for testing
[EnOceanESP3.zip](https://github.com/domoticz/domoticz/files/6657710/EnOceanESP3.zip)

cdt

**Comment by gizmocuz** [comment] 2021-06-16 05:27
@labelette91 , I'm sorry we can not easily compare against a zip file.
In Domoticz the RSSI value has a range of 0-11 , and 12 = NA (Not used)

I can't see what you changed by looking into a zip file

**Comment by labelette91** [comment] 2021-06-16 06:34
[EnOceanESP3.cpp.txt](https://github.com/domoticz/domoticz/files/6660708/EnOceanESP3.cpp.txt)

**Comment by titi234** [comment] 2021-06-16 06:48
> Did you try the beta version ?

Yes and it's the same

**Comment by titi234** [comment] 2021-06-16 06:51
> find the correction for testing
> [EnOceanESP3.zip](https://github.com/domoticz/domoticz/files/6657710/EnOceanESP3.zip)
> 
> cdt

where do I put the cpp file ?

**Comment by gizmocuz** [comment] 2021-06-16 11:02
Posting a complete source file does not show us what has been changed.
Maybe post the relevant code change and the difference in the result

**Comment by labelette91** [comment] 2021-06-18 15:15
![image](https://user-images.githubusercontent.com/1288018/122582438-76935a80-d058-11eb-84cd-ab38c5b0874e.png)
Find text compare.

I have tested with simulation mean. Not with real hardware.
Copy the file to hardware in order to test.

cdt

**Comment by gizmocuz** [comment] 2021-06-20 08:38
Thank you for the changes, PR is merged

**Closed as completed by gizmocuz** 2021-06-20 08:38 UTC

**Comment by efdeb** [comment] 2021-06-21 13:28
Hi gizmocuz,

To avoid future regressions, it would be interresting to add comments to indicate that it is a trick to use RFXSENSOR.filler and RFXSENSOR.rssi to transmit EnOcean DeviceID/UnitID to decode_RFXSensor in mainworker.cpp.

In the same way, TEMP.battery_level and TEMP.rssi are used to transmit EnOcean device UnitID to decode_Temp in mainworker.cpp

The same trick could be used (but isn't) for RFXMETER and  TEMP_HUM ?

The root problem is that enocean devices use 4 bytes IDs + 1 byte UnitID when only 2 bytes IDs are supported in most RBUF declarations in RFXtrx.h / mainworker.cpp. Resulting issues are that different devices could be seen as a single device (see https://www.domoticz.com/forum/viewtopic.php?f=56&t=34102) or battery_level/rssi data may be ignored even if available.

RFXtrx.h seems to belong to RFXCOM SDK (version 9.31, April 6, 2021) whict I could find freely available on the net. Do you know how to find it and it's documentation ? Is it possible to change it to support 4 bytes IDs directly in domoticz source or must this change be negociated with RFXCOM development teams ?

**Comment by titi234** [comment] 2021-06-23 13:01
Hi,
if I understood, you fixed the problem. But how I can updated my domoticz to correct it ?
Thanks

**Comment by labelette91** [comment] 2021-06-23 16:52
Hi,
you have to checkout the development branch and to recompil .
cdt
