### ISSUE TITLE
zwave incorrect state in domoticz

### ISSUE THREAD

**Issue by decommentator** [domoticz/domoticz#4352] opened 2020-09-18 20:35 UTC
domoticz is not setting the correct state and not updating the state as it should be.
So there is a difference with domoticz state vs real state / openzwave state.

Bug existing since december 2018
https://domoticz.com/forum/viewtopic.php?f=6&t=25950

Sure it is ok if a state is not direct correct as long as state is updated sometimes. In the past it was possible to force correct state with script in first post. As mentioned here
https://domoticz.com/forum/viewtopic.php?f=6&t=25950#p237182

it is a incorrect state in domoticz vs real state / openzwave state

Also ropske mentioned this problem
https://domoticz.com/forum/viewtopic.php?f=24&t=33927

problem exist on rpi2 , rpi3 and rpi4 on all raspian versions since December 2018 and with all domoticz versions since December 2018 stable & beta

**Comment by gizmocuz** [comment] 2020-09-19 06:23
@decommentator , what version of Domoticz are you running ?
There have been a recent update that used a secondary update method (~a week ago)

What hardware are you using (Node), is the controller in the Life-Line ? Most times group 1, but some nodes need to have to controller in another group

It would also help if you could debug the code, compile Domoticz in debug mode (Visual Studio), there you should see a lot of debug messages, you should see (I hope) some update messages
Set some break points, add some more logging

**Comment by decommentator** [comment] 2020-09-19 07:30
Version: 2020.2 (build 12377)
Build Hash: c8ea3180c-modified
Compile Date: 2020-09-13 07:55:48
dzVents Version: 3.0.12


001 (0x01) | Controller | ZW090 Z-Stick Gen5 EU | AEON Labs | 0x005a | 0x0001


![image](https://user-images.githubusercontent.com/71527824/93661767-b8a45700-fa5a-11ea-8dc7-fb4a7122073b.png)

**Comment by gizmocuz** [comment] 2020-09-19 07:56
@decommentator , What hardware are you using (Node), the node that does not update correctly ?

**Comment by decommentator** [comment] 2020-09-19 08:07
using 

FGS223 Double Relay+ | FIBARO System | 0x1000 | 0x0203
FGWPE/F Wall Plug Gen5+ | FIBARO System | 0x1001 | 0x0602

both have problems with correct state

**Comment by gizmocuz** [comment] 2020-09-19 08:22
I do have a FGS223 and am experiencing the same issue. Only Instance 1 is being correctly updated (Also in the control panel),
Instance 2 does not report anything.
Do you say the what you see in the control panel is always correct ? As I can not reproduce this...

**Comment by decommentator** [comment] 2020-09-19 08:30
the state in openzwave cp is always correct

**Comment by decommentator** [comment] 2020-09-20 19:26
from openzwave cp:
`2020-09-20 21:21:14.537 Error, Node039, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "MultiChannel Encapsulated (instance=2): SwitchBinaryCmd_Get (Node=39): 0x01, 0x0d, 0x00, 0x13, 0x27, 0x06, 0x60, 0x0d, 0x01, 0x02, 0x25, 0x02, 0x25, 0x3a, 0x96"
2020-09-20 21:21:14.537 Always, 
2020-09-20 21:21:14.537 Always, Dumping queued log messages
2020-09-20 21:21:14.537 Always, 
2020-09-20 21:21:14.537 Always, 
2020-09-20 21:21:14.537 Always, End of queued log message dump
2020-09-20 21:21:14.537 Always, 
2020-09-20 21:22:03.183 Error, Node039, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "MultiChannel Encapsulated (instance=2): SwitchBinaryCmd_Get (Node=39): 0x01, 0x0d, 0x00, 0x13, 0x27, 0x06, 0x60, 0x0d, 0x01, 0x02, 0x25, 0x02, 0x25, 0x48, 0xe4"
2020-09-20 21:22:03.184 Always, 
2020-09-20 21:22:03.184 Always, Dumping queued log messages
2020-09-20 21:22:03.184 Always, 
2020-09-20 21:22:03.184 Always, 
2020-09-20 21:22:03.184 Always, End of queued log message dump
2020-09-20 21:22:03.184 Always,`

state in Domoticz : on
state fgs223 / 2 : off

turned switch off in Domoticz 
then the lua state checkscript turned it on
`2020-09-20 21:21:11.466 Status: User: admin initiated a switch command (1325/Buitenlamp schuurtje/Off)
2020-09-20 21:21:14.537 Status: OpenZWave: Received timeout notification from HomeID: 4034974610, NodeID: 39 (0x27)
2020-09-20 21:22:00.037 Status: LUA: Buitenlamp schuurtje is uit terwijl deze aan moet zijn
2020-09-20 21:22:00.039 Status: EventSystem: Script event triggered: /home/pi/domoticz/scripts/lua/script_time_lampen.lua
2020-09-20 21:22:03.184 Status: OpenZWave: Received timeout notification from HomeID: 4034974610, NodeID: 39 (0x27)`

**Comment by nonolk** [comment] 2020-09-21 09:23
Hello, I'm experiencing exactly the same issue.
Domoticz version: Version: 2020.2 (build 12392)
Zwave node experiencing the issue: AEON Labs ZW096 Smart Switch 6
State in domoticz: On
State in Zwave CP and physical : Off
![Screen Shot 2020-09-21 at 11 22 19](https://user-images.githubusercontent.com/26922736/93751068-c72a7400-fbfc-11ea-9ef6-8c6d5d1781b2.png)
![Screen Shot 2020-09-21 at 11 22 33](https://user-images.githubusercontent.com/26922736/93751074-c98cce00-fbfc-11ea-8257-f373ffc0e079.png)

**Comment by decommentator** [comment] 2020-10-05 17:42
can confirm, today again incorrect state in Domoticz and correct state in openzwave cp with fgs223

what can we do to debug this?

**Comment by gizmocuz** [comment] 2020-10-06 06:34
@decommentator , could you comment the line

`UpdateValue(nodeInfo, vID);`

(around line 637) in the switch case '::Notification::Type_ValueRefreshed'

This has been added lately, It might be the reason for this issue

**Comment by cndian** [comment] 2020-10-06 09:05
I have the same problem with the FGR223. I get no status update. How to resolve this?

**Comment by decommentator** [comment] 2020-10-06 15:37
> @decommentator , could you comment the line
> 
> `UpdateValue(nodeInfo, vID);`
> 
> (around line 637) in the switch case '::Notification::Type_ValueRefreshed'
> 
> This has been added lately, It might be the reason for this issue

if it is in a .py file I can test it if you tell me which one.
If it's in a source file I can't help because I can't compile. I use the beta update script to update

**Comment by gizmocuz** [comment] 2020-10-07 07:02
@decommentator , you could follow some easy steps here:

https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

**Comment by decommentator** [comment] 2020-12-14 20:32
update:
it seems this problem effects the powerstatus as well
so the correct current watt usage is in openzwave panel and domoticz isn't updating the state. Sometimes it is even in red . Manual switching it on off corrects the state

**Comment by decommentator** [comment] 2020-12-21 09:33
Latest betabuid 2020.2 (build 12741)
incorrect state domoticz
![2020-12-21 (1)_LI](https://user-images.githubusercontent.com/71527824/102761859-c7f7b100-4377-11eb-81ff-ce46c47c9cb8.jpg)
correct state openzwavecp
![2020-12-21_LI](https://user-images.githubusercontent.com/71527824/102761863-c928de00-4377-11eb-85a2-6c5d712aaedb.jpg)

**Comment by decommentator** [comment] 2020-12-21 09:36
periodic power reports not working:
![2020-12-21 (2)](https://user-images.githubusercontent.com/71527824/102762277-5b30e680-4378-11eb-82f3-e82ef5d241c2.png)
![2020-12-21 (3)](https://user-images.githubusercontent.com/71527824/102762278-5bc97d00-4378-11eb-968a-328bbd937c95.png)

**Comment by decommentator** [comment] 2020-12-21 09:38
update when using the switch (in above state) in domoticz and set it to on and switch it off; the light is turned off as expected.

**Comment by nebuohyrrah** [comment] 2020-12-23 11:21
Maybe this is related as well.
I've noticed that when the following error is received "ZW_SEND_DATA could not be delivered to Z-Wave stack", for reasons not completely clear yet (probably the zwave stick is busy with another module or a lot of traffic), the status in ozwcp is correct and domoticz assumes the command is sent and displays the wrong status.

For example: If a switch on command is triggered by dzvents in ozwcp the switch says off, but domoticz displays it as on. Physically it is off because the command was never sent. Putting in an check a few seconds later with .checkFirst() has no effect since in domoticz the switch is believed to be on. Going for multiple on and off commands makes the situation only worse because it generates more zwave traffic. Luckily it doesn't happen often.

Version: 2020.2 (build 12709)
Build Hash: 7dfcb3d5c-modified
Compile Date: 2020-11-29 11:09:03
dzVents Version: 3.0.17

**Comment by gizmocuz** [comment] 2020-12-23 13:16
When you switch something on/off or change a level, this is updated in Domoticz directly, regardless if it is send or not.
The reason for this is that for 433Mhz RF hardware (and others) there is no feedback, so we need to assume it is set correctly

**Comment by nebuohyrrah** [comment] 2020-12-23 13:53
Oké, that sounds logical. Thanks for the answer.

**Comment by decommentator** [comment] 2020-12-26 22:13
Why is it closed? Item is not solved @gizmocuz ?

Still not updated power reports after 3600

**Comment by gizmocuz** [comment] 2020-12-27 08:21
@decommentator , sorry about this... we're mixing switches and power usage here in this thread.
Could you try with the latest beta version ? There has been a change recently that allows paring of commandclass_no_operation (which I though did not do anything, but seems to report states)

**Comment by decommentator** [comment] 2020-12-27 10:38
> @decommentator , sorry about this... we're mixing switches and power usage here in this thread.
> Could you try with the latest beta version ? There has been a change recently that allows paring of commandclass_no_operation (which I though did not do anything, but seems to report states)

sure updated yesterday to
Domoticz2020.2 (build 12760)

(before reply here that it isn't solved ;) )


openzwave cp log for device 37

> 2020-12-27 06:21:57.859 Error, Node026, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "WakeUpCmd_NoMoreInformation (Node=26): 0x01, 0x09, 0x00, 0x13, 0x1a, 0x02, 0x84, 0x08, 0x25, 0x50, 0x04"
> 2020-12-27 06:21:57.866 Always,
> 2020-12-27 06:21:57.866 Always, Dumping queued log messages
> 2020-12-27 06:21:57.866 Always,
> 2020-12-27 06:21:57.866 Always,
> 2020-12-27 06:21:57.866 Always, End of queued log message dump
> 2020-12-27 06:21:57.866 Always,
> 2020-12-27 06:22:00.866 Error, Node026, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "WakeUpCmd_NoMoreInformation (Node=26): 0x01, 0x09, 0x00, 0x13, 0x1a, 0x02, 0x84, 0x08, 0x25, 0x51, 0x05"
> 2020-12-27 06:22:00.866 Always,
> 2020-12-27 06:22:00.866 Always, Dumping queued log messages
> 2020-12-27 06:22:00.866 Always,
> 2020-12-27 06:22:00.866 Always,
> 2020-12-27 06:22:00.866 Always, End of queued log message dump
> 2020-12-27 06:22:00.866 Always,
> 2020-12-27 09:05:06.535 Error, Node039, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "MultiChannel Encapsulated (instance=2): SwitchBinaryCmd_Get (Node=39): 0x01, 0x0d, 0x00, 0x13, 0x27, 0x06, 0x60, 0x0d, 0x01, 0x02, 0x25, 0x02, 0x25, 0x5d, 0xf1"
> 2020-12-27 09:05:06.536 Always,
> 2020-12-27 09:05:06.536 Always, Dumping queued log messages
> 2020-12-27 09:05:06.536 Always,
> 2020-12-27 09:05:06.536 Always,
> 2020-12-27 09:05:06.536 Always, End of queued log message dump
> 2020-12-27 09:05:06.536 Always,`
> 
> Domoticz zwave screen
> `
> 
> 037 (0x25) | Buitenverlichting heg links | FGS223 Double Relay+ | FIBARO System | 0x1000 | 0x0203 | 2020-12-27 00:29:52 | No
> -- | -- | -- | -- | -- | -- | -- | --
> 
>

**Comment by gizmocuz** [comment] 2020-12-27 11:49
Well if you search for "ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "WakeUpCmd_NoMoreInformation" you see we're not alone here...
Since all software experiencing this issue, I doubt it's a Domoticz issue...
There have been some tips, like moving the controller, including the switch in non-secure mode, setting the retry timeout higher (hardware->openzwave, select the controller (node 1), change the timeout value)

**Comment by decommentator** [comment] 2020-12-29 07:28
Domoticz:
![2020-12-29_LI](https://user-images.githubusercontent.com/71527824/103266329-a4ec8300-49af-11eb-9be4-393bec33e464.jpg)

Domoticz:
![2020-12-29 (2)_LI](https://user-images.githubusercontent.com/71527824/103266336-a61db000-49af-11eb-9e4c-753eee9fef1a.jpg)

Openzwave cp:
![2020-12-29 (1)_LI](https://user-images.githubusercontent.com/71527824/103266332-a5851980-49af-11eb-8695-7db3fb755b51.jpg)

**Comment by gizmocuz** [comment] 2020-12-29 08:22
@decommentator , you should also have a kWh device, and I believe this is being updated correctly
If Domoticz find a kWh value, it will keep updating this, and stop updating the Usage(W) device
There should also be a second Usage(W) device that is being updated
(Looking at ZWaveBase.cpp here...
`else if (pDevice->devType == ZDTYPE_SENSOR_POWER)`
)

Maybe this code needs to be checked, but looking at it:

```
		_tUsageMeter umeter;
		umeter.id1 = ID1;
		umeter.id2 = ID2;
		umeter.id3 = ID3;
		umeter.id4 = ID4;
		umeter.dunit = 2;
		umeter.fusage = pDevice->floatValue;
		sDecodeRXMessage(this, (const unsigned char *)&umeter, nullptr, BatLevel, nullptr);
```

This should give you a Watt device with deviceID = 00 00 NODEID INSTANCEID
If this is node (hex) 10 for example the ID will be 00 00 10 02 (because you highlighted Instance 2)

I recommend to use the General/kWh device, and if you want a Instant (Watt) device, take the one with the above device ID and unit=2

**Comment by decommentator** [comment] 2020-12-29 08:46
> This should give you a Watt device with deviceID = 00 00 NODEID INSTANCEID
> If this is node (hex) 10 for example the ID will be 00 00 10 02 (because you highlighted Instance 2)
> 
> I recommend to use the General/kWh device, and if you want a Instant (Watt) device, take the one with the above device ID and unit=2

Thanks for reply. It is the one with instanceID02
![2020-12-29 (3)](https://user-images.githubusercontent.com/71527824/103271468-9fe10100-49ba-11eb-9f0f-17f8c8776a5d.png)


edit: btw I use instant device to try to find the incorrect state in Domoticz so if it uses power and Domoticz state is off there is something wrong. So it is very difficult to find this when both aren't correct

**Comment by gizmocuz** [comment] 2020-12-29 11:51
I am currently testing with a FGS-223 and have no issues receiving and sending the correct switch states and usage/kWh
I made some small patches, that needs verification
But you should also have a 00001201 and a 00001202
So in the search filter type "z-wave 12" without the quotes and you should see it, and use that one
Or even better, just just the kWh meter ?

**Comment by decommentator** [comment] 2020-12-29 20:28
update 5 minutes ago  to 2020.2 (build 12774)

when using "z-wave 12" I see a lot more so I used "z-wave 112":
![2020-12-29 (4)](https://user-images.githubusercontent.com/71527824/103312234-b0c25e80-4a1c-11eb-837b-487599f7515e.png)

**Comment by decommentator** [comment] 2020-12-30 07:41
Yesterday before sleep:
Last update the time Domoticz got the update
![2020-12-29 (5)](https://user-images.githubusercontent.com/71527824/103336453-843c3000-4a78-11eb-8c2b-a405b08acfbe.png)

ok time to sleep and turn off the lights
openzwave state id02 and real status
![2020-12-29 (6)_LI](https://user-images.githubusercontent.com/71527824/103336605-03c9ff00-4a79-11eb-9e65-1b561e695c85.jpg)

Domoticz switch status:
![2020-12-29 (7)_LI](https://user-images.githubusercontent.com/71527824/103336687-383dbb00-4a79-11eb-8396-71e91822ddbc.jpg)

Domoticz power status:
![2020-12-29 (8)](https://user-images.githubusercontent.com/71527824/103336743-5a373d80-4a79-11eb-8ad4-0ca4b19dece1.png)

Only effecting FGS223 Double Relay+? Nope also

FGWPE/F Wall Plug Gen5+ | FIBARO System | 0x1001 | 0x0602
-- | -- | -- | --


openzwave status and real status:
![2020-12-29 (9)](https://user-images.githubusercontent.com/71527824/103336850-b5693000-4a79-11eb-9c90-6ddf13a46ee2.png)

Domoticz:
![2020-12-29 (10)_LI](https://user-images.githubusercontent.com/71527824/103336897-e184b100-4a79-11eb-8d79-718e248e15f3.jpg)

Zwave connections:
![chart](https://user-images.githubusercontent.com/71527824/103337105-7be4f480-4a7a-11eb-97f8-17ad3ca8bcd9.jpeg)

Edit: Tested also on a different location:
Problem also exists when using only 4 fibaro wallplugs

**Comment by gizmocuz** [comment] 2020-12-30 16:37
@decommentator , are you able to build domoticz yourself and test the 'OpenZWave' branch ?
I made some changes here and here is works perfect.... on one machine, on the other machine where i already had installed a FGS223 since years it does not work.
There is also a difference in the order of configuration parameters and information. (Firmware/App is the same)
So I might need to exclude and include the node and it could work... this i can test tomorrow

**Comment by decommentator** [comment] 2021-01-01 20:49
hi, happy new year.

Sorry, building is not possible for me

**Comment by gizmocuz** [comment] 2021-01-02 08:04
@decommentator , on what platform are you running Domoticz (and 32 or 64 bit for Arm/Linux)

**Comment by gizmocuz** [comment] 2021-01-03 09:32
Using the default beta version (without my patch), I excluded my FGS-223 (was included long long time ago, OpenZWave 1.4 ... )
After including everything works as expected. I receive both switches , both kWh sensors, I can control both relays
Before this I tried refreshing the node information/configuration, but nothing changed
I notice that the order of the configuration is different, same as on my test system as mentioned a few posts back
Did you try to exclude/include one that failed recently ?

**Comment by decommentator** [comment] 2021-01-03 20:43
all included last October. I'll try to exclude and include them all as I see the problem with .

oh wait: The test with the 4 plugs was on a clean install with only new plugs and new usb zwavestick

**Comment by gizmocuz** [comment] 2021-01-04 07:04
@decommentator , please exclude and include 1 for the test... Also with the latest beta version

**Comment by gizmocuz** [comment] 2021-01-04 07:23
(And before you do, make sure you are on the beta version)

**Comment by decommentator** [comment] 2021-01-09 16:38
updated 4/5 days ago to Domoticz2020.2 (build 12828)
excluded today 1 wallplug
included today the wallplug

no difference in total devices for the plug. The new devicenumber has same devices with same discription.

heal network after it.

result:
more troubles when the lights should be on
incorrect states for
3 wallplugs (all connected to the excluded and included plug according to neigbours diagram) incorrect state
2 FGD212 Dimmer 2+ incorrect state in domoticz 
4 FGS223 Double Relay+ incorrect state in Domoticz

and the checklightstates script is trying to correct them without luck, every minute
```
2021-01-09 17:32:00.467 Status: LUA: Tuinverlichting is uit terwijl domoticz denkt dat deze aan is
2021-01-09 17:32:00.468 Status: LUA: Buitenlamp schuurtje is uit terwijl domoticz denkt dat deze aan is
2021-01-09 17:32:00.468 Status: LUA: Buitenlamp voordeur is uit terwijl domoticz denk dat deze aan is
2021-01-09 17:32:00.468 Status: LUA: Leeslamp is uit terwijl domoticz denkt dat deze aan is
```

so total darkness today instead of light....

Updated to latest beta now
Domoticz2020.2 (build 12836)

and after some time my checklightstatus script is turning on the lights as they should be. 
So waiting for tomorow to see what will happen

**Comment by decommentator** [comment] 2021-01-10 16:41
looks stable today
except there is huge delay for motion and doorsensors to report so there is also a huge delay to switch on the light automatically

**Comment by decommentator** [comment] 2021-01-15 19:36
looks like the slowness/delay from motion and doorsensors is gone since update
Domoticz 2020.2 (build 12844)

**Comment by gizmocuz** [comment] 2021-01-16 14:57
Good to here.... except my changes where related to Power/Enery meters and the Fibaro Wallplug.
Maybe your mesh network improved somehow ?
Closing issue for now, feel free to re-open if the problem continues

**Closed as completed by gizmocuz** 2021-01-16 14:57 UTC

**Comment by decommentator** [comment] 2021-01-30 07:55
problem not solved.

**Comment by decommentator** [comment] 2021-08-03 06:08
@gizmocuz still not solved. 
![2021-08-03 (2)](https://user-images.githubusercontent.com/71527824/127966242-f854b9d8-ae00-4c48-9370-73a3db842f65.png)
![2021-08-03 (3)](https://user-images.githubusercontent.com/71527824/127966250-55c75c44-4c69-43bd-88ef-394f49f2dbe3.png)
![2021-08-03 (1)](https://user-images.githubusercontent.com/71527824/127966252-051b7a96-efe7-4211-a971-2827d597f357.png)

**Comment by decommentator** [comment] 2021-09-06 20:13
@gizmocuz please open this issue as this strange behaviour is still there. And always showing correct state in openzwave cp while wrong state in domoticz or red states.

**Comment by Patricen1** [comment] 2021-09-09 04:11
Hello all,

This issue is not only specific to Fibaro fgs223. I'm also experiencing the same bug (intermittently) with Popp thermostatic radiator valves, neo coolcam plugs and Qubino flush shutter controllers, all of them operating on z-wave network.
There is a thread related to this issue there : [https://www.domoticz.com/forum/viewtopic.php?f=6&t=36823](url)

**Comment by Patricen1** [comment] 2021-11-19 10:44
I'm running last stable version (2021.1), has there been any update regarding this issue?

**Comment by decommentator** [comment] 2021-12-05 21:43
> I'm running last stable version (2021.1), has there been any update regarding this issue?

no...
the topic is stil closed

**Comment by gizmocuz** [comment] 2021-12-06 00:43
No, please switch to the zwave2mqtt implantation

**Comment by Patricen1** [comment] 2021-12-06 07:00
Ok thanks @gizmocuz , any recommended installation process / will zwave2mqtt be embedded within the next stable version?

**Comment by gizmocuz** [comment] 2021-12-13 16:06
Yep

**Comment by chdamn** [comment] 2021-12-15 20:44
> Yep

Do you have an idea when the next release will be?

**Comment by gizmocuz** [comment] 2021-12-17 10:29
Hope before end of this year.... In the mean time, just test the beta version...
Maybe easiest to do this with docker

**Comment by chdamn** [comment] 2021-12-19 20:19
Thanks, i tried the beta. I cannot select the zwave2mgtt as an option in the device type. Am i missing something?

**Comment by gizmocuz** [comment] 2021-12-20 01:08
See https://www.domoticz.com/wiki/MQTT

**Comment by stephanvdplas** [comment] 2022-01-19 21:00
I can still reproduce this issue. A Zwave device (Fibaro Dimmer 2) that is pressed locally does not update status to Domoticz. In Domoticz, the dimmer can be controlled perfectly, it is just that the status is not set correctly in Domoticz (though the Zwave CP show the correct status).

**Comment by decommentator** [comment] 2022-01-19 21:08
> I can still reproduce this issue. A Zwave device (Fibaro Dimmer 2) that is pressed locally does not update status to Domoticz. In Domoticz, the dimmer can be controlled perfectly, it is just that the status is not set correctly in Domoticz (though the Zwave CP show the correct status).

sure, because:

> No, please switch to the zwave2mqtt implantation
