### ISSUE TITLE
Dimmer slider is missing in Floorplan after icon change to Fan etc

### ISSUE THREAD

**Issue by gryzli133** [domoticz/domoticz#3555] opened 2019-08-01 09:56 UTC
I have fans that have speed control. Now I use only standard dimmer icons, while the FAN icon are not working well. The fan displays the %, but there is no possibility to change speed from Floorplan. I used to control my house only from floorplans, because I have hundred of switches in my house (every light, blind etc is controlled from Domoticz). Using the floorplan I do not need to scroll all the time. I used to control the fans from standard dimmer icon, but in some rooms there is hard to know which is light and which is fan or blind. I have attached screenshots using dimmer icon and fan icon. As you can see while using FAN icon there is no slider for percentage control.

PS: There is an post on the forum including screenshots: http://www.domoticz.com/forum/viewtopic.php?f=8&t=28871&p=220469#p220469

**Comment by mikewoudenberg** [comment] 2019-08-02 08:21
I have a rrelated issue (I think). I have door/window sensors. Some of them I gave a custom icon to make them stand out better on my floorplan. The sensors with custom icons always show as open (while they are shown correctly in the switches tab of domoticz). 

I traced this issue down to https://github.com/domoticz/domoticz/blob/development/www/js/domoticzdevices.js#L824 where the type of the device is overriden by the name of the custom image, causing it to default to a switch type instead of a door type.

**Comment by dnpwwo** [comment] 2019-08-04 13:53
The Floorplan does not use the name of the custom image because they have numbers.

It uses the initial image to work out what kind of device it actually is from a behavior perspective and creates one of those. The logic is different from the other pages but the code is far more generic and compact.

The problem is that the Fan image is not a custom icon its a standard icon that has standard handling which does not include a slider. If you loaded an actual custom fan icon the floorplan would assume it was still a dimmer and render it correctly with a slider.

Domoticz actually sends a data field that is supposed tell the front end if the device has a dimmer but it is unreliable so the floorplan ignores it.  (see line 371)

**Comment by gizmocuz** [comment] 2019-08-11 11:21
@dnpwwo , can you provide some examples where Domoticz advertises a wrong dimmer field ?
Should not happen of course, and i find this strange as the normal gui (and for example mobile application) work correctly

**Comment by gizmocuz** [comment] 2019-10-25 13:02
Closing this issue because no feedback has been received for months

**Closed as completed by gizmocuz** 2019-10-25 13:02 UTC

**Comment by xztraz** [comment] 2020-04-03 08:29
I have the same issue. no dimmer slider on lights with custom icons.

**Comment by xztraz** [comment] 2020-10-20 13:20
This is still a problem.
No slider on dimmers when using custom icons
![image](https://user-images.githubusercontent.com/25690871/96591674-cbbf7680-12e7-11eb-88e9-8584000d2fc4.png)
