### ISSUE TITLE
MQTT Auto discovery Thermostat modes & preset_modes confuse

### ISSUE THREAD

**Issue by MarkKoshelev** [domoticz/domoticz#5521] opened 2023-01-06 10:13 UTC
domoticz ver 14893 (latest)
z2m 1.29.0) commit: [dddce571] (latest)
Termostat [TuYa] [X5H-GB-B], but the issue is not only for this model
domoticz confuses modes and preset_modes 

AD topic from z2m is normal (in the attacment)
but domoticz doesnt create switch for "modes" property
Also see changes of preset_modes switch in domoticz if I click on mode switch in the thermostat

[ad_thermostat.txt](https://github.com/domoticz/domoticz/files/10359240/ad_thermostat.txt)
[thermostat.txt](https://github.com/domoticz/domoticz/files/10359276/thermostat.txt)

Probably the topics is not the same in AD and status message

**Comment by odelma** [comment] 2023-01-09 06:24
Hi, I can confirm this with Moes BHT-002 (Tuya) zigbee thermostat (I am at least assuming the problem I am facing is very close even if it manifests in a bit different way in my case), I have described it  in the Domoticz Slack channel as well: https://domoticz.slack.com/archives/C02DZ8C0ACQ/p1672612634700339

In short, for the operating mode (preset) switch, for each incoming message it first changes the status in Domoticz to "program" and then immediately (at the same second) to "hold" - which is the correct status in my case. The incoming message in mqtt is:

```
{
  "child_lock": "UNLOCK",
  "current_heating_setpoint": 18,
  "deadzone_temperature": 1,
  "heat": "OFF",
  "linkquality": 87,
  "local_temperature": 21,
  "local_temperature_calibration": -3,
  "max_temperature_limit": 25,
  "min_temperature_limit": 5,
  "preset": "hold",
  "preset_mode": "hold",
  "running_state": "idle",
  "sensor": "IN",
  "system_mode": "heat"
}
```

Config topic:

```
{
  "action_template": "{% set values = {None:None,'idle':'off','heat':'heating','cool':'cooling','fan_only':'fan'} %}{{ values[value_json.running_state] }}",
  "action_topic": "zigbee2mqtt/Termostaatti makuuhuone",
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state"
    }
  ],
  "current_temperature_template": "{{ value_json.local_temperature }}",
  "current_temperature_topic": "zigbee2mqtt/Termostaatti makuuhuone",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x50325ffffe401d5d"
    ],
    "manufacturer": "Moes",
    "model": "Moes BHT series Thermostat (BHT-002-GCLZB)",
    "name": "Termostaatti makuuhuone"
  },
  "max_temp": "35",
  "min_temp": "5",
  "mode_command_topic": "zigbee2mqtt/Termostaatti makuuhuone/set/system_mode",
  "mode_state_template": "{{ value_json.system_mode }}",
  "mode_state_topic": "zigbee2mqtt/Termostaatti makuuhuone",
  "modes": [
    "off",
    "heat"
  ],
  "name": "Termostaatti makuuhuone",
  "preset_mode_command_topic": "zigbee2mqtt/Termostaatti makuuhuone/set/preset",
  "preset_mode_state_topic": "zigbee2mqtt/Termostaatti makuuhuone",
  "preset_mode_value_template": "{{ value_json.preset }}",
  "preset_modes": [
    "hold",
    "program"
  ],
  "temp_step": 1,
  "temperature_command_topic": "zigbee2mqtt/Termostaatti makuuhuone/set/current_heating_setpoint",
  "temperature_state_template": "{{ value_json.current_heating_setpoint }}",
  "temperature_state_topic": "zigbee2mqtt/Termostaatti makuuhuone",
  "temperature_unit": "C",
  "unique_id": "0x50325ffffe401d5d_climate_zigbee2mqtt"
}
```

I tested this in Home Assistant and it works normally so I assume it follows the standard protocol and should integrate to Domoticz. Because of this back and forth switching the short log for these switches is huge:
![image](https://user-images.githubusercontent.com/10372952/211250884-84c2ae51-5943-447d-b758-886ee9abcca5.png)

In my case also the icons for the auto-created switches do not seem to work. It created the "bulb" switch and even if I try to change it via settings it does not work (for all other zigbee switches it does work). For selectors it should by default be something else than the bulb in any case?

![image](https://user-images.githubusercontent.com/10372952/211250711-d72264f3-0e96-4b93-985c-2d1afc99587a.png)
 
Finally, I noticed one thing missing (for this thermostat device at least) that I would like to see in Domoticz: That is the running_state (idle or heating) status that would tell if the thermostat is heating or not.

**Comment by odelma** [comment] 2023-01-09 23:32
One additional "malfunction" with regards to thermostat (can be of course something with the device itself), from time to time I see in domoticz error log:
`Error: MQTT autodiscovery: Climate device unhandled temperature_state_template (0x50325ffffe401d5d_climate_zigbee2mqtt)`
...in the logs, but even after recording the mqtt messages and comparing them to previous ones (which do not cause error), I cannot see any difference. In HA I cannot see anything similar in logs.

**Comment by gizmocuz** [comment] 2023-01-11 07:34
Maybe you two could debug the code in MQTTAutoDiscovery.cpp ?
action_template/action_topic are not implemented

I don't understand the reason of "Because of this back and forth switching the short log for these switches is huge"

**Comment by odelma** [comment] 2023-01-11 09:01
Yes, sorry for mixing things up a bit. I should have mentioned about the missing action_template/topic on a different post in order not to create confusion with this preset_mode issue.

> I don't understand the reason of "Because of this back and forth switching the short log for these switches is huge"

This I thought was worth mentioning if it would shed some light into the issue. What I meant by the above, is that for my setup (with Moes BHT-002), Domoticz creates a selector switch for "Preset Mode" with two option, hold and program. So far so good, if we compare this to what we see in config topic:

```
  "name": "Termostaatti makuuhuone",
  "preset_mode_command_topic": "zigbee2mqtt/Termostaatti makuuhuone/set/preset",
  "preset_mode_state_topic": "zigbee2mqtt/Termostaatti makuuhuone",
  "preset_mode_value_template": "{{ value_json.preset }}",
  "preset_modes": [
    "hold",
    "program"
  ]
```

However, the thermostat is (in my case) set to "hold", and with each incoming mqtt message that updates this thermostat, Domoticz switches the Preset Mode to "program" and immediately back to "hold". Because of this, I have now over 24 000 entries in the short log of the Preset Mode selector switch. Even when I have not changed the Preset Mode setting of the thermostat at all.

If I understand correct, @MarkKoshelev  is seeing something quite similar. "Mode State" switch (heat, off) is not created (for me neither) and:

> ...I see changes of preset_modes switch in domoticz if I click on mode switch in the thermostat

In fact, if you look at the screenshot from my earlier message, my "Preset Mode" switch is showing as values "off" / "heat" which what the missing "Mode State" switch should show. This relates to what I mentioned:

> In my case also the icons for the auto-created switches do not seem to work. 

...as (probably in Slack message) I also described the problem that if I edit the switch, the levels change briefly to "off" / "heat" for the "Preset Mode" switch, they do change back to "hold" / "program" soon though.

If I now look the the short log, I see "hold" and "program" (as in compare to previous short log screenshot):
![image](https://user-images.githubusercontent.com/10372952/211762385-54fc8be1-fa81-44f2-822e-ab28941cf1f6.png)

Hope this explains it a bit more.

**Comment by MarkKoshelev** [comment] 2023-01-11 09:44
Hi,

Correct. I see the same

"Preset Mode" switch is showing as values "off" / "heat"

But the first is that "off" / "heat" doesn’t exist after discovery

Also I see some strange with “Child lock” property. This problem is not so important.

I may try to debug but this will not be so fast(( 

I may connect z2m gateway to external MQTT broker. If possible the maintainer of AD discovery feature may debug this issue.

**Comment by odelma** [comment] 2023-01-15 08:19
> Maybe you two could debug the code in MQTTAutoDiscovery.cpp ? action_template/action_topic are not implemented

As for this debugging - I'm afraid as I don't have possibility to compile locally it is not possible? I tried to go through the code for thermostats in the file in question but did not find anything obvious. Could someone debug with the help of the mqtt messages we've provided (and can of course provide more if needed)?

**Comment by gizmocuz** [comment] 2023-01-15 14:32
Okey, I made some changes in beta 14961, could you try this version?
I changed the Unit for presets to 2, this way we can differentiate between the modes (and possible more modes in the feature)

@odelma , what do you mean with 'compile locally it is not possible?' , did you try and it failed? Did you try the build steps from our wiki?
You can also build with Visual Studio under Windows

**Comment by odelma** [comment] 2023-01-15 15:32
Thank you very much @gizmocuz - so far so good 👍  I now get also the status device ("off" / "heat") created along with the hold mode. So I guess this explains the earlier behavior when in same message came info that status was "heat" (Level 10) and hold mode was "hold" (Level 0) and when only the hold mode switch was created it picked level 0 from status and level 10 from hold mode to the same switch.

Now behavior is as expected, hold mode keeps its status and is not filling up the log with continuous changes.
![image](https://user-images.githubusercontent.com/10372952/212550162-0e6ca740-3d7c-480f-9b8c-a8b8d080d896.png)

What is observed is that both devices received same name (e.g. "Termostaatti makuuhuone" - bedroom thermostat, I renamed them to distinct them from one another) - should the names be different by default? Also, the default icon is the light bulb. If I go to setting I see the "on/off" icon:
![image](https://user-images.githubusercontent.com/10372952/212550274-58153335-9121-4a13-9d02-6b9f1a8a717f.png)

but still UI shows the bulb. Now I can change it to something else though (which did not work earlier). Just wondering should it have the on/off icon in UI visible by default.

**Comment by odelma** [comment] 2023-01-15 15:34
> @odelma , what do you mean with 'compile locally it is not possible?' , did you try and it failed? Did you try the build steps from our wiki? You can also build with Visual Studio under Windows

I meant just that I don't have a suitable environment where I could compile and test at the moment. I guess I could create it though, just need to take some time to go through the instructions...😊

**Comment by gizmocuz** [comment] 2023-01-15 15:48
No the names are the same, it is one device with multiple modes. (One config object)

**Comment by gizmocuz** [comment] 2023-01-15 15:49
Great it's working, thanks for the feedback! Closing issue!

**Closed as completed by gizmocuz** 2023-01-15 15:49 UTC

**Comment by odelma** [comment] 2023-01-15 22:11
Sure @gizmocuz, it is easy to rename them in any case. Just thought it might not be good to have two switches with exact same name, potentially confusing blockly etc. where you operate with switch name.

Would it be easy to add the running_state (this gives info on whether device is actually heating or just idle) as a switch as well?

Thank you for all the efforts with Domoticz - a happy user since 2015 😃
