### ISSUE TITLE
[issue] Master/slave setup with thermostat device

### ISSUE THREAD

**Issue by bdegroot123** [domoticz/domoticz#805] opened 2016-08-20 10:24 UTC
https://www.domoticz.com/forum/viewtopic.php?f=6&t=10030&p=70726#p70726

Hardware: Raspberry Pi 1 model B (master and slave setup, both raspberry), with RFXcom transeiver
OS: Domoticz image SD card, with latest beta software (but problem exists in earlier versions as well
Domoticz branch: Beta
Bug/problem or a question: Bug /problem

Problem: When my smartwares thermostat device is connected to the slave domoticz instance, and i want to manage it thru my master domoticz instance. The values are not set at all.
If I set the setpoint directly from my slave domoticz instance, everything works well, and also the status is correctly updated on the master domoticz instance.

The same issue accurs with a nefit thermostat device. So it is likely that the problem exists when using a themostats in combination with a domoticz master/slave construction.

**Comment by bdegroot123** [comment] 2016-08-20 10:25
## Feedback from gizmocus:

I think you could be right here...

i think we have to look into the function

MainWorker::ProcessRXMessage

and in

MainWorker::PerformRealActionFromDomoticzClient

it should call 

MainWorker::SetSetPoint(const std::string &idx, const float TempValue)

**Comment by michsv7** [comment] 2016-11-05 07:22
The issue seems to be as feedback from gizmocus in MainWorker::PerformRealActionFromDomoticzClient.
At line 1710: Unit = 0; could be changed to Unit = pMeter-dunit;

When Unit is hard coded to 0, the "original hardware" ID lookup in the SQL query below in the same function fails.  
This results in that the client cannot map the thermostat change correct. In the client you will get a new thermostat with same ID but unknown hardware. (ID=0)
.
else if (devType == pTypeThermostat)
    {
        const _tThermostat _pMeter = reinterpret_cast<const _tThermostat_>(pResponse);
        sprintf(szTmp, "%X%02X%02X%02X", pMeter->id1, pMeter->id2, pMeter->id3, pMeter->id4);
        ID = szTmp;
        Unit = pMeter->dunit;
    }

// find our original hardware
        // if it is not a domoticz type, perform the actual command

```
    result = m_sql.safe_query(
        "SELECT HardwareID,ID,Name,StrParam1,StrParam2,nValue,sValue FROM DeviceStatus WHERE (DeviceID='%q' AND Unit=%d AND Type=%d AND SubType=%d)",
        ID.c_str(), Unit, devType, subType);
```

**Comment by bdegroot123** [comment] 2016-11-11 11:50
Hi,
I tried the 3.5837 version with this patch.

Still the thermostat is not updating correctly on the slave device.

**Comment by michsv7** [comment] 2016-11-11 19:49
Hi,

The issue caused domoticz to adderad new devices with same id but unknow hardware. 
After the fix, I hade to delete those devices in Setup/Devices to get it to work.

**Comment by bdegroot123** [comment] 2016-11-12 11:31
ok. thx.
But still no luck.
Deleted devices on master and slave en setup al devices again.
Still not working

**Comment by michsv7** [comment] 2016-11-12 18:59
Strange, it worked for me after deleting the duplicated devices caused by the issue.
Nog I can set setpoint from master and also use timers on master instead of domoticz client that has the z-wave thermostats attached. Using popp (compatible with lc-13)

Perhaps a typo but the code change was merged into 3.5877 and not 3.5837.

Check with a dummy setpoint on the client and share it with the master, if you are able to change setpoint value from master on the dummy device then your smartwares uses some other code than default setpoint devices.

**Comment by bdegroot123** [comment] 2016-11-12 19:51
Indeed version  3.5877 on both master and slave.

In the log on the master see this, when i set a temp on the slave:
`2016-11-12 20:45:17.259 (DomoticzFromMaster) Radiator 1 (Unknown)`

And then a new device is made on the master:
`43  Unknown?    2461049 4   Unknown Radiator 1  Smartwares  5.5 -   -   Add DeviceRename Device     2016-11-12 20:47:28`

when i delete this device, it still does not work, and the unknown device is made again.

**Comment by michsv7** [comment] 2016-11-19 15:59
Ah, Radiator1 uses different code than Thermostat1 that I use for my radiators setpoint. 
Similar issue, but tricky to debug without a smartware. Radiator1 is not hard coded as Thermostat1 was so need more understanding of its ids.

**Comment by bdegroot123** [comment] 2016-11-19 16:29
Thanks for your anwser,
Please let me know if i can help debugging

**Closed as completed** 2017-02-04 14:03 UTC

**Comment by bdegroot123** [comment] 2017-02-04 17:43
no solution for Radiator1?

**Comment by gizmocuz** [comment] 2017-02-05 08:24
No unfortunately not yet... the whole master/slave has to be reprogrammed soon, but after a new release

**Comment by cornelissensolutions** [comment] 2019-11-13 08:57
Any update on this issue? 
Can we implement a workaround for now?
