### ISSUE TITLE
Support of Xiaomi Aqara wireless relay LLKZMK11LM (lumi.relay.c2acn01)

### ISSUE THREAD

**Issue by nighthawkii** [domoticz/domoticz#4029] opened 2020-03-30 15:31 UTC
Hello,

Would it be possible to add the support of the Xiaomi Aqara wireless relay LLKZMK11LM (lumi.relay.c2acn01) ?

In fact it is the same usage than the Aqara Double Wired Switch QBKG12LM (lumi.ctrl_ln2.aq1).

So the idea would be to modify XiaomiGateway.cpp, line 1088
to add "lumi.relay.c2acn01" in the conditions:

`else if (model == "ctrl_neutral2" || model == "ctrl_ln2" || model == "ctrl_ln2.aq1") {`

becomes

`else if (model == "ctrl_neutral2" || model == "ctrl_ln2" || model == "ctrl_ln2.aq1" || model == "relay.c2acn01" ) {`

Thanks in advance,

**Comment by kovainfo** [comment] 2020-03-31 20:54
the relay does not send information about its model. therefore, it is not possible to determine from which device the message is coming. You should write about this problem to the Chinese gateway developers.

**Comment by nighthawkii** [comment] 2020-03-31 21:32
Hi,

Thanks for your answer, now I understand why it is not supported by Domoticz... the solution was too simple to be not implemented...
So the only solution seems to stay with zigbee2mqtt.

Have a nice day,

**Comment by Huupke** [comment] 2020-04-04 09:52
Duplicate of #3769 and #3577

Agree with @kovainfo to file the issue at Xiaomi. The more requests they get the faster they will implement it.

**Comment by Huupke** [comment] 2021-05-25 17:20
Solved by #4839, propose to close

**Closed as completed** 2021-06-09 06:15 UTC
Labels: PendingFeedback
