### ISSUE TITLE
Selector switch protection is broken

### ISSUE THREAD

**Issue by balintkozma** [domoticz/domoticz#2488] opened 2018-06-13 10:19 UTC
Using the latest beta, enabling protection for a selector switch results in WRONG CODE error message, when clicking on one of the level buttons. It might be the side effect of recent selector switch modifications.

**Comment by gizmocuz** [comment] 2018-06-14 04:46
@balintkozma , did this work before ? The problem is in the domoticz.js file where the protection level is not handled correctly.
I will have a look, if it's a easy fix i report back shortly

**Comment by gizmocuz** [comment] 2018-06-14 04:46
I Don't think this every worked, as the device variable "isProtected" is undefined
Nope that's not it... internally this flag is correctly set, but it is incorrectly used in the sendswitch command

**Comment by gizmocuz** [comment] 2018-06-14 05:02
Fixed in upcoming beta version
https://github.com/domoticz/domoticz/commit/fbadd64cb904e0010e32535f93c83a48ae0a41cc

**Closed as completed by gizmocuz** 2018-06-14 05:02 UTC
