### ISSUE TITLE
Plugin heartbeat default to 1s and Domoticz.Heartbeat does not work

### ISSUE THREAD

**Issue by leopoldwang** [domoticz/domoticz#4727] opened 2021-03-13 13:00 UTC
From the log below, you can see that onHeartBeat call for each plugin happens every second now instead of 10s default one.

2021-03-13 12:57:21.664 Python Plugin System: (SunMoonPosition) Calling message handler 'onHeartbeat'.
2021-03-13 12:57:21.664 Python Plugin System: (SunMoonPosition) onHeartbeat
2021-03-13 12:57:21.664 Python Plugin System: (SunMoonPosition) onHeartbeat called, run again in 291 heartbeats.
2021-03-13 12:57:22.616 Python Plugin System: (SunMoonPosition) Pushing 'onHeartbeatCallback' on to queue
2021-03-13 12:57:22.666 (SunMoonPosition) Processing 'onHeartbeatCallback' message
2021-03-13 12:57:22.666 Python Plugin System: (SunMoonPosition) Calling message handler 'onHeartbeat'.
2021-03-13 12:57:22.666 Python Plugin System: (SunMoonPosition) onHeartbeat
2021-03-13 12:57:22.667 Python Plugin System: (SunMoonPosition) onHeartbeat called, run again in 290 heartbeats.
2021-03-13 12:57:23.619 Python Plugin System: (SunMoonPosition) Pushing 'onHeartbeatCallback' on to queue
2021-03-13 12:57:23.669 (SunMoonPosition) Processing 'onHeartbeatCallback' message
2021-03-13 12:57:23.669 Python Plugin System: (SunMoonPosition) Calling message handler 'onHeartbeat'.
2021-03-13 12:57:23.669 Python Plugin System: (SunMoonPosition) onHeartbeat
2021-03-13 12:57:23.669 Python Plugin System: (SunMoonPosition) onHeartbeat called, run again in 289 heartbeats.
2021-03-13 12:57:24.621 Python Plugin System: (SunMoonPosition) Pushing 'onHeartbeatCallback' on to queue
2021-03-13 12:57:24.671 (SunMoonPosition) Processing 'onHeartbeatCallback' message
2021-03-13 12:57:24.671 Python Plugin System: (SunMoonPosition) Calling message handler 'onHeartbeat'.
2021-03-13 12:57:24.671 Python Plugin System: (SunMoonPosition) onHeartbeat
2021-03-13 12:57:24.671 Python Plugin System: (SunMoonPosition) onHeartbeat called, run again in 288 heartbeats.
2021-03-13 12:57:25.623 Python Plugin System: (SunMoonPosition) Pushing 'onHeartbeatCallback' on to queue
2021-03-13 12:57:25.673 (SunMoonPosition) Processing 'onHeartbeatCallback' message
2021-03-13 12:57:25.673 Python Plugin System: (SunMoonPosition) Calling message handler 'onHeartbeat'.
2021-03-13 12:57:25.673 Python Plugin System: (SunMoonPosition) onHeartbeat
2021-03-13 12:57:25.673 Python Plugin System: (SunMoonPosition) onHeartbeat called, run again in 287 heartbeats.
2021-03-13 12:57:26.632 Python Plugin System: (SunMoonPosition) Pushing 'onHeartbeatCallback' on to queue
2021-03-13 12:57:26.683 (SunMoonPosition) Processing 'onHeartbeatCallback' message

**Comment by rwaaren** [comment] 2021-03-14 02:21
@dnpwwo Could this be related to the recent commits for the Python Plugin systems?

This is also messing up the rest of the eventsystem because devices are updated very frequent and every update causes a visit to Blockly, Lua and dzVents.

Configured poll intervals are not respected.

**Comment by gizmocuz** [comment] 2021-03-14 12:15
Yes, I think it is caused by the timeout of IsStopRequested, that was 500ms, and not 50

void CPlugin::Do_Work()
	{
		Log(LOG_STATUS, "(%s) Entering work loop.", m_Name.c_str());
		m_LastHeartbeat = mytime(nullptr);
		int scounter = m_iPollInterval * 2;
		while (!IsStopRequested(50) || !m_bIsStopped)
		{


Also all functions/code in Do_Work is now called 10 times more

**Comment by dnpwwo** [comment] 2021-03-14 23:53
Yeah, that will be the root cause.

I'll fix it shortly.

**Comment by rwaaren** [comment] 2021-03-15 04:57
👍Thx!

**Comment by gizmocuz** [comment] 2021-03-15 15:53
A patch has been silently made by @dnpwwo and I updates the Arm/x64 beta's
If all is working fine, please close this issue

**Closed as completed** 2021-03-15 16:03 UTC

**Comment by gizmocuz** [comment] 2021-03-15 16:18
Thanks for the feedback, also updated the docker images

**Comment by pipiche38** [comment] 2021-03-15 17:39
I do confirm it works better ;-) thanks
