### ISSUE TITLE
Last beta crashes using Raspbian stretch

### ISSUE THREAD

**Issue by Patricen1** [domoticz/domoticz#3882] opened 2020-02-01 21:56 UTC
After update, Domoticz status shows :
● domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh; generated; vendor preset: enabled)
   Active: active (exited) since Sat 2020-02-01 22:44:49 CET; 10min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1433 ExecStop=/etc/init.d/domoticz.sh stop (code=exited, status=0/SUCCESS)
  Process: 1443 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/domoticz.service

févr. 01 22:44:49 domoticz systemd[1]: Starting LSB: Home Automation System...
févr. 01 22:44:49 domoticz domoticz.sh[1443]: /home/pi/domoticz/domoticz: /lib/arm-linux-gnueabihf/libm.so.6: versio
févr. 01 22:44:49 domoticz domoticz.sh[1443]: /home/pi/domoticz/domoticz: /lib/arm-linux-gnueabihf/libc.so.6: versio
févr. 01 22:44:49 domoticz systemd[1]: Started LSB: Home Automation System.

**Comment by xztraz** [comment] 2020-02-01 22:07
Linux 4.1.18-v7+ armv7l GNU/Linux

`sudo service domoticz status
● domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh)
   Active: active (exited) since Sat 2020-02-01 23:04:56 CET; 10s ago
  Process: 627 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)

Feb 01 23:04:56 raspberrypi systemd[1]: Starting LSB: Home Automation System...
Feb 01 23:04:56 raspberrypi domoticz.sh[627]: /home/pi/domoticz/domoticz: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Feb 01 23:04:56 raspberrypi systemd[1]: Started LSB: Home Automation System.
`

**Comment by xztraz** [comment] 2020-02-01 22:09
Forum thread. latest beta crashes for many people. seem to be some fix going back a version then upgrading?

https://www.domoticz.com/forum/viewtopic.php?f=6&t=31157

edit: upgrading os to buster seem to work but that was a interesting evening...

**Comment by rwaaren** [comment] 2020-02-01 23:55
Duplicate of #3880 
Also [forum post](https://www.domoticz.com/forum/viewtopic.php?f=6&t=31157&sid=ff791dc7d9245319ac467785ccb75dcf)

**Closed as completed by rwaaren** 2020-02-01 23:55 UTC
