### ISSUE TITLE
Domoticz V4.10408 fail at start on synology arch-x86

### ISSUE THREAD

**Issue by Jumbotroll** [domoticz/domoticz#3013] opened 2019-02-03 15:58 UTC
Domoticz V4.10406 ok on synology, but Domoticz V4.10408 fail at start.

2019-02-03 16:33:20.950  Status: Domoticz V4.10408 (c)2012-2019 GizMoCuz
2019-02-03 16:33:20.950  Status: Build Hash: 48b5ccc-modified, Date: 2019-02-03 14:10:22
2019-02-03 16:33:20.951  Status: Startup Path: /volume1/@appstore/domoticz/bin/
2019-02-03 16:33:20.952  Error: Error opening SQLite3 database: unable to open database file
terminate called without an active exception
2019-02-03 16:33:20.952  Error: Domoticz(pid:10486, tid:10486('domoticz')) received fatal signal 6 (Aborted)
2019-02-03 16:33:20.952  Error: siginfo address=0x400000028f6, address=0x7f449f5f7907
2019-02-03 16:33:20.956  Error: Failed to start gdb, will use backtrace() for printing stack frame

2019-02-03 16:33:20.959  Error: #0  ./domoticz() [0x6874a0]
2019-02-03 16:33:20.959  Error: #1  ./domoticz : signal_handler(int, siginfo_t*, void*) + 0x295 [0x688205]
2019-02-03 16:33:20.959  Error: #2  /lib/libpthread.so.0 :  + 0x101c0 [0x7f449fe821c0]
2019-02-03 16:33:20.959  Error: #3  /lib/libc.so.6 : gsignal + 0x37 [0x7f449f5f7907]
2019-02-03 16:33:20.959  Error: #4  /lib/libc.so.6 : abort + 0x16a [0x7f449f5f8cda]
2019-02-03 16:33:20.959  Error: #5  ./domoticz : __gnu_cxx::__verbose_terminate_handler() + 0xbf [0xba5a87]
2019-02-03 16:33:20.959  Error: #6  ./domoticz : __cxxabiv1::__terminate(void (*)()) + 0x3 [0xb70b14]
2019-02-03 16:33:20.959  Error: #7  ./domoticz : __cxxabiv1::__unexpected(void (*)()) + 0 [0xb70b4a]
2019-02-03 16:33:20.959  Error: #8  ./domoticz : main + 0x88d [0x5ad28d]
2019-02-03 16:33:20.960  Error: #9  /lib/libc.so.6 : __libc_start_main + 0xf0 [0x7f449f5e4030]
2019-02-03 16:33:20.960  Error: #10 ./domoticz() [0x5db8af]

**Comment by sweetpants** [comment] 2019-02-03 16:06
Duplicate of https://github.com/domoticz/domoticz/issues/3012

**Closed as completed** 2019-02-03 16:09 UTC
