### ISSUE TITLE
Notifications not working anymore

### ISSUE THREAD

**Issue by githubos1** [domoticz/domoticz#4941] opened 2021-09-24 14:18 UTC
Hi,
Domoticz on latest BETA 2021.1(13502) 
on RASPI-2 w/Zigbee Dongle and Zigbee2MQTT Plugin
The plugin recognizes and paires all ZB devices successfully.

Since I moved from Stable to beta Version, somehow NOTIFICATIONS from ZigBee (ZB) devices do not work anymore.
All ZB devices are working properly (Sensors Switches and Repeaters) in "both" directions - sensing and switching - but neither Notifications (I'm using E-Mail and telegram) do work - For NON-Zigbee devices  (Wifi) everything works well (incl notifications)

Any idea what could cause that ?

**Comment by waltervl** [comment] 2021-09-25 09:24
So it looks to be Zigbee2MQTT python plugin related if other python plugin managed devices are still sending notifications.
Perhaps check the Zigbee2MQTT plugin repository. It could be that the new DomoticzEx plugin framework is the root cause but it depends on the implementation within the Zigbee2MQTT plugin. Let the Plugin maintainer and the plugin Framework maintaner find this out.

**Comment by odelma** [comment] 2021-09-26 15:45
Could be same as with on/off (etc.) actions: https://github.com/domoticz/domoticz/issues/4931

**Comment by dnpwwo** [comment] 2021-09-27 01:33
Pushed another fix today.  Notifications were not triggering for switches (were for other devices) in the extended framework.

**Comment by odelma** [comment] 2021-09-27 11:24
Notifications seem to be working but unfortunately the switch actions do not.

**Comment by dnpwwo** [comment] 2021-09-29 05:52
Actions is covered on a different thread.

Can this be closed now that notifications seem okay?

**Comment by gizmocuz** [comment] 2021-10-03 13:37
Closing topic.

**Closed as completed by gizmocuz** 2021-10-03 13:37 UTC
