### ISSUE TITLE
dzVents avg() returns 0 when values are constant

### ISSUE THREAD

**Issue by mc02** [domoticz/domoticz#3165] opened 2019-04-28 17:26 UTC
Hi

i use a dzVents Script to measure the Average Lux outside, sometimes when the Lux is constant for 15min (my History Data Timeout is 15min) the avg() function returns 0

what iam doing wrong here?

here the script

```
return {
	on = {
		devices = {
			347
		},
		timer = {
		    'between 7:35 and before sunset every 5 minutes', 
		},
	},
	data = {
          pastLux = { history = true, maxMinutes = 15 }
    },
	execute = function(domoticz, device)

        if (device.isTimer) then
            local average = domoticz.data.pastLux.avg()
            domoticz.log('average lux ' .. average, domoticz.LOG_INFO)
        else
		    -- add new data
            domoticz.data.pastLux.add(device.lux)
        end
}
```
Log Output:
2019-04-28 19:05:00.300 Status: dzVents: Info: average lux 16248.5
2019-04-28 19:10:00.303 Status: dzVents: Info: average lux 7143
**2019-04-28 19:15:00.491 Status: dzVents: Info: average lux 0**
2019-04-28 19:20:00.475 Status: dzVents: Info: average lux 34422

Output of the RAW Table Data of this Sensor for that Timeperiod
2019-04-28 18:40:00	33918
2019-04-28 18:45:00	12829
2019-04-28 18:50:00	12829
2019-04-28 18:55:00	25354
**2019-04-28 19:00:00	7143
2019-04-28 19:05:00	7143
2019-04-28 19:10:00	7143
2019-04-28 19:15:00	7143**
2019-04-28 19:20:00	34422

thanks
ne0

**Comment by rwaaren** [comment] 2019-04-28 18:01
Please use the forum for these type of questions. This issue list is not the right place.
This script you original posted cannot produce this Log Output. It does not add anything to the historical data so it will produce errors. 
You need to add at least something like domoticz.data.pastLux.add(domoticz.devices(xxx).lux) to get it working

**Comment by mc02** [comment] 2019-04-28 18:24
But isnt that the right place to report a bug?
I dont need support for my script, it runs fine.
My Point was that the avg function returns 0 under those special conditions.

i only postet the relevant parts of the script but added a little more code for clarification.

if this post is still at the wrong place so please remove it.

**Comment by rwaaren** [comment] 2019-04-28 19:02
From the README of this github

"Support
Your first place for support is the Domoticz Forum
The Github issue tracker is NOT for end-user support."

As far as I can see it this is not a bug. the avg function just returns 0 if no (valid) data is left. Valid data in this case is data younger as 15 minutes.
This is as described in the wiki:
_avg( [fromIdx], [toIdx], [default] ): Calculates the average of all item values within the range fromIdx to toIdx. If no data are in the set, the value default will be returned instead of 0._
Please post the complete script on the forum. If you only post part of the script I will have to guess what the missing parts are.

I cannot remove the issue, You have to close it yourselve or wait until @gizmocuz will do it for you.

**Comment by mc02** [comment] 2019-04-28 23:27
> From the README of this github
> 
> "Support
> Your first place for support is the Domoticz Forum
> The Github issue tracker is NOT for end-user support."
> 
As i said, i dont ask for support, i want to report this as a bug

> As far as I can see it this is not a bug. the avg function just returns 0 if no (valid) data is left. Valid data in this case is data younger as 15 minutes.
> This is as described in the wiki:
> _avg( [fromIdx], [toIdx], [default] ): Calculates the average of all item values within the range fromIdx to toIdx. If no data are in the set, the value default will be returned instead of 0._
> Please post the complete script on the forum. If you only post part of the script I will have to guess what the missing parts are.
> 
i already said i posted the complete script, i also highlighted the relevant parts in **BOLD**
the last part is the raw data from the table of that sensor, as you can see data from the last 15min is

7143, 7143, 7143, 7143 and the avg of this results in 0 but should be 7143

**Comment by gizmocuz** [comment] 2019-04-29 05:59
@mc02 , have you read and considered what rwaaren said ?

> As far as I can see it this is not a bug. the avg function just returns 0 if no (valid) data is left. Valid data in this case is data younger as 15 minutes.
> This is as described in the wiki:
> avg( [fromIdx], [toIdx], [default] ): Calculates the average of all item values within the range fromIdx to toIdx. If no data are in the set, the value default will be returned instead of 0.

Could that be your case ?

**Comment by mc02** [comment] 2019-04-29 07:46
> @mc02 , have you read and considered what rwaaren said ?
yes
> Could that be your case ?
maybe im missing something, you see my raw table data from the past ~20min, as you can see its filled with data
2019-04-28 19:00:00	7143
2019-04-28 19:05:00	7143
2019-04-28 19:10:00	7143
2019-04-28 19:15:00	7143

so on 2019-04-28 19:15:00.491 the avg function reports 0 despite the fact there are data entries younger 15min, as far i can see this it only happens when every item left in the history table is the same value.

**Closed as completed** 2019-05-21 07:48 UTC
