### ISSUE TITLE
Domoticz segfault on exit (python3.8.x), on exit and stopping plugins (python3.9.x)

### ISSUE THREAD

**Issue by moroen** [domoticz/domoticz#4672] opened 2021-02-23 20:55 UTC
In relation to #4487, the latest domoticz beta (build 12983) still fails on exit and when stopping a plugin, when using python 3.9.x. In addition, while previous builds have worked on python 3.8, the latest build crashes on exit if one or more plugins are installed, or if all plugins have been deleted. Stopping/deleting plugins does work when using python 3.8, but exiting domoticz with a plugin installed aborts and coredumps. 

Python 3.8.5 (Ubuntu 20.04)
```
2021-02-23 21:41:34.897  Status: PluginSystem: Exiting work loop.
Fatal Python error: PyInterpreterState_Delete: remaining subinterpreters
Python runtime state: finalizing (tstate=0x564c34cb6320)

2021-02-23 21:41:34.904  Error: Domoticz(pid:1979, tid:1979('domoticz')) received fatal signal 6 (Aborted)
2021-02-23 21:41:34.904  Error: siginfo address=0x7bb, address=0x7f9fb83fc18b
2021-02-23 21:41:34.911  Error: Failed to start gdb, will use backtrace() for printing stack frame

2021-02-23 21:41:34.914  Error: #0  ./domoticz :  + 0x373706 [0x564c32a90706]
2021-02-23 21:41:34.914  Error: #1  ./domoticz : signal_handler(int, siginfo_t*, void*) + 0x235 [0x564c32a91215]
2021-02-23 21:41:34.914  Error: #2  /lib/x86_64-linux-gnu/libpthread.so.0 :  + 0x153c0 [0x7f9fb87143c0]
2021-02-23 21:41:34.914  Error: #3  /lib/x86_64-linux-gnu/libc.so.6 : gsignal + 0xcb [0x7f9fb83fc18b]
2021-02-23 21:41:34.914  Error: #4  /lib/x86_64-linux-gnu/libc.so.6 : abort + 0x12b [0x7f9fb83db859]
2021-02-23 21:41:34.914  Error: #5  /lib/x86_64-linux-gnu/libpython3.8.so :  + 0x74c38 [0x7f9fb721dc38]
2021-02-23 21:41:34.914  Error: #6  /lib/x86_64-linux-gnu/libpython3.8.so :  + 0x1923f9 [0x7f9fb733b3f9]
2021-02-23 21:41:34.914  Error: #7  /lib/x86_64-linux-gnu/libpython3.8.so : PyInterpreterState_Delete + 0x11b [0x7f9fb7338f1b]
2021-02-23 21:41:34.914  Error: #8  /lib/x86_64-linux-gnu/libpython3.8.so : Py_FinalizeEx + 0x158 [0x7f9fb733c4a8]
2021-02-23 21:41:34.914  Error: #9  ./domoticz : Plugins::CPluginSystem::StopPluginSystem() + 0x645 [0x564c32e96c25]
2021-02-23 21:41:34.914  Error: #10 ./domoticz : MainWorker::Stop() + 0x225 [0x564c32a4d4d5]
2021-02-23 21:41:34.914  Error: #11 ./domoticz : main + 0x668 [0x564c3298f4f8]
2021-02-23 21:41:34.914  Error: #12 /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main + 0xf3 [0x7f9fb83dd0b3]
2021-02-23 21:41:34.914  Error: #13 ./domoticz : _start + 0x2e [0x564c329b1fce]
Aborted (core dumped)
```

Python 3.9.2 (EndeavourOS (Arch)):
```
2021-02-23 20:52:24.390  Python Plugin System: (Kodi) onStop called
Fatal Python error: Segmentation fault

Thread 0x00007f9a4e9f1c00 (most recent call first):
<no Python frame>
2021-02-23 20:52:24.393  Error: Domoticz(pid:12580, tid:12583('PluginMgr')) received fatal signal 11 (Segmentation fault)
2021-02-23 20:52:24.393  Error: siginfo address=0x3e800003124, address=0x7f9a4e711498
2021-02-23 20:52:24.401  Error: Failed to start gdb, will use backtrace() for printing stack frame

2021-02-23 20:52:24.403  Error: #0  ./domoticz :  + 0x35bd36 [0x5577a54bad36]
2021-02-23 20:52:24.403  Error: #1  ./domoticz : signal_handler(int, siginfo_t*, void*) + 0x225 [0x5577a54bb805]
2021-02-23 20:52:24.403  Error: #2  /usr/lib/libpthread.so.0 :  + 0x13960 [0x7f9a4f25e960]
2021-02-23 20:52:24.403  Error: #3  /usr/lib/libpython3.9.so : PyEval_ReleaseLock + 0x15 [0x7f9a4e711498]
2021-02-23 20:52:24.403  Error: #4  ./domoticz : Plugins::CPlugin::Stop() + 0xb7 [0x5577a590f387]
2021-02-23 20:52:24.403  Error: #5  ./domoticz : Plugins::CPluginMessageBase::Process() + 0x35 [0x5577a5437d95]
2021-02-23 20:52:24.403  Error: #6  ./domoticz : Plugins::CPluginSystem::Do_Work() + 0x985 [0x5577a5913155]
2021-02-23 20:52:24.403  Error: #7  ./domoticz :  + 0xa38be4 [0x5577a5b97be4]
2021-02-23 20:52:24.403  Error: #8  /usr/lib/libpthread.so.0 :  + 0x9299 [0x7f9a4f254299]
2021-02-23 20:52:24.403  Error: #9  /usr/lib/libc.so.6 : clone + 0x43 [0x7f9a4efc5053]
[1]    12580 segmentation fault (core dumped)  ./domoticz
```

**Comment by dnpwwo** [comment] 2021-02-23 22:26
I gave up trying to test this fix 100% because of Python 3.9+ so I've pushed the fix.

Confirmed that Python below 3.9 on Linux is not impacted.  On Windows  and Linux with 3.9+ it already crashes so it can't be made worse.

Can you retry?

BTW I don't believe the first crash dump is the same problem so this will possible persist

**Comment by rwaaren** [comment] 2021-02-23 23:28
> Can you retry?
> 

tested with Python 3.9.1 and 3.7.3

disabling a Python plugin and stopping domoticz both worked without crash. So it looks like you fixed it.

Thx !!

**Comment by moroen** [comment] 2021-02-24 14:21
@dnpwwo, 
I can confirm that python3.9.1 now works, good job! 

Unfortunately, I can also confirm that the crash on exit  with python 3.8.5 indeed persists as you predicted.

**Comment by peter4200** [comment] 2021-02-24 17:53
Thanks, developers. Just compiled and tested on Fedora 33 with Python 3.9.1 and python plugins are working again

**Comment by moroen** [comment] 2021-02-26 08:33
I just issued a pull request that should fix the "Fatal Python error: PyInterpreterState_Delete: remaining subinterpreters" when using python 3.8.x and below. Py_Finalize should, according to the docs, terminate all lingering subinterpreters, which it appears to do when using python3.9, but throws fatal python error on lower python versions.

**Closed as completed** 2021-02-28 17:06 UTC
