### ISSUE TITLE
TTN GPS tracker cayenne 'gmatch' error

### ISSUE THREAD

**Issue by jeroenkl** [domoticz/domoticz#3568] opened 2019-08-12 07:22 UTC
@gizmocuz 
Got since some weeks the follwing issue filling the logfiles:
2019-07-24 14:40:29.961 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: /home/pi/domoticz/dzVents/runtime/Utils.lua:26: bad argument #1 to 'gmatch' (string expected, got nil)

Only occurs when my TTN GPS tracker is online sending data to cayenne.

Can you please check?

BR,

Jeroen

_Originally posted by @jeroenkl in https://github.com/domoticz/domoticz/issues/3050#issuecomment-514642257_

**Comment by rwaaren** [comment] 2019-08-12 07:38
This does not appear to be a domoticz code problem. Please post this on the forum and include your domoticz / dzVents version and the script triggering this error. Thx.

**Comment by jeroenkl** [comment] 2019-08-12 07:43
> This does not appear to be a domoticz code problem. Please post this on the forum and include your domoticz / dzVents version and the script triggering this error. Thx.

it is coming from the domoticz code. De dzVents script is part of the domoticz code. Not managed or created by me.
See for ref #3050 
Current domoticz Version: 4.11083

**Comment by rwaaren** [comment] 2019-08-12 07:54
Thx for your quick reply and including your version number. I am one of the maintainers of the dzVents (Lua) code  but to be able to help I do need to be able to have a look at the script triggering this error.  The only way /home/pi/domoticz/dzVents/runtime/Utils.lua is called, is by a user script.

**Comment by jeroenkl** [comment] 2019-08-12 08:07
> Thx for your quick reply and including your version number. I am one of the maintainers of the dzVents (Lua) code but to be able to help I do need to be able to have a look at the script triggering this error. The only way /home/pi/domoticz/dzVents/runtime/Utils.lua is called, is by a user script.

I'm sorry but there is no userscript. I used the hardware option:
**The Things Network (MQTT/CAyenneLPP) with LAN interface**
It is a build in option which connect to TTN with my credentials and uses the Cayenne protocol.

But, only when the GPS tracker is switched 'on', the error occurs.

**Comment by rwaaren** [comment] 2019-08-12 08:18
If you don't use dzVents at all you can switch it off in settings other.
If you do use it, please switch the dzVents logging to debug and report the lines before and after the error. This might help in identifying the reason why the Utils.lua is called.

**Comment by jeroenkl** [comment] 2019-08-12 09:19
> If you don't use dzVents at all you can switch it off in settings other.
> If you do use it, please switch the dzVents logging to debug and report the lines before and after the error. This might help in identifying the reason why the Utils.lua is called.

I do use dzVents ;-) but not for the Cayenne MQTT.
Issue occured after a domoticz update some months ago.
I'll check the log and let you know.

**Comment by jeroenkl** [comment] 2019-08-12 09:30
The logging:

2019-08-12 11:27:13.458 Status: dzVents: Debug: Processing device-adapter for ttgo_beam_xxxxxx: Barometer device adapter
2019-08-12 11:27:13.460 Status: dzVents: Debug: Processing device-adapter for ttgo_beam_xxxxxx: Temperature+humidity device adapter
2019-08-12 11:27:13.461 Status: dzVents: Debug: dzVents version: 2.4.28
2019-08-12 11:27:13.461 Status: dzVents: Debug: Event triggers:
2019-08-12 11:27:13.461 Status: dzVents: Debug: - Device: ttgo_beam_xxxxxx
2019-08-12 11:27:13.461 Status: dzVents: Debug: - Device: ttgo_beam_xxxxxx
2019-08-12 11:27:13.461 Status: dzVents: Debug: - Device: ttgo_beam_xxxxxx
2019-08-12 11:27:13.696 Status: dzVents: Debug: Dumping domoticz data to /home/pi/domoticz/scripts/dzVents/domoticzData.lua
2019-08-12 11:27:13.918 Status: dzVents: Debug: Processing device-adapter for ttgo_beam_xxxxxx: Voltage device adapter
2019-08-12 11:27:13.919 Status: dzVents: Debug: dzVents version: 2.4.28
2019-08-12 11:27:13.919 Status: dzVents: Debug: Event triggers:
2019-08-12 11:27:13.919 Status: dzVents: Debug: - Device: ttgo_beam_xxxxxxx
2019-08-12 11:27:14.092 Status: dzVents: Debug: Dumping domoticz data to /home/pi/domoticz/scripts/dzVents/domoticzData.lua
2019-08-12 11:27:14.272 Status: dzVents: Debug: Processing device-adapter for ttgo_beam_xxxxxx: Voltage device adapter
2019-08-12 11:27:14.273 Status: dzVents: Debug: dzVents version: 2.4.28
2019-08-12 11:27:14.273 Status: dzVents: Debug: Event triggers:
2019-08-12 11:27:14.273 Status: dzVents: Debug: - Device: ttgo_beam_xxxxxx
2019-08-12 11:27:15.376 Status: dzVents: Debug: Dumping domoticz data to /home/pi/domoticz/scripts/dzVents/domoticzData.lua

2019-08-12 11:29:16.478 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: /home/pi/domoticz/dzVents/runtime/Utils.lua:52: bad argument #1 to 'gmatch' (string expected, got nil)

**Comment by gizmocuz** [comment] 2019-08-12 09:44
@rwaaren , could it be that you don't handle/know the GPS sensor in dzVents and try to split the sValue ?

**Comment by rwaaren** [comment] 2019-08-12 10:36
Could well be. Will investigate but will not be any sooner then tonight.

**Comment by jeroenkl** [comment] 2019-08-12 10:38
> Could well be. Will investigate but will not be any sooner then tonight.

No worries, already thankfull you are willing to help. 
Domoticz is a great product

**Comment by rwaaren** [comment] 2019-08-12 17:47
@jeroenkl,  cannot replicate your setup so need your help to solve this.

I understand from  #3050 that gps value is stored in uservariable. but do not see what triggers the stringSplit function in Utils.lua yet.

Can you please replace the self.stringSplit function in /home/pi/domoticz/dzVents/runtime/Utils.lua
with this one ? It will probably not solve the problem but might give me more information to work with if the error pops-up in one of the other dzVents runtime Lua's 
It will not influence any dzVents scripts. 

```
function self.stringSplit(text, sep)
	local sep = sep or '%s'
	local text = text or ''
	local t = {}
	for str in string.gmatch(text, "([^"..sep.."]+)") do
		table.insert(t, str)
	end
	return t
end
```

**Comment by jeroenkl** [comment] 2019-08-12 18:38
Hi @rwaaren,

Performed, resulting in:

2019-08-12 20:34:23.689 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: /home/pi/domoticz/dzVents/runtime/Time.lua:196: field 'day' missing in date table
2019-08-12 20:36:26.718 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: /home/pi/domoticz/dzVents/runtime/Time.lua:196: field 'day' missing in date table

available for any tests ;-)

BR,

Jeroen

**Comment by rwaaren** [comment] 2019-08-12 21:47
@jeroenkl, Thx!

next step to locate origin of the error:

please replace part in /home/pi/domoticz/dzVents/runtime/Time.lua starting with line 173
( if (isUTC~=nil and isUTC==true) then ) and ending with line 196 
( local dDate = os.time{year=y,month=mon,day=d,hour=h,min=min,sec=s }

with code

```
	if (isUTC~=nil and isUTC==true) then
		now = os.date('!*t')
	else
		now = os.date('*t')
		isUTC = false
	end

	utils.log('sDate : ' .. tostring(sDate), utils.LOG_FORCE)  

	if (sDate == nil or sDate == '') then
		local now
		if (isUTC) then
			now = os.date('!*t')
		else
			now = os.date('*t')
		end
		local ms = _testMS == nil and getMS() or _testMS
		sDate = now.year .. '-' .. now.month ..'-' .. now.day .. ' ' .. now.hour .. ':' .. now.min .. ':' .. now.sec .. '.' .. tostring(ms)
	end
 
	utils.log('sDate : ' .. tostring(sDate), utils.LOG_FORCE)  
  
	local y,mon,d,h,min,s = parseDate(sDate)

	utils.log('y, m, d, h, min, s : ' .. 
		tostring(y) .. ', ' ..
		tostring(mon) .. ', ' ..
		tostring(d) .. ', ' ..
		tostring(h) .. ', ' ..
		tostring(min) .. ', ' ..
		tostring(s)	 , utils.LOG_FORCE)

	-- extract s and ms
	s, ms = getSMs(s)

	local dDate = os.time{year=y,month=mon,day=d,hour=h,min=min,sec=s }

```
Again it will not yet solve the error but it hopefully brings us one step closer to identifying the cause.

**Comment by jeroenkl** [comment] 2019-08-13 06:47
Hi @rwaaren,

Changed the related file as requested, the log:

2019-08-13 08:46:07.560 Status: dzVents: !Info: sDate : nil
2019-08-13 08:46:07.560 Status: dzVents: !Info: sDate : 2019-8-13 8:46:7.469
2019-08-13 08:46:07.560 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 8, 13, 8, 46, 7.469
2019-08-13 08:46:07.561 Status: dzVents: !Info: sDate : 2019-08-12 09:17:48
2019-08-13 08:46:07.561 Status: dzVents: !Info: sDate : 2019-08-12 09:17:48
2019-08-13 08:46:07.561 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 12, 09, 17, 48
2019-08-13 08:46:07.624 Status: dzVents: !Info: sDate : 2019-08-13 08:44:04
2019-08-13 08:46:07.624 Status: dzVents: !Info: sDate : 2019-08-13 08:44:04
2019-08-13 08:46:07.624 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 13, 08, 44, 04
2019-08-13 08:46:07.625 Status: dzVents: !Info: sDate : 2019-8-13 52.2657,5.1832,15.8:00
2019-08-13 08:46:07.625 Status: dzVents: !Info: sDate : 2019-8-13 52.2657,5.1832,15.8:00
2019-08-13 08:46:07.625 Status: dzVents: !Info: y, m, d, h, min, s : nil, nil, nil, nil, nil, nil
2019-08-13 08:46:07.723 Status: dzVents: !Info: sDate : nil
2019-08-13 08:46:07.724 Status: dzVents: !Info: sDate : 2019-8-13 8:46:7.659
2019-08-13 08:46:07.724 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 8, 13, 8, 46, 7.659
2019-08-13 08:46:07.724 Status: dzVents: !Info: sDate : 2019-08-12 09:17:48
2019-08-13 08:46:07.725 Status: dzVents: !Info: sDate : 2019-08-12 09:17:48
2019-08-13 08:46:07.725 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 12, 09, 17, 48
2019-08-13 08:46:07.788 Status: dzVents: !Info: sDate : 2019-08-13 08:44:04
2019-08-13 08:46:07.788 Status: dzVents: !Info: sDate : 2019-08-13 08:44:04
2019-08-13 08:46:07.789 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 13, 08, 44, 04
2019-08-13 08:46:07.830 Status: dzVents: !Info: sDate : 2019-08-13 08:44:04
2019-08-13 08:46:07.830 Status: dzVents: !Info: sDate : 2019-08-13 08:44:04
2019-08-13 08:46:07.831 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 13, 08, 44, 04
2019-08-13 08:46:07.832 Status: dzVents: !Info: sDate : 2019-08-13 08:44:04
2019-08-13 08:46:07.832 Status: dzVents: !Info: sDate : 2019-08-13 08:44:04
2019-08-13 08:46:07.832 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 13, 08, 44, 04
2019-08-13 08:46:07.626 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: /home/pi/domoticz/dzVents/runtime/Time.lua:208: field 'day' missing in date table

BR,

Jeroen

**Comment by jeroenkl** [comment] 2019-08-13 07:10
And when I reverted the utils.lua back to original:

2019-08-13 09:06:32.834 TTN_MQTT: Topic: ttgo-beam/devices/ttgo_beam_xxxxxx/up
2019-08-13 09:06:32.839 (MQTT client gateway TTN) General/Percentage (ttgo_beam_xxxxxx Altitude)
2019-08-13 09:06:32.854 (MQTT client gateway TTN) Temp (ttgo_beam_xxxxxxx)
2019-08-13 09:06:32.858 (MQTT client gateway TTN) Humidity (ttgo_beam_xxxxxx)
2019-08-13 09:06:32.870 (MQTT client gateway TTN) General/Barometer (ttgo_beam_xxxxxx)
2019-08-13 09:06:32.883 (MQTT client gateway TTN) General/Voltage (ttgo_beam_xxxxxx)
2019-08-13 09:06:32.895 (MQTT client gateway TTN) General/Voltage (ttgo_beam_xxxxxx)
2019-08-13 09:06:32.907 (MQTT client gateway TTN) General/Voltage (ttgo_beam_xxxxxx)

2019-08-13 09:06:33.279 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: /home/pi/domoticz/dzVents/runtime/Utils.lua:52: bad argument #1 to 'gmatch' (string expected, got nil)

2019-08-13 09:07:01.093 Status: dzVents: !Info: sDate : nil
2019-08-13 09:07:01.093 Status: dzVents: !Info: sDate : 2019-8-13 9:7:1.21
2019-08-13 09:07:01.093 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 8, 13, 9, 7, 1.21
2019-08-13 09:07:01.094 Status: dzVents: !Info: sDate : 2019-08-12 09:17:48
2019-08-13 09:07:01.094 Status: dzVents: !Info: sDate : 2019-08-12 09:17:48
2019-08-13 09:07:01.094 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 12, 09, 17, 48
2019-08-13 09:07:01.159 Status: dzVents: !Info: sDate : 2019-08-13 09:06:50
2019-08-13 09:07:01.159 Status: dzVents: !Info: sDate : 2019-08-13 09:06:50
2019-08-13 09:07:01.159 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 13, 09, 06, 50
2019-08-13 09:07:01.206 Status: dzVents: !Info: sDate : 2019-08-13 09:07:00
2019-08-13 09:07:01.206 Status: dzVents: !Info: sDate : 2019-08-13 09:07:00
2019-08-13 09:07:01.207 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 13, 09, 07, 00
2019-08-13 09:07:01.208 Status: dzVents: !Info: sDate : 2019-08-13 09:07:00
2019-08-13 09:07:01.209 Status: dzVents: !Info: sDate : 2019-08-13 09:07:00
2019-08-13 09:07:01.209 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 13, 09, 07, 00
2019-08-13 09:07:01.211 Status: dzVents: !Info: sDate : 2019-08-13 09:07:00
2019-08-13 09:07:01.211 Status: dzVents: !Info: sDate : 2019-08-13 09:07:00
2019-08-13 09:07:01.211 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 13, 09, 07, 00
2019-08-13 09:07:01.213 Status: dzVents: !Info: sDate : 2019-08-13 09:07:00
2019-08-13 09:07:01.213 Status: dzVents: !Info: sDate : 2019-08-13 09:07:00
2019-08-13 09:07:01.213 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 13, 09, 07, 00
2019-08-13 09:07:01.215 Status: dzVents: !Info: sDate : 2019-08-13 09:07:00
2019-08-13 09:07:01.215 Status: dzVents: !Info: sDate : 2019-08-13 09:07:00
2019-08-13 09:07:01.215 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 13, 09, 07, 00
2019-08-13 09:07:01.217 Status: dzVents: !Info: sDate : 2019-08-13 09:07:00
2019-08-13 09:07:01.217 Status: dzVents: !Info: sDate : 2019-08-13 09:07:00
2019-08-13 09:07:01.217 Status: dzVents: !Info: y, m, d, h, min, s : 2019, 08, 13, 09, 07, 00

**Comment by rwaaren** [comment] 2019-08-13 08:29
In the log (using the modified Time.lua and Utils.lua) you see that the  sDates variable (most likely when obtained from the TTN tracker uservariable) contains your GPS coordinates and not the expected date/time stamp. Need to investigate further but I am traveling so not much time. Will get back to you probably tonight.

**Comment by rwaaren** [comment] 2019-08-13 22:25
to work around error please replace part in /home/pi/domoticz/dzVents/runtime/Time.lua starting with 
if (UTC~=nil and isUTC==true) then 
and ending with 
local dDate = os.time{year=y,month=mon,day=d,hour=h,min=min,sec=s }

with code

```
	if (isUTC~=nil and isUTC==true) then
		now = os.date('!*t')
	else
		now = os.date('*t')
		isUTC = false
	end

	local function makesDate()
		local now
		if (isUTC) then
			now = os.date('!*t')
		else
			now = os.date('*t')
		end
		local ms = _testMS == nil and getMS() or _testMS
		return ( now.year .. '-' .. now.month ..'-' .. now.day .. ' ' .. now.hour .. ':' .. now.min .. ':' .. now.sec .. '.' .. tostring(ms) )
	end

	if sDate == nil or sDate == '' then
		sDate = makesDate() 
	end

	local y, mon, d, h, min, s 

	y, mon, d, h, min, s = parseDate(sDate)
	if not(y and mon and d and h and min and s) then
		sDate = makesDate()
		y, mon, d, h, min, s = parseDate(sDate)
		utils.log('sDate was invalid. Reset to ' .. sDate , utils.LOG_ERROR)  
	end

	-- extract s and ms
	s, ms = getSMs(s)

	local dDate = os.time{year=y,month=mon,day=d,hour=h,min=min,sec=s }

```
To identify root cause please set dzVents loglevel to debug and when you see the error
sDate was invalid. Reset to 'yyyy-mm-dd hh:mm' , please copy the file /home/pi/domoticz/scripts/dzVents/domoticzData.lua and send to dzdomovents@gmail.com after removing any potential sensitive data from it. Thx !

**Comment by jeroenkl** [comment] 2019-08-14 06:58
thxs! 
Currently performing the requested actions.
Indeed saw the the error: 
_2019-08-14 08:55:35.263 Error: dzVents: Error: (2.4.28) sDate was invalid. Reset to 2019-8-14 8:55:35.13_

I'll send the file to the provided email address.
Thxs!

Jeroen

**Comment by rwaaren** [comment] 2019-08-14 09:06
Thx for the domoticzData.lua

I found that in uservariable ttgo_beam_ttnmapper1 (type time) the data is 
`52.2657,5.1832,14.8 ` which is not a valid time format.

I can work around that in the dzVents runtime modules  but

@gizmocuz is this intentional ? and if not could this var be changed to a type string ?

**Comment by jeroenkl** [comment] 2019-08-14 09:49
The add the following 
The data is also send to cayenne dashboard and is handled the correct way.

![image](https://user-images.githubusercontent.com/37976568/63011859-74bf4580-be89-11e9-927d-8e52835eec53.png)

**Comment by gizmocuz** [comment] 2019-08-14 09:51
@rwaaren , well it supposed to be a string of course.... let me double check why this is reported as 'date/time'

Okey,in TTNMQTT.cpp i just call

UpdateUserVariable(DeviceName, sstr.str());

Which is a function in the file/class, and if the variable does not exists, it created on (USERVARTYPE_STRING)

Maybe @jeroenkl  changed the type in domoticz to date/time ?

**Comment by jeroenkl** [comment] 2019-08-14 10:09
@gizmocuz , nope I did not changed something to this var.
To test I created a new 'The Things Network (MQTT/CAyenneLPP) with LAN interface'  and domoticz created new IDX's. Ofcourse I suspended the original hardware interface.

![image](https://user-images.githubusercontent.com/37976568/63013346-53138d80-be8c-11e9-973e-26dad538f87c.png)

Still same error

**Comment by jeroenkl** [comment] 2019-08-14 10:15
IDX708 temp is high, but it in the sun ;-)
IDX711 should be satellites locked by GPS

received by Cayenne:
![image](https://user-images.githubusercontent.com/37976568/63013739-36c42080-be8d-11e9-88b7-547cc1b03b7d.png)

**Comment by jeroenkl** [comment] 2019-08-14 10:30
Ehhh, found it.
Somehow I add this and set it to 'time'.
Changed it to 'string' and error is gone, thanks all for your time!
![image](https://user-images.githubusercontent.com/37976568/63014607-36c52000-be8f-11e9-85a7-e77677b60d68.png)


Is it possible to have the 'IDX711' changed to GPS 'sat'?

**Comment by gizmocuz** [comment] 2019-08-14 12:40
@jeroenkl , I am confused.... what is IDX711 ? If i look at the screenshot above screenshot from the devices tab, it is a Voltage sensor ?
The screenshot above is from the User Variable overview ?

**Comment by jeroenkl** [comment] 2019-08-14 12:56
@gizmocuz, Yes it is in the device screenshot. It is by domoticz detected as voltage detector but it is actualy the GPS sat lock count.

**Comment by gizmocuz** [comment] 2019-08-15 05:57
@jeroenkl , Could you post the raw payload of the MQTT message that contains the lock count ?

**Comment by jeroenkl** [comment] 2019-08-15 07:43
@gizmocuz , below the raw data.

Is it possible to add a nice 'GPS' device with location info? ;-), battery and speed device?

`mosquitto_sub -h eu.thethings.network -u xxxxx -P ttn-account-v2.xxxxxxxxxxxxxxxxxxxxxx -v -t '#'

ttgo-beam/devices/ttgo_beam_ttnmapper1/up {"app_id":"ttgobeam","dev_id":"ttgo_beam_ttnmapper1","hardware_serial":"00xxxxxxxx","port":1,"counter":15,"payload_raw":"xxxxxxxxxxxxxxxxxxxxxx","payload_fields":{"analog_in_5":3.37,"analog_in_6":0.01,"analog_in_7":7,"barometric_pressure_4":1006.7,"gps_1":{"altitude":20.29,"latitude":52.2657,"longitude":5.1832},"relative_humidity_3":64.5,"temperature_2":23.6},"metadata":{"time":"2019-08-15T07:33:14.058847148Z","frequency":867.9,"modulation":"LORA","data_rate":"SF7BW125","airtime":92416000,"coding_rate":"4/5","gateways":[{"gtw_id":"eui-xxxxxx","timestamp":863872020,"time":"","channel":7,"rssi":-65,"snr":9.8,"rf_chain":0,"latitude":52.265717,"longitude":5.18308,"altitude":8,"location_source":"registry"}]}}
ttgo-beam/devices/ttgo_beam_ttnmapper1/up/relative_humidity_3 64.5
ttgo-beam/devices/ttgo_beam_ttnmapper1/up/barometric_pressure_4 1006.7
ttgo-beam/devices/ttgo_beam_ttnmapper1/up/analog_in_5 3.37
ttgo-beam/devices/ttgo_beam_ttnmapper1/up/analog_in_6 0.01
ttgo-beam/devices/ttgo_beam_ttnmapper1/up/analog_in_7 7
ttgo-beam/devices/ttgo_beam_ttnmapper1/up/gps_1 {"altitude":20.29,"latitude":52.2657,"longitude":5.1832}
ttgo-beam/devices/ttgo_beam_ttnmapper1/up/temperature_2 23.6
`

analogue 5 = battery in V
analogue 6 = speed in km/h
analogue 7 = satellite

**Comment by gizmocuz** [comment] 2019-08-15 11:19
Thank you for the data. Domoticz is using the payload_raw fields, but reading the JSON data, it seems some data (some data...) is inside analog_in_5, analog_in_6 and analog_in_7...
So there is no way Domoticz would know that this is a 'count' for example
Is there a field in CayenneLPP for a counter ?

**Comment by jeroenkl** [comment] 2019-08-15 16:19
Hi Gizmocuz, 

I don't think there is a field for it. The protocol Cayenne LPP format for payload data is used, no extra flags added.
But what's the difference between the temp/hum sensor on 2 and 3 (which domoticz handled fine) and the sensors on 5, 6 and 7?
(trying to help)

BR,

Jeroen

**Comment by gizmocuz** [comment] 2019-08-16 08:34
@jeroenkl , temp/hum sensors are well known.
Sensor 5 (6 and 7) are reported as analog .... i thread them as 'Voltage' ... analog voltage
In these sensors, you put the GPS satellite count ? I guess you created the code for the Lora node, so you should know this
If there was a CayenneLPP field that could for instance store a 16bit value, then we could use this (but maybe this has to be requested, maybe it is already there ? you have to look in the specs)

Another option is that i threat all analog sensors as 'custom sensors' in domoticz, you can then change the icon/label yourself, but as it is Analog (and not a counter) you will always see 14.00 instead of 14
That is why i think a static number field (16/32 bits) in CayenneLPP would be a better sollution

https://developers.mydevices.com/cayenne/docs/lora/#lora-cayenne-low-power-payload

**Comment by gizmocuz** [comment] 2019-08-16 08:48
Maybe the GPS data could be extended here to support a counter for the amount of satellites it is receiving:

https://www.win.tue.nl/san/education/IoT-inf4all/files/IPSO-Smart-Objects-Expansion-Pack.pdf

Here you can see the current mapping of the IPSO object ID's to the LPP id's:

https://developers.mydevices.com/cayenne/docs/lora/#lora-cayenne-low-power-payload-downlink-payload-structure

3202 (Analogue Input (From the IPSO Starter pack) Voltage) -> 2

**Comment by jeroenkl** [comment] 2019-08-18 08:57
Hi @gizmocuz, 

_I programmed the tracker as:_
      lpp.addGPS(1, lat, lon, alt);
      lpp.addTemperature(2, tmp);
      lpp.addRelativeHumidity(3, hum);
      lpp.addBarometricPressure(4, pressure);
      lpp.addAnalogInput(5, vBat);
      lpp,addAnalogInput(6, kmph);
      lpp.addAnalogInput(7, sats);

_I'm sure you are already aware of this info:_
as reference: CayenneLPP:
https://github.com/ElectronicCats/CayenneLPP

uint8_t addDigitalInput(uint8_t channel, uint32_t value);
uint8_t addDigitalOutput(uint8_t channel, uint32_t value);
uint8_t addAnalogInput(uint8_t channel, float value); // 3 decimals
uint8_t addAnalogOutput(uint8_t channel, float value); // 3 decimals
uint8_t addLuminosity(uint8_t channel, uint32_t value); // in luxes
uint8_t addPresence(uint8_t channel, uint32_t value);
uint8_t addTemperature(uint8_t channel, float value); // in celcius (1 decimal)
uint8_t addRelativeHumidity(uint8_t channel, float value); // in % (0.5% steps)
uint8_t addAccelerometer(uint8_t channel, float x, float y, float z); // 3 decimals for each axis
uint8_t addBarometricPressure(uint8_t channel, float value); // in hPa (1 decimal)
uint8_t addGyrometer(uint8_t channel, float x, float y, float z); // 2 decimals for each axis
uint8_t addGPS(uint8_t channel, float latitude, float longitude, float altitude); // lat & long with 4 decimals, altitude with 2 decimals

uint8_t addUnixTime(uint8_t channel, uint32_t value);

uint8_t addGenericSensor(uint8_t channel, float value);
uint8_t addVoltage(uint8_t channel, float value); // in volts (2 decimals)
uint8_t addCurrent(uint8_t channel, float value); // in amperes (3 decimals)
uint8_t addFrequency(uint8_t channel, uint32_t value); // in hertzs
uint8_t addPercentage(uint8_t channel, uint32_t value); // 0 to 100
uint8_t addAltitude(uint8_t channel, float value); // in meters
uint8_t addPower(uint8_t channel, uint32_t value); // in watts
uint8_t addDistance(uint8_t channel, float value); // in meters (3 decimals)
uint8_t addEnergy(uint8_t channel, float value); // in kWh (3 decimals)
uint8_t addDirection(uint8_t channel, float value); // in degrees
uint8_t addSwitch(uint8_t channel, uint32_t value); // 0 or 1

Decodes a byte array into a JsonArray (requires ArduinoJson library). The result is an array of objects, each one containing channel, type, type name and value. The value can be a scalar or an object (for accelerometer, gyroscope and GPS data). The method call returns the number of decoded fields or 0 if error.

uint8_t decode(uint8_t *buffer, uint8_t size, JsonArray& root);
Example output:

[
  {
    "channel": 1,
    "type": 136,
    "name": "gps",
    "value": {
      "latitude": 42.3518,
      "longitude": -87.9094,
      "altitude": 10
    }
  }
]

BR,

Jeroen

**Comment by jeroenkl** [comment] 2019-08-18 08:58
> @jeroenkl , temp/hum sensors are well known.
> Sensor 5 (6 and 7) are reported as analog .... i thread them as 'Voltage' ... analog voltage
> In these sensors, you put the GPS satellite count ? I guess you created the code for the Lora node, so you should know this
> If there was a CayenneLPP field that could for instance store a 16bit value, then we could use this (but maybe this has to be requested, maybe it is already there ? you have to look in the specs)
> 
> Another option is that i threat all analog sensors as 'custom sensors' in domoticz, you can then change the icon/label yourself, but as it is Analog (and not a counter) you will always see 14.00 instead of 14
> That is why i think a static number field (16/32 bits) in CayenneLPP would be a better sollution
> 
> https://developers.mydevices.com/cayenne/docs/lora/#lora-cayenne-low-power-payload

Agree the option to tread them as custom is possible a better solution.

BR,

Jeroen

**Comment by gizmocuz** [comment] 2019-08-23 08:07
@jeroenkl , i think a new counter would be the solution, could you ask if they could extend the protocol ?

**Comment by jeroenkl** [comment] 2019-08-29 04:28
@gizmocuz, 
The protocol will not change unfortunately

**Comment by gizmocuz** [comment] 2019-08-29 17:52
@jeroenkl , is there a link to the discussion maybe ?

**Comment by jeroenkl** [comment] 2019-08-31 08:24
2019-08-31 10:22:54.632 Status: TTN_MQTT: Unhandled type: accel (Please report!)
2019-08-31 10:22:54.632 Status: TTN_MQTT: Unhandled type: gyro (Please report!)

**Comment by waltervl** [comment] 2022-02-12 22:52
Close this issue?

**Closed as completed** 2022-02-13 08:52 UTC
