### ISSUE TITLE
latest beta not starting on Raspbian buster

### ISSUE THREAD

**Issue by Utopia69** [domoticz/domoticz#3881] opened 2020-01-31 21:18 UTC
errorlog:
Jan 31 22:15:33 raspberrypi systemd[1]: Starting LSB: Home Automation System...
Jan 31 22:15:33 raspberrypi domoticz.sh[23159]: /home/pi/domoticz/domoticz: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by /home/pi/domoticz/domoticz)
Jan 31 22:15:33 raspberrypi domoticz.sh[23159]: /home/pi/domoticz/domoticz: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /home/pi/domoticz/domoticz)
Jan 31 22:15:33 raspberrypi systemd[1]: Started LSB: Home Automation System.

**Comment by rwaaren** [comment] 2020-01-31 21:24
Duplicate of #3880 
Also [forum post](https://www.domoticz.com/forum/viewtopic.php?f=6&t=31157&sid=ff791dc7d9245319ac467785ccb75dcf)

**Closed as completed by rwaaren** 2020-01-31 21:24 UTC
