### ISSUE TITLE
SSL protocol issue

### ISSUE THREAD

**Issue by gordonb3** [domoticz/domoticz#2062] opened 2018-01-12 16:20 UTC
Looks like there is an issue with the in core SSL library. Checksums appear to be incorrect, leading to connectivity errors.

Details here: https://www.domoticz.com/forum/viewtopic.php?f=12&t=21365&start=4

**Comment by gizmocuz** [comment] 2018-01-27 10:21
Not sure what you mean by this (also not from the topic).
The library is a normal system library or retrieved via the aptitude system...
Do we need to solve something ?

**Comment by gordonb3** [comment] 2018-01-27 16:48
As the logging that was submitted in the forum topic shows: the checksum on the encrypted packages that are being sent from Domoticz is incorrect, apparently also leading to Domoticz not accepting whatever is returned by the peer website it tries to connect to.

I don't really know the details as it is not my setup that this log came from. I also do not run Debian on my system, so I don't know how they normally organize things, but on my system I usually do not have static libs available. All I know is that I do not see any of these errors nor do I have any problems connecting to outside web portals on my system where Domoticz was compiled to do dynamic linking.

**Comment by gizmocuz** [comment] 2018-01-28 08:02
The problem is that between jessy and stretch there are different versions, and i can not build one version that supports both unfortunately.

**Comment by koenkooi** [comment] 2018-01-28 11:16
This might be a red herring since people reported issues on x86_64 as well, but I ran into a similar bug when using armv7a: https://github.com/openssl/openssl/issues/4659

The reported uses an rpi3, but doesn't say if it's using 32bit or 64bit userspace, if it's 32bit, the above issue will trigger.

**Comment by gordonb3** [comment] 2018-01-28 19:29
So what you're saying is that this problem may be related to a specific version of openssl? Strangely it did start to work for this particular user after he switched to dynamic linking and as he did state that the earlier version he used was also compiled by himself I'm assuming that must be the same openssl version.

Admittedly: he did state he still saw the bad checksums on the https communication afterwards. Which raises the question what version he is using and what version you compile in as a static library? Who else may be affected by this bug and is there something we can do about it or does a solution have to come from the maintainers of whatever distribution they're using?

**Comment by gizmocuz** [comment] 2018-01-29 07:49
The binaries of Domoticz are not linked statically

> pi@raspbuild:~/dev-domoticz $ ldd domoticz | grep ssl
>         libssl.so.1.0.2 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.2 (0x76a72000)
> 

Because when you do, the HTTP does indeed not seem to work anymore

A solution would be IF we could link statically AND the HTTP still is working, but i was unable to do so

There should be no issue when stretch is used with the binary distribution

**Comment by gordonb3** [comment] 2018-01-29 08:36
hmm?

```
set (domoticz_VERSION_MINOR 0)
set (domoticz_VERSION_PATCH ${ProjectRevision})

option(USE_OPENSSL_STATIC "Link OpenSSL static" YES)
IF(USE_OPENSSL_STATIC)
	set(OPENSSL_USE_STATIC_LIBS TRUE)
ENDIF(USE_OPENSSL_STATIC)

option(USE_BUILTIN_LUA "Use builtin lua library" YES)
IF(USE_BUILTIN_LUA)
  IF(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
```

**Comment by xbeaudouin** [comment] 2018-01-29 14:04
Sure, but domoticz depends of libcurl, which can be dynamicaly linked to libssl.
So if you like 2 libssl on domoticz you can have "strange" stuff happening.
That's why 2 pkg should be done ... But this is time consuming.

**Comment by gordonb3** [comment] 2018-01-29 14:42
Aha! A very good point indeed. It also means that the ldd output quoted by Gizmocuz may be misleading because libssl.so is (also) pulled in as a secondary dependency through libcurl.

Gizmocuz: can you double check with command
>` readelf -s domoticz | grep "@NSS"`

If openssl is statically linked (and from that `CMakeLists.txt` snippet I'd say it must be) this should produce output similar to this
>`   256: 00000000000249c0   158 FUNC    GLOBAL DEFAULT   12 SSL_InvalidateSession@@NSS_3.2
`

**Comment by gizmocuz** [comment] 2018-01-29 15:56
This is the output of the build system

```
pi@raspbuild:~ $ cd dev-domoticz/
pi@raspbuild:~/dev-domoticz $ readelf -s domoticz | grep "@NSS"
pi@raspbuild:~/dev-domoticz $


```

**Comment by gordonb3** [comment] 2018-01-29 16:39
Right... my bad :(

Apparently one can't trust symbol names to be the same in every situation. So I just downloaded the x64 version and it has 470 SSL related entries in the symbol list whereas my live system only has 68. That last one is not up to date though, so I would have to compile that same version as the downloaded executable on my own system to verify.

**Comment by gordonb3** [comment] 2018-02-02 15:59
Okay. Took some fiddling to get the static libs available on my build system, but building Domoticz with `-DUSE_OPENSSL_STATIC="NO"` results in an image that contains 10,534 less symbols than leaving this configure option at its default value. The additional symbol list includes large quantities of `SSL_`, `X509_` and `PKCS*` entries. The latter being the most obvious as there are no `PKCS*` at all in the image that only has dynamic linked openssl.

So yes, openssl is most definitely linked in static. Which kind of seems pointless as it is also has a dependency on the dynamic library. Question remains how this relates to reported issues (there's another one [HERE](https://www.domoticz.com/forum/viewtopic.php?f=6&t=21994))

**Comment by heggink** [comment] 2018-02-06 16:03
@gizmocuz did a fresh install following the build from source wiki (boost, openzwave and domoticz) but still get the "Nest error login". Any suggestions on how to figure this out? Tried the -DUSE_OPENSSL_STATIC="NO" but no joy. upgradebeta works fine (no python which I don't really use) but build from source breaks the old Nest plugin...

**Comment by gizmocuz** [comment] 2018-02-09 13:37
Are you linking against libssl1.0-dev ? (see the build guide) if not try

sudo apt-get remove libssl-dev
sudo apt-get install libssl1.0-dev

Getting quite nuts hre with that libssl library and dependencies between distributions...

**Comment by heggink** [comment] 2018-02-09 17:12
I thought I was but apparently not. Your fix did the work! Now I just need to fix the fatal signal 6 issue :-). Thanks!

**Comment by heggink** [comment] 2018-02-12 19:17
@gizmocuz  here's another thing for you: using your suggestion, the Nest issue is gone but, guess what: the python plugins now crash?!?!?! Hadn't found the time to test the python plugins so 1) did the latest upgrade (web ui) today, then did a git pull and make and restarted domoticz using my own binary. Added harmony hub and ... signal 11.
Really bizarre that these changes have such an impact. I know my coding days are quite a bit behind me but this makes no sense...

**Comment by heggink** [comment] 2018-02-12 23:30
At least for python, the issue is related to https://www.domoticz.com/forum/viewtopic.php?f=6&t=22012&p=171001#p171001

**Comment by gizmocuz** [comment] 2018-06-07 09:40
Can we close this issue ?

**Comment by gordonb3** [comment] 2018-06-07 12:06
Don't know. I've never been able to replicate the issue myself. I only saw the logs from others. I guess if nobody else can replicate the checksum failures it should be okay to close it. People can submit a new issue if this is still a problem.

**Comment by gizmocuz** [comment] 2018-06-07 12:23
Thanks! Closing for now

**Closed as completed by gizmocuz** 2018-06-07 12:23 UTC
