### ISSUE TITLE
Python framework memory leak

### ISSUE THREAD

**Issue by heggink** [domoticz/domoticz#5234] opened 2022-05-13 09:32 UTC
Using the below python plugin and consistently sending messages with `while :; do netcat -N localhost $PORTNO < testdata; sleep 2; done`

Will lead to a gradual consumption of domoyticz process memory:

![Screenshot 2022-05-13 084120](https://user-images.githubusercontent.com/3987735/168255328-8c3f71dd-9526-4772-b46c-2fadcf6abe57.jpg)

This is using Domoticz, not DomoticzEx with Domoticz build 14318 Build Hash: a380461ea, Compile Date: 2022-04-22 06:36:31 on raspberry pi

```
"""
<plugin key="Test" name="Listener Test Plugin" author="heggink" version="1.0.1">
    <params>
        <param field="Port" label="Port" width="75" required="true" default="8008"/>
    </params>
</plugin>
"""

import Domoticz
#import json
#import sys
#import socket

class BasePlugin:
    enabled = False
    httpServerConn = None

    def __init__(self):
        return

    def onStart(self):
        self.httpServerConn = Domoticz.Connection(Name="Server Connection", Transport="TCP/IP", Protocol="HTML", Port=Parameters["Port"])
        self.httpServerConn.Listen()

    def onConnect(self, Connection, Status, Description):
        Domoticz.Log("onConnect called")
        if (Status == 0):
            Domoticz.Log("Connected successfully to: "+Connection.Address+":"+Connection.Port)
        else:
            Domoticz.Error("Failed to connect ("+str(Status)+") to: "+Connection.Address+":"+Connection.Port+" with error: "+Description)
        Domoticz.Log(str(Connection))

    def onMessage(self, Connection, Data):
        Domoticz.Log("onMessage called for connection: " + Connection.Address + ":" + Connection.Port)
        strData = Data.decode("utf-8", "ignore")
        Domoticz.Log("Message received " + strData)

    def onCommand(self, Unit, Command, Level, Hue):
        Domoticz.Log("onCommand called for Unit " + str(Unit) + ": Parameter '" + str(Command) + "', Level: " + str(Level))

    def onDisconnect(self, Connection):
        Domoticz.Log("onDisconnect called for connection '" + Connection.Name + "'.")
        Domoticz.Log("Connections:")

    def onHeartbeat(self):
        Domoticz.Log("onHeartbeat called ")

global _plugin
_plugin = BasePlugin()

def onStart():
    global _plugin
    _plugin.onStart()

def onConnect(Connection, Status, Description):
    global _plugin
    _plugin.onConnect(Connection, Status, Description)

def onMessage(Connection, Data):
    global _plugin
    _plugin.onMessage(Connection, Data)

def onCommand(Unit, Command, Level, Hue):
    global _plugin
    _plugin.onCommand(Unit, Command, Level, Hue)

def onDisconnect(Connection):
    global _plugin
    _plugin.onDisconnect(Connection)

def onHeartbeat():
    global _plugin
    _plugin.onHeartbeat()
```

**Comment by pipiche38** [comment] 2022-05-13 10:25
you probably need to tell which version of Domoticz you are using. I know that the python framework has been through extensive changes and should have remove quiet a number of leak

**Comment by heggink** [comment] 2022-05-13 10:42
Yeah, apologies. This is using Domoticz, not DomoticzEx with Domoticz build 14318 Build Hash: a380461ea, Compile Date: 2022-04-22 06:36:31 on raspberry pi

**Comment by kiddigital** [comment] 2022-05-13 12:26
HI @heggink , could you also try the same plugin with the DomoticzEx framework? Good to know if the same things happens there as well. DomoticzEx is the target framework as it hopefully replaces the _legacy_ Domoticz framework one day.

**Comment by heggink** [comment] 2022-05-13 14:23
Just started the same test after changing import Domoticz to import DomoticzEx as Domoticz. Will report back.

**Comment by heggink** [comment] 2022-05-14 07:04
I will let it run for another day or two but, so far, same thing.

**Comment by heggink** [comment] 2022-05-14 18:01
![Screenshot_20220514-195711_Kiwi Browser](https://user-images.githubusercontent.com/3987735/168443400-69de5aed-1f6d-47c0-b7d3-752de173d66f.jpg)

**Comment by heggink** [comment] 2022-05-14 18:02
So trending the same way.

**Comment by heggink** [comment] 2022-05-16 07:10
Maybe good to know: on every incoming message the plugin gets an onConnect and a onDisconnect once the message is received.

**Comment by heggink** [comment] 2022-05-16 10:48
[vg.zip](https://github.com/domoticz/domoticz/files/8699349/vg.zip)

Valgrind log running:
valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind-out.txt ./domoticz

**Comment by Ittiz** [comment] 2022-05-17 12:54
I wonder if this issue and [5091](https://github.com/domoticz/domoticz/issues/5091) are related?  Both seem to be coming from Python.

**Comment by dnpwwo** [comment] 2022-05-20 09:37
I get
`bash: testdata: No such file or directory
`

**Comment by heggink** [comment] 2022-05-20 09:39
true so just create a file called testdata with anything in it. It sends that data to the plugin.

**Comment by dnpwwo** [comment] 2022-05-21 02:48
Pushed a fix for this.

FYI - @heggink the Plugin Framework does not support a protocol called 'HTML' (because that's a markup language and not a protocol), you may have meant 'HTTP'

**Comment by heggink** [comment] 2022-05-21 08:02
> Pushed a fix for this.
> 
> FYI - @heggink the Plugin Framework does not support a protocol called 'HTML' (because that's a markup language and not a protocol), you may have meant 'HTTP'

Correct. Typo :-). Thanks for the fix. I'll let it run for a while and report back!

**Comment by heggink** [comment] 2022-05-21 09:39
Is this the fix?
https://github.com/domoticz/domoticz/commit/5f4b1452f01c5f34b355f11bbbf1b6980dd71964

**Comment by dnpwwo** [comment] 2022-05-21 09:53
Yes

**Comment by heggink** [comment] 2022-05-21 10:07
OK, just did a build on my ubuntu box (22.04 with Python 3.10) and the problem seemed to still exist so building on my rpi3 now but that's slooooow... That still has 3.7 on it.

**Comment by heggink** [comment] 2022-05-21 19:24
![Screenshot_20220521-212151_Kiwi Browser](https://user-images.githubusercontent.com/3987735/169666365-e8f55168-9436-4845-a757-8f1a8986d8ef.jpg)
Doesn't look like the fix is being very effective...

**Comment by dnpwwo** [comment] 2022-05-22 02:39
Are you sure that you are sending valid HTTP to the plugin?

Note that if you are sending a Linux text file it won't be valid because Unix terminates lines with a carriage return but HTTP **explicitly** requires a carriage return **and line feed.**  That would make the protocol buffer increase in size for ever while it waited for a complete first line so that it knows whether it is a client or server message.

**Comment by heggink** [comment] 2022-05-22 06:08
Oh dear, that makes sense. Let me check. Thanks.

**Comment by heggink** [comment] 2022-05-22 06:44
OK, so 2 quick additional questions:
1) how does that work for the JSON protocol?
2) if the device that sends messages to the plugin does not include a CL/LF in the message, what better option would I have to handle that message? I suppose the default "None", correct?

**Comment by heggink** [comment] 2022-05-22 07:42
Nvm. Changed protocol to None on a couple of plugins and that seems to have fixed it. Many thanks for the help!

**Comment by kiddigital** [comment] 2022-05-22 07:48
> Are you sure that you are sending valid HTTP to the plugin?
> 
> 
> 
> Note that if you are sending a Linux text file it won't be valid because Unix terminates lines with a carriage return but HTTP **explicitly** requires a carriage return **and line feed.**  That would make the protocol buffer increase in size for ever while it waited for a complete first line so that it knows whether it is a client or server message.

Great to read that the issue of @heggink is solved. But shouldn't we consider some kind of timeout on the scenario @dnpwwo describes?

Or maybe even do some checking before handing it over the plugin as the expected type is configured?

**Comment by heggink** [comment] 2022-05-22 08:52
There's 2 options here IMHO: 1) the plugin description is rather sparse so maybe add some verbiage describing it's intended use and caveats
2) provide some warning in the framework if things don't go as expected.
That said, I continue to be a BIG fan of the work @dnpwwo has put into this!

**Comment by kiddigital** [comment] 2022-05-22 18:38
@heggink , thanks for the extended testing.. so to conclude, this exists in both the old and the new Python framework.

In is not actually a bug, as in a sense this is expected behavior as the framework keeps waiting for the correct CL/LF's to signal the 'end of the request'. In the mean time, new input coming in gets added to the buffer and therefore the buffer needs to keep expanding consuming more memory.

Question remaining is what to do with this knowledge? @dnpwwo , @gizmocuz any suggestions? Maybe we can at least document this behavior at the Wiki (maybe in a FAQ or as a note somewhere) @waltervl ?

And yes I agree.. the Python plugin framework is a great addition to Domoticz, so indeed thx @dnpwwo for all the great work!

**Comment by dnpwwo** [comment] 2022-05-22 23:52
To me the key thing here is that, if you are connecting to a plugin that is listening and handling a particular protocol, using a library or tool that supports the protocol is always the best idea.  Using network tools to send a file is not the most robust method.

Linux has command line tools for this (curl, wget, ...) and I would expect them to work.

To be more clear, when I said "HTTP explicitly requires a carriage return and line feed", I meant the actual HTTP standard itself [(https://datatracker.ietf.org/doc/html/rfc2616#page-31)](https://datatracker.ietf.org/doc/html/rfc2616#page-31) which I followed.  This is not a limitation in Domoticz.

**Comment by heggink** [comment] 2022-05-24 21:14
I was trying to run some additional tests but the last 2 betas crash when using "None" for protocol...

**Comment by heggink** [comment] 2022-05-26 20:02
![Screenshot_20220526-215823_Kiwi Browser](https://user-images.githubusercontent.com/3987735/170568453-ad46055c-0797-440b-94e1-c086652a5aa3.jpg)

Reopening: using the latest updates, compiled from source, if I set Protocol="None", memory still increases. That was not supposed to happen, right?

**Comment by kiddigital** [comment] 2022-07-29 07:50
@heggink , After commit https://github.com/domoticz/domoticz/commit/3ede84ac65bdb525e466b2136f7e1f85c2786039 , is this issue still there?

**Comment by heggink** [comment] 2022-07-29 09:53
Unfortunately, no. Just redid 2 tests, one for connections and the other for TCP messages and both still have the same leak AFAICT.

You can easily replicate as follows:

Create a test folder under plugins
copy the following in plugin.py:

```
"""
<plugin key="Test" name="Listener Test Plugin" author="heggink" version="1.0.1">
    <params>
        <param field="Port" label="Port" width="75" required="true" default="8765"/>
    </params>
</plugin>
"""

#import DomoticzEx as Domoticz
import Domoticz as Domoticz

class BasePlugin:
    enabled = False
    httpServerConn = None

    def __init__(self):
        return

    def onStart(self):
#        Domoticz.Debugging(1)
        self.httpServerConn = Domoticz.Connection(Name="Server Connection", Transport="TCP/IP", Protocol="None", Port=Parameters["Port"])
        self.httpServerConn.Listen()

    def onConnect(self, Connection, Status, Description):
        Domoticz.Log("onConnect called")

        if (Status == 0):
            Domoticz.Log("Connected successfully to: "+Connection.Address+":"+Connection.Port)
        else:
            Domoticz.Error("Failed to connect ("+str(Status)+") to: "+Connection.Address+":"+Connection.Port+" with error: "+Description)
        Domoticz.Log(str(Connection))

    def onMessage(self, Connection, Data):
        Domoticz.Log("onMessage called for connection: " + Connection.Address + ":" + Connection.Port)

    def onCommand(self, Unit, Command, Level, Hue):
        Domoticz.Log("onCommand called for Unit " + str(Unit) + ": Parameter '" + str(Command) + "', Level: " + str(Level))

    def onDisconnect(self, Connection):
        Domoticz.Log("onDisconnect called for connection '" + Connection.Name + "'.")

    def onHeartbeat(self):
        Domoticz.Log("onHeartbeat called ")

global _plugin
_plugin = BasePlugin()

def onStart():
    global _plugin
    _plugin.onStart()

def onConnect(Connection, Status, Description):
    global _plugin
    _plugin.onConnect(Connection, Status, Description)

def onMessage(Connection, Data):
    global _plugin
    _plugin.onMessage(Connection, Data)

def onCommand(Unit, Command, Level, Hue):
    global _plugin
    _plugin.onCommand(Unit, Command, Level, Hue)

def onDisconnect(Connection):
    global _plugin
    _plugin.onDisconnect(Connection)

def onHeartbeat():
    global _plugin
    _plugin.onHeartbeat()
```

restart domoticz and add the Listener test plugin

then run either one of the followingh 2 python scripts:

conn.py:

```
###########################################################################
# This python script creates and closes a TCP socket every 0.1 second
import socket
import time
HOST = "127.0.0.1"  # The server's hostname or IP address
PORT = 8765  # The port used by the server
while True:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
           s.connect((HOST, PORT))
           s.close()
           time.sleep(0.1)

```
msg.py:

```
###########################################################################
# This python script open a connection and sends a message every 0.05 seconds
import socket
import time
s=socket.socket()
s.connect(('127.0.0.1',8765))
str="Hello World"

while True:
    try:
       s.sendall(str.encode())
    except:
       s.close()
       s=socket.socket()
       s.connect(('127.0.0.1',8765))
       s.sendall(str.encode())
    time.sleep(0.05)
s.close()

```
"Talking" to Rob (gizmocus) a week or 2 ago, his comments were as follows:

PluginTransports.cpp
line 257
CPluginTransportTCP* pTcpTransport = new CPluginTransportTCP(m_HwdID, pConnection, sAddress, sPort);
a new connection is allocated and added to the connection list:
			// Add it to the plugins list of connections
			pConnection->pPlugin->AddConnection(pTcpTransport);
BUT void CPlugin::RemoveConnection(CPluginTransport *pTransport) only removes it from the list and does not deallocate (delete) the object

There also seems to be a similar issue with 'm_MessageQueue', where new messages are added with 'new', and here also, messages are taken from the queue but not deallocated.

According to the windows profiler.

I am not a c++ knowledgeable person in any shape or form and really struggle to read that code (my old C code was muuuch easier ;-)) so could not comment either way other than to say it sounds plausible.

Also, since, in my original plugin, I swapped TCP for a file based exchange, memory has been very stable and domoticz is now up and running for 40 days. Using the TCP version of the plugin, I would have run out of memory after some 3 weeks.

**Comment by kiddigital** [comment] 2022-07-29 11:10
@heggink , thx for retesting.

Do I see correctly that your are using the 'old' plugin framework ('import domoticz') and not the new one ('import DomoticzEx')?

Does the problem also exist when using the new one?

**Comment by heggink** [comment] 2022-07-29 11:25
Both domoticz and domoticzEx seem to have the same leaks afaict.

**Comment by kiddigital** [comment] 2022-07-29 11:26
Thx, maybe @dnpwwo can have a look to reproduce and hopefully fix it?

**Comment by delinend** [comment] 2022-08-01 08:18
I'm using Domoticz prebuild Beta releases, on my Windows server2016.

I see no MQTT problems in my longtime used 14353 release, but after updating to release 14440, I see MQTT errors, when involving Python scripts, in DzVents. My Domoticz, is restarting ~1-2minutes.
Ex.: 
2022-08-01 10:15:53.172 Error: (ProcessInbound) MQTT protocol violation: Invalid message length 40 for packet type '3' (iQoS:0, topicLen:5888)
2022-08-01 10:15:53.172 Error: (ProcessInbound) MQTT protocol violation, sending DisconnectedEvent to Connection.
2022-08-01 10:15:53.172 Error: BAD2 Vask - H801_33C05B: Disconnected from MQTT Server: 127.0.0.1:1883
2022-08-01 10:15:53.174 Error: (ProcessInbound) MQTT protocol violation: Invalid message length 40 for packet type '3' (iQoS:0, topicLen:5888)
2022-08-01 10:15:53.174 Error: (ProcessInbound) MQTT protocol violation, sending DisconnectedEvent to Connection.
2022-08-01 10:15:53.174 Error: BAD2 Skab - H801_4BD990: Disconnected from MQTT Server: 127.0.0.1:1883
2022-08-01 10:15:53.637 Error: CPluginTransport: Base handleRead invoked for Hardware 26
2022-08-01 10:15:53.638 Error: CPluginTransport: Base handleRead invoked for Hardware 22

I don't see any other errors in DZ log.

Sorry... I can't compile.

Best regards

**Comment by kiddigital** [comment] 2022-08-01 08:55
> I'm using Domoticz prebuild Beta releases, on my Windows server2016.
> 
> I see no MQTT problems in my longtime used 14353 release, but after updating to release 14440, I see MQTT errors, when involving Python scripts, in DzVents. My Domoticz, is restarting ~1-2minutes. Ex.: 2022-08-01 10:15:53.172 Error: (ProcessInbound) MQTT protocol violation: Invalid message length 40 for packet type '3' (iQoS:0, topicLen:5888) 2022-08-01 10:15:53.172 Error: (ProcessInbound) MQTT protocol violation, sending DisconnectedEvent to Connection. 2022-08-01 10:15:53.172 Error: BAD2 Vask - H801_33C05B: Disconnected from MQTT Server: 127.0.0.1:1883 2022-08-01 10:15:53.174 Error: (ProcessInbound) MQTT protocol violation: Invalid message length 40 for packet type '3' (iQoS:0, topicLen:5888) 2022-08-01 10:15:53.174 Error: (ProcessInbound) MQTT protocol violation, sending DisconnectedEvent to Connection. 2022-08-01 10:15:53.174 Error: BAD2 Skab - H801_4BD990: Disconnected from MQTT Server: 127.0.0.1:1883 2022-08-01 10:15:53.637 Error: CPluginTransport: Base handleRead invoked for Hardware 26 2022-08-01 10:15:53.638 Error: CPluginTransport: Base handleRead invoked for Hardware 22
> 
> I don't see any other errors in DZ log.
> 
> Sorry... I can't compile.
> 
> Best regards

@delinend , how do you see this related to this particular issue? Maybe better to open this question on the forum to get support in trying to identify the problem. If it turns out to be a real bug (reproducible scenario), feel free to open a separate issue here.

**Comment by delinend** [comment] 2022-08-01 09:16
@kiddigital , Thanks for replying.
I was just mention, that after upgrade from DZ Windows release 14353 til 14440, I can't execute any of my old Python script, without DZ is restarting (just after execution). Maybe nothing todo with memory leak, as it go's so fast (restarting), that I can't see the memory use of DZ.
My DZ is running "As Service"

Best regards

**Comment by heggink** [comment] 2022-08-01 10:20
Anything in the logs? It must be crashing for some reason so key to find the reason


Herman Eggink
________________________________

**Comment by delinend** [comment] 2022-08-01 15:40
@heggink , This is the only thing I see in the look. Some MQTT/Python errors, and then Domoticz restarts quickly again. This is an endless loop :-(

2022-08-01 12:40:26.795  MysensorGW_433: Temp + Humidity (TempHum)
2022-08-01 12:40:26.801  MysensorGW_433: Temp + Humidity + Baro (TempHumBaro-1)
2022-08-01 12:40:26.807  MysensorGW_433: Temp (Temp)
2022-08-01 12:40:26.847  MysensorGW_433: General/Barometer (Baro)
2022-08-01 12:40:26.852  MysensorGW_433: General/Voltage (Voltage)
2022-08-01 12:40:27.002  MysensorGW_433: General/Voltage (TempHumBaro-1 Batteri)
2022-08-01 12:40:31.765  MysensorGW_433: Temp (Temp)
2022-08-01 12:40:31.816  MysensorGW_433: General/Barometer (Baro)
2022-08-01 12:40:31.821  MysensorGW_433: General/Voltage (Voltage)
2022-08-01 12:40:34.269  MysensorGW_433: Temp (Temp)
2022-08-01 12:40:34.326  MysensorGW_433: Temp + Humidity (TempHum433-1)
2022-08-01 12:40:34.330  MysensorGW_433: Temp + Humidity + Baro (TempHumBaro)
2022-08-01 12:40:34.334  MysensorGW_433: General/Voltage (Voltage)
2022-08-01 12:40:36.197  MysensorGW: Rain (Regn)
2022-08-01 12:40:36.250  MysensorGW: General/Voltage (Regn - Batteri)
2022-08-01 12:40:36.731  MysensorGW_433: Temp (Temp)
2022-08-01 12:40:36.782  MysensorGW_433: General/Barometer (Baro)
2022-08-01 12:40:36.786  MysensorGW_433: General/Voltage (Voltage)
2022-08-01 12:40:41.297  Error: (ProcessInbound) MQTT protocol violation: Invalid message length 467 for packet type '3' (iQoS:0, topicLen:5632)
2022-08-01 12:40:41.297  Error: (ProcessInbound) MQTT protocol violation, sending DisconnectedEvent to Connection.
2022-08-01 12:40:41.297  Error: Postkasse H801_319325: Disconnected from MQTT Server: 127.0.0.1:1883
2022-08-01 12:40:41.578  Status: Domoticz V2022.1 (build 14440) (c)2012-2022 GizMoCuz
2022-08-01 12:40:41.578  Status: Build Hash: b793752ee, Date: 2022-07-30 17:12:25
2022-08-01 12:40:41.578  Status: Startup Path: C:\Program Files (x86)\Domoticz\
2022-08-01 12:40:41.583  Sunrise: 05:27:00 SunSet: 21:28:00
2022-08-01 12:40:41.583  Day length: 16:01:00 Sun at south: 13:28:00
2022-08-01 12:40:41.583  Civil twilight start: 04:40:00 Civil twilight end: 22:16:00
2022-08-01 12:40:41.583  Nautical twilight start: 03:30:00 Nautical twilight end: 23:26:00
2022-08-01 12:40:41.583  There is no astronomical twilight in the space of 24 hours
2022-08-01 12:40:41.600  Status: PluginSystem: Started, Python version '3.5.2', 4 plugin definitions loaded.
2022-08-01 12:40:41.602  Status: : Using poll interval of 1 secs.
2022-08-01 12:40:41.603  Active notification Subsystems: email (1/13)
2022-08-01 12:40:41.604  Status: WebServer(HTTP) started on address: :: with port 8081
2022-08-01 12:40:41.609  Status: Camera: settings (re)loaded
2022-08-01 12:40:41.609  Starting shared server on: :::6144
2022-08-01 12:40:41.609  Status: TCPServer: shared server started...
2022-08-01 12:40:41.610  Status: RxQueue: queue worker started...
2022-08-01 12:40:43.612  H801 Test H801_6F977C: Worker thread started.
2022-08-01 12:40:43.612  Status: MysensorGW: trying to connect to: 192.168.1.120:5003

Best regards

**Comment by heggink** [comment] 2022-08-02 07:57
This is not related to the memory bug so I suggest we continue this elsewhere. It does seem to be some kind of bug in handling a MQTT message. Please use the forum to report it. When reporting, also include the crash log as well as info on the hardware that is sending the messages to mqtt.

**Comment by heggink** [comment] 2022-08-02 07:58
> Thx, maybe @dnpwwo can have a look to reproduce and hopefully fix it?

I was indeed hoping that @dnpwwo can take another look. He looked at this before suggesting that I was using the wrong protocol (which I was). But using None as protocol still gives the same memory leaks.

**Closed as completed** 2023-07-26 06:11 UTC
Labels: bug
