### ISSUE TITLE
Build 13314 empty graph issue with type General, Counter Incremental

### ISSUE THREAD

**Issue by laplug** [domoticz/domoticz#4856] opened 2021-06-05 21:44 UTC
@michahagg the problem with P1 smartmeter is solved (thanks for that!), but there now is an issue with an empty graph with type General, Counter Incremental.
Don't know if it is related to the the issue with the P1 graph, since it is different type sensor.
No error messages to provide a clue as to what is wrong.

![TypeGeneralCounterIncremental](https://user-images.githubusercontent.com/70644748/120906170-7b6b0e00-c657-11eb-9329-1a41d835b4e5.PNG)

**Comment by michahagg** [comment] 2021-06-06 06:34
Thanks for the issue report. I'm looking into it now.

**Comment by jenshenk** [comment] 2021-06-07 00:14
Hi,
I'm seeing the same problem for the today and last 7 day graphs for switches since update 13311/13314. Maybe same issue?
Thanks so much for checking!

**Comment by magicwoody** [comment] 2021-06-13 03:09
which browser u use? Have the same on firefox latest version 89. Chrome works fine, all graphs ok

**Comment by jenshenk** [comment] 2021-06-13 13:56
Just as extra info: I just got an email notification about browser differences someone posted here, maybe he/she deleted it again in the meantime... in contrast to that comment I do not see graphs for switches either with chrome nor firefox... also not with chrome on android (all tested in incognito/private mode)

**Comment by waltervl** [comment] 2021-06-21 12:00
Some users report an empty switch history. Could this be related too?
https://domoticz.com/forum/viewtopic.php?f=6&t=36522

**Comment by jenshenk** [comment] 2021-06-21 12:54
In my case it was not the history but just the graphs... I could see a list of events but not a visualization of it it, like in the forum link you shared. Cache clearing, different browsers, all the same. 
However, I can share my experience about going back to stable: At the moment it works without any issues since stable and beta seem to share the same database structure now. After the latest beta update the domoticz webserver did not start at all anymore, and without a lot of thinking I just executed the "updatestable" script, crossed my fingers and got lucky. Happy to finally be on stable again now :)
One weird thing about cleaning caches was that on some machines I had to do it multiple times before I could see the before missing graphes on stable.

**Comment by waltervl** [comment] 2021-06-21 13:20
There were indeed some issues lately in beta due to Python Framework changes but those should be solved now.
The other users indeed mentioned the graphs missing in the switch logging.
So if @michahagg could please check this issue too?

**Comment by Netcandy-dev** [comment] 2021-06-24 11:36
Same issue here.
Domoticz 2021.1 (build 13330) using latest official Docker image. Chrome browser.

**Comment by a3vd** [comment] 2021-06-29 13:27
Same issue here with 2021.1 (13330) , devices are showing counts but no graphs

**Comment by marceldbo** [comment] 2021-07-02 17:07
Issue still there with 2021.1 (13358).  Some switch devices not showing Today and Last 7 days history logs. The history table shows the correct values, so the data is there.

**Comment by Eddie-BS** [comment] 2021-07-03 06:37
problem still exists with 13358 here

**Comment by marceldbo** [comment] 2021-07-05 06:47
Thanks for resolving this issue. My switch history Today and Last 7 days history logs are visible again as intended as of version 13360.

**Comment by Claude2666** [comment] 2021-07-05 08:52
I have just upgraded 13360 but for incremental counter, type energy generated or energy, graph page with daily, weekly, .. is still empty.  It seems to work for type counter, but not for type energy and energy generated.

**Comment by laplug** [comment] 2021-07-05 13:42
Same here with build 13360, no graph for General, counter incremental kWh (report section is okay). So I reverted to build 13299.
@michahagg did you find any clues about the cause of the problem? (I couldn't find one)

**Comment by laplug** [comment] 2021-08-10 21:03
The problem is _not_ fixed. Still empty graph Counter Incremental Type Engery and P1 Smart Meter Gas. (Except for the Report graphs.)
I reverted to build 13299.

**Comment by a3vd** [comment] 2021-08-31 11:25
Any progress in solving this issue ? can we help out with logs ?

**Comment by gizmocuz** [comment] 2021-08-31 13:48
If you can write a step by step instruction how to reproduce this (without any hardware, just scripts) it could help debugging.
Or you could help out debugging and make a patch in the code

**Comment by Claude2666** [comment] 2021-08-31 14:41
This is how I reproduce it:

Create a virtual sensor type counter or counter incremental  

Type energy generated
![image](https://user-images.githubusercontent.com/43413877/131520593-2a2e5904-2b98-4b70-9d4e-10d95db09a25.png)

And check log
![image](https://user-images.githubusercontent.com/43413877/131520811-d955f708-ff42-4920-aa1b-7cc421cb130f.png)

It is empty.  

For a counter type counter

![image](https://user-images.githubusercontent.com/43413877/131521193-a7ecba1d-4d10-448a-bb0c-0de5987263f8.png)

In this case the charts are present:

![image](https://user-images.githubusercontent.com/43413877/131521701-c04cfd3e-53ee-44cb-9843-a12fa3f6df2b.png)


Unfortunately my knowledge about how webUI  work is null, so I cannot help to debug.  

I did try the proposed solution in 
https://github.com/domoticz/domoticz/issues/4856

And it made the counter log work, but it had some side effects that the log appeared double in some counter cases.
Also the comparing generated chart has all identical values with the above update.

![image](https://user-images.githubusercontent.com/43413877/131523213-4a0efa60-6cfc-46dd-bba9-eae0162ae193.png)

**Comment by laplug** [comment] 2021-09-01 11:47
I second the above. Additionally, my P1 Smart Meter, Gas does not show graphs logs (except for the report). It is connected via LAN to a YouLess (latest firmware) and was generated by Domoticz after registering the hardware, if I remember correctly.

**Comment by kovainfo** [comment] 2021-09-01 12:13
the problem is here:
`domoticz/www/app/log/DeviceLog.html`

or rather, in this code:

```
     <device-counter-log ng-if = ":: vm.isCounterLog () && vm.isGasDevice ()" device = ":: vm.device" subtype = "'gas'"> </device-counter-log>
     <device-counter-log ng-if = ":: vm.isCounterLog () && vm.isWaterDevice ()" device = ":: vm.device" subtype = "'water'"> </device-counter-log>
     <device-counter-log ng-if = ":: vm.isCounterLog () && vm.isCounterDevice ()" device = ":: vm.device" subtype = "'counter'"> </device-counter-log> 
```

if all of the above is replaced by

`<device-counter-log ng-if = ":: vm.isCounterLog ()" device = ":: vm.device" subtype = "'counter'"> </device-counter-log>`

then the graphs will appear

**Comment by gizmocuz** [comment] 2021-09-01 13:45
@kovainfo , that sounds very correct.... Could you make a PR with this change ?

**Comment by a3vd** [comment] 2021-09-01 17:16
> the problem is here:
> `domoticz/www/app/log/DeviceLog.html`
> 
> or rather, in this code:
> 
> ```
>      <device-counter-log ng-if = ":: vm.isCounterLog () && vm.isGasDevice ()" device = ":: vm.device" subtype = "'gas'"> </device-counter-log>
>      <device-counter-log ng-if = ":: vm.isCounterLog () && vm.isWaterDevice ()" device = ":: vm.device" subtype = "'water'"> </device-counter-log>
>      <device-counter-log ng-if = ":: vm.isCounterLog () && vm.isCounterDevice ()" device = ":: vm.device" subtype = "'counter'"> </device-counter-log> 
> ```
> 
> if all of the above is replaced by
> 
> `<device-counter-log ng-if = ":: vm.isCounterLog ()" device = ":: vm.device" subtype = "'counter'"> </device-counter-log>`
> 
> then the graphs will appear

This fixxes not all for me , now i see the graphs form year results but not day etc  :-(

![2021-09-01_19-14-33](https://user-images.githubusercontent.com/29863575/131714935-f72fe2e1-ecab-4034-80ee-84a2dbe33b93.png)

**Comment by GravityRZ** [comment] 2021-09-01 18:04
i am on 2021.1.13422

i have the same issue as laplug (empty log without windows)
It seems i only have this issue with the dummy counter specified as Energy)
the dummy counter used for water or waterflow seems to work ok.
Also my real energy p1 device  and gas device works normal(RFXCOM)

i did some testing
create dummy counter (default energy):log empty
create dummy counter (default energy):log empty change type to Gas:log windows appear
create dummy counter (default energy):log empty change type to Water:log windows appear
create dummy counter (default energy):log empty change type to Counter:log windows appears
create dummy counter (default energy):log empty change type to energy generated:log empty
create dummy counter (default energy):log empty change type to time generated:log empty

when changing these dummy counters multiple times causes the browser to hang.
this is the reason why i created several new dummy devices and only ched the type once

so the problem looks to be in the dummy energy counters

**Comment by Claude2666** [comment] 2021-09-02 09:58
@a3vd 

With the proposed change, it takes a long time to load the Comparing counter, as it tries to load from year 1 until 2021 for  dummy energy counters

![image](https://user-images.githubusercontent.com/43413877/131823917-bcb9de4a-1afc-44af-b153-4b19ebf46b1a.png)

**Comment by kovainfo** [comment] 2021-09-02 10:21
> i am on 2021.1.13422
> 
> i have the same issue as laplug (empty log without windows)
> It seems i only have this issue with the dummy counter specified as Energy)
> the dummy counter used for water or waterflow seems to work ok.
> Also my real energy p1 device and gas device works normal(RFXCOM)
> 
> i did some testing
> create dummy counter (default energy):log empty
> create dummy counter (default energy):log empty change type to Gas:log windows appear
> create dummy counter (default energy):log empty change type to Water:log windows appear
> create dummy counter (default energy):log empty change type to Counter:log windows appears
> create dummy counter (default energy):log empty change type to energy generated:log empty
> create dummy counter (default energy):log empty change type to time generated:log empty
> 
> when changing these dummy counters multiple times causes the browser to hang.
> this is the reason why i created several new dummy devices and only ched the type once
> 
> so the problem looks to be in the dummy energy counters

no. the problem is in the code that displays the logs (I wrote about this above).
the code only handles 3 devices:
vm.isGasDevice
vm.isWaterDevice ()
vm.isCounterDevice ()

the rest is ignored and does not display logs for them

**Comment by GravityRZ** [comment] 2021-09-02 10:57
ok. clear. maybee dumb question but someone obviously removed the code to display the logs for the missing devices.
if it is just a case of restoring those missing code lines why  has this not been done before(this thread is very long)

**Comment by Claude2666** [comment] 2021-09-02 11:41
I think the problem started when there were some updates/enhancements added for the logs like the yearly compare.

**Comment by GravityRZ** [comment] 2021-09-02 13:29
ok so in the end it is not a big deal with the database because the data is still there . let's patiently wait for a fix.

**Comment by gizmocuz** [comment] 2021-09-02 14:03
@GravityRZ , are you able to make a patch and test this ?

**Comment by kovainfo** [comment] 2021-09-02 14:15
> ok. clear. maybee dumb question but someone obviously removed the code to display the logs for the missing devices.
> if it is just a case of restoring those missing code lines why has this not been done before(this thread is very long)

no, someone replaced a simple one-line code (for any counters) with a custom one for the selected three devices. and I don't understand why, otherwise I would have done a PR

**Comment by GravityRZ** [comment] 2021-09-02 14:22
> @GravityRZ , are you able to make a patch and test this ?

No i am not. i just recently discovered this bug because i hardly look into the log of those 2 dummy energy counters. i only use them to se the instant value.
i would  not know how to solve this

**Comment by Claude2666** [comment] 2021-09-02 14:23
Most likely something missing in the PR:
https://github.com/domoticz/domoticz/pull/4830

**Comment by waltervl** [comment] 2021-09-26 08:32
@michahagg can you please check this issue again, it could have slipped your mind...

**Comment by waltervl** [comment] 2021-09-29 14:42
at all, please check latest beta's as it seems to be fixed by one of the latest charting fixes eg https://github.com/domoticz/domoticz/pull/4943

Edit: I am sorry, I can still reproduce the issue with 13628....

**Comment by a3vd** [comment] 2021-09-29 17:19
It is even getting worse , i lost a lot of my graphs now 👎

**Comment by kovainfo** [comment] 2021-09-29 17:23
> It is even getting worse , i lost a lot of my graphs now 👎

this is an update for the sake of updating, and not for the sake of new functionality (((

@michahagg

**Comment by a3vd** [comment] 2021-09-29 17:26
> > It is even getting worse , i lost a lot of my graphs now 👎
> 
> this is an update for the sake of updating, and not for the sake of new functionality (((
> 
> @michahagg

No functionality you mean !

**Comment by michahagg** [comment] 2021-09-29 18:29
I'm currently restoring the charts for the General Counter Incremental devices. Should be done tomorrow. Sorry for the inconvenience.

**Comment by marceldbo** [comment] 2021-09-29 18:33
Issue with the switch graphs has indeed returned, however the database still has all the data so I will wait patiently for a fix :-)

**Comment by a3vd** [comment] 2021-09-29 18:54
> > > It is even getting worse , i lost a lot of my graphs now 👎
> > 
> > 
> > this is an update for the sake of updating, and not for the sake of new functionality (((
> > @michahagg
> 
> No functionality you mean !

I mean no Graphs , only for Last year and Comparing 

**And yes i did remove the Cache / Cookies etc** 

![2021-09-29_20-51-22](https://user-images.githubusercontent.com/29863575/135330957-36cbe5bf-1b64-44ed-a8ff-3e83b20f2c81.png)
![2021-09-29_20-55-16](https://user-images.githubusercontent.com/29863575/135331374-caf991ba-7648-4150-8df8-15936ae2200f.png)

**Comment by gizmocuz** [comment] 2021-09-30 10:22
@a3vd , I fixed the light on/off chart in beta 13644, my P1 meter is displaying correctly however

**Comment by marceldbo** [comment] 2021-09-30 11:00
Thanks gizmocus, just installed the latest beta and switch graphs work again as they should!

**Comment by laplug** [comment] 2021-09-30 14:04
I just installed build 13647 and the result is the same as my first issue report: [https://github.com/domoticz/domoticz/issues/4856#issue-912460448](url)
The counter Type General, Counter Incremental does not show any graph, except for the Report page.
![image](https://user-images.githubusercontent.com/70644748/135469674-d8052d99-5a33-4515-981c-2033920673e2.png)

To add to the problem: I was unable to revert to build 13299. Domoticz didn't want to start after reverting.
I couldn't find any error messages in the domoticz.log.
It seems I'm now stuck with this version... Very, very unhappy.

**Comment by gizmocuz** [comment] 2021-09-30 14:30
@laplug , what is your forum username ?

**Comment by laplug** [comment] 2021-09-30 14:33
Found the problem!
The device is "Type Energy", but is registered as "Type Counter"
After replacing the device to Type Counter, the graphs show correctly. (Now I have 'only' to adapt the dzVents script...)

Sorry for the inconvenience!!

**Comment by gizmocuz** [comment] 2021-09-30 14:38
@laplug , Maybe a sorry is in order here ? People try to do there best in their free time here !
Also next time, when you update domoticz, there is a FULL backup in your backup folder, including the database, that you can restore (it even hase a date/time)
Another option is to install the domoticz beta as a docker, if it's working, you can update
Even better, install domoticz as a docker, and you can quickly make a backup, update it, and revert it when needed

**Comment by gizmocuz** [comment] 2021-09-30 14:39
@a3vd, are your graphs working again ?

**Comment by a3vd** [comment] 2021-09-30 14:43
> @a3vd , I fixed the light on/off chart in beta 13644, my P1 meter is displaying correctly however

Tnxs, the light/ switch charts are back great but is still have no charts with my P1 / Toon or other custom electra device which i did have before this issue started.

**Comment by a3vd** [comment] 2021-09-30 14:45
> Found the problem! The device is "Type Energy", but is registered as "Type Counter" After replacing the device to Type Counter, the graphs show correctly. (Now I have 'only' to adapt the dzVents script...)
> 
> Sorry for the inconvenience!!

Where can i find the type which is used maybe this is an issue with my problem also.

**Comment by laplug** [comment] 2021-09-30 14:56
> Where can i find the type which is used maybe this is an issue with my problem also.

You can find it on the panel (In my case I named it "Tesy usage today", probably on the Utilities tab [
![image](https://user-images.githubusercontent.com/70644748/135478939-a90c3c43-f360-4015-bca1-affe56bfc416.png)
](url)
It turns out it is possible to have a "Type General, Counter incremental" while the device has Type Energy (click on 'Edit' and check what type is selected).
[
![image](https://user-images.githubusercontent.com/70644748/135469674-d8052d99-5a33-4515-981c-2033920673e2.png)
](url)

**Comment by waltervl** [comment] 2021-09-30 16:57
> i am on 2021.1.13422
> i did some testing:
> **create dummy counter (default energy):log empty** 
> change type to Gas:log windows appear 
> change type to Water:log windows appear 
> change type to Counter:log windows appears 
> **change type to energy generated:log empty** 


Just did same testing in 2021.1 build 13644 and still have the same results.
P1 (Gas and Electricity) and Electricity (Instant and Counter) are working fine.

**Comment by a3vd** [comment] 2021-09-30 16:59
> > Where can i find the type which is used maybe this is an issue with my problem also.
> 
> You can find it on the panel (In my case I named it "Tesy usage today", probably on the Utilities tab [ ![image](https://user-images.githubusercontent.com/70644748/135478939-a90c3c43-f360-4015-bca1-affe56bfc416.png) ](url) It turns out it is possible to have a "Type General, Counter incremental" while the device has Type Energy (click on 'Edit' and check what type is selected). [ ![image](https://user-images.githubusercontent.com/70644748/135469674-d8052d99-5a33-4515-981c-2033920673e2.png) ](url)

Tnxs fount it and they are all type general count, all without a graph

**Comment by nielswest65** [comment] 2021-09-30 19:02
Hi,

considering myself a Newbie , reading al above, i tried changing the devicelog.html. this did not work. However tryng Edge instead of Chrome. I had my Gas Graph back. Using 
Version: 2021.1 (build 13644)
Build Hash: 5a0fc8319
Compile Date: 2021-09-30 11:32:03
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

**Comment by waltervl** [comment] 2021-09-30 19:07
> Hi,
> 
> considering myself a Newbie , reading al above, i tried changing the devicelog.html. this did not work. However tryng Edge instead of Chrome. I had my Gas Graph back. Using Version: 2021.1 (build 13644) Build Hash: [5a0fc83](https://github.com/domoticz/domoticz/commit/5a0fc8319437408721d872c9897d0442faf3df61) Compile Date: 2021-09-30 11:32:03 dzVents Version: 3.1.8 Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]


This seems to be a newbie mistake: clear browser cache after an update. :-)

**Comment by nielswest65** [comment] 2021-09-30 19:24
> > Hi,
> > considering myself a Newbie , reading al above, i tried changing the devicelog.html. this did not work. However tryng Edge instead of Chrome. I had my Gas Graph back. Using Version: 2021.1 (build 13644) Build Hash: [5a0fc83](https://github.com/domoticz/domoticz/commit/5a0fc8319437408721d872c9897d0442faf3df61) Compile Date: 2021-09-30 11:32:03 dzVents Version: 3.1.8 Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
> 
> This seems to be a newbie mistake: clear browser cache after an update. :-)

I realy do need to learn a lot :-) thanks it worked.

**Comment by laplug** [comment] 2021-09-30 22:08
> > i am on 2021.1.13422
> > i did some testing:
> > **create dummy counter (default energy):log empty**
> > change type to Gas:log windows appear
> > change type to Water:log windows appear
> > change type to Counter:log windows appears
> > **change type to energy generated:log empty**
> 
> Just did same testing in 2021.1 build 13644 and still have the same results. P1 (Gas and Electricity) and Electricity (Instant and Counter) are working fine.

This is the same for me: Dummy Type General Counter incremental, default Energy.

So, we pinned the problem to those devices? (Using Dummy Type Counter works fine and I have no problems with P1 devices.)
Maybe the default Dummy Type General Counter incremental, default Energy wasn't added to the update by @michahagg ?

The DeviceLog.htm lists subtype p1Energy, but not Energy. Is that the problem?

`    <device-text-log ng-if="::vm.isTextLog()" device-idx="::vm.deviceIdx"></device-text-log>
    <device-light-log ng-if="::vm.isLightLog()" device-idx="::vm.deviceIdx"></device-light-log>
    <device-temperature-log ng-if="::vm.isTemperatureLog()" device="::vm.device"></device-temperature-log>
    <device-graph-log ng-if="::vm.isGraphLog()" device="::vm.device"></device-graph-log>
    <device-counter-log ng-if="::vm.isInstantAndCounterLog()" device="::vm.device" subtype="'instantAndCounter'"></device-counter-log>
    <device-counter-log ng-if="::vm.isP1EnergyLog()" device="::vm.device" subtype="'p1Energy'"></device-counter-log>
    <device-counter-log ng-if="::vm.isCounterLog() && vm.isGasDevice()" device="::vm.device" subtype="'gas'"></device-counter-log>
    <device-counter-log ng-if="::vm.isCounterLog() && vm.isWaterDevice()" device="::vm.device" subtype="'water'"></device-counter-log>
    <device-counter-log ng-if="::vm.isCounterLog() && vm.isCounterDevice()" device="::vm.device" subtype="'counter'"></device-counter-log>
`

**Comment by waltervl** [comment] 2021-10-01 09:10
PR https://github.com/domoticz/domoticz/pull/4950 created yesterday by @michahagg  to solve this issue, Thanks! Now wait until it is merged in a beta release....

**Comment by gizmocuz** [comment] 2021-10-01 12:18
It's merged

**Comment by Claude2666** [comment] 2021-10-01 12:39
I have just loaded the latest beta, and indeed now the logs for energy generated are shown. Great job. Thank you.

Just one small glitch, the comparing generated table has all the same values. 
![Compare](https://user-images.githubusercontent.com/43413877/135620426-c7240709-cfdb-47dc-8909-cf53429d91cf.png)

**Comment by michahagg** [comment] 2021-10-01 20:16
Hi @Claude2666 good to hear the charts are working now. Except for the Comparing chart, as you say. The chart mainly uses the Counter values from the Meter_Calendar table. Could you make an export of the records with the device-id?

`select * from Meter_Calendar where DeviceRowID=<device-id> order by Date desc`

Thanks

**Comment by laplug** [comment] 2021-10-01 20:16
> I have just loaded the latest beta, and indeed now the logs for energy generated are shown. Great job. Thank you.

Same for me: now the graphs are visible. (no glitches)
Thank you @michahagg and others for contributing.

**Comment by Claude2666** [comment] 2021-10-02 04:38
@michahagg Here are the counters:
[SolarProduction.txt](https://github.com/domoticz/domoticz/files/7270870/SolarProduction.txt)

And this is how the counter is configured in Domoticz:
![image](https://user-images.githubusercontent.com/43413877/135703696-68eb6333-db43-457c-aa5c-901a794303ce.png)


Thanks for looking into this.

**Comment by michahagg** [comment] 2021-10-02 19:00
Hi @Claude2666 thanks for the data. The data but mostly the device configuration was what actually helped me solve the problem. :-) It calculates the values by taking the differences between all counters. There is no need to adjust the values with the Meter Offset.
It is fixed with PR #4954 .

**Comment by gizmocuz** [comment] 2021-10-03 09:15
Sorry issue closed itself after applying the PR.
New beta available now (13680)

Hope all is OK and this issue can be closed

**Comment by Claude2666** [comment] 2021-10-03 09:20
I just loaded (build 13680 and I can confirm that all counter logs that I use are all working fine.  
@michahagg  Thank you so much for your work on the logs.  I find the log graphs one excellent features that Domoticz has.

**Comment by michahagg** [comment] 2021-10-03 09:44
Great! 
I agree with you on the excellent graphs in Domoticz! :-) The praise for that goes to @gizmocuz , @stas-demydiuk and someone named Erik! From the git history it looks like they did all the creative work on the charts! 🥇
I just humbly refactored the code to make it a little bit more extendible.

**Comment by waltervl** [comment] 2021-11-25 16:06
There is still a (perhaps unrelated) issue that on the report page for this counter device:
1. the Unit of measure is not mentioned, 
2. sometimes 3 decimals are added, 
3. and the counter is marked as NaN (not a number).
https://domoticz.com/forum/viewtopic.php?p=282885#p282885

![image](https://user-images.githubusercontent.com/16327072/143473465-41b15abb-bf38-45b9-816a-c3ddfcc2dd69.png)

**Comment by gizmocuz** [comment] 2022-01-09 15:35
@waltervl , that is indeed unrelated to the graphs.
I am not using this type of counter, but if you can send me a database with this counter, or some steps/json calls to create/fill one, I'm happy to test.
But you might also look at the c++/html code

**Comment by waltervl** [comment] 2022-01-10 18:55
I have created a new issue and will upload a test database for it.
This issue can be closed. Should be solved with pr 4954 as mentioned before.

**Closed as completed** 2022-01-11 07:46 UTC
