### ISSUE TITLE
b64DecodeUnicode is not defined

### ISSUE THREAD

**Issue by mzealey** [domoticz/domoticz#4321] opened 2020-09-05 18:32 UTC
https://github.com/domoticz/domoticz/blob/fbade6811a5b22e953e0bfcdb7dcd06943443be2/www/app/DeviceLightEdit.js#L513

When trying to change the symbol for a switch I get the following error:

```
ReferenceError: b64DecodeUnicode is not defined
    at DeviceLightEdit.js:513
    at angular.min.js:137
    at m.$digest (angular.min.js:148)
    at m.$apply (angular.min.js:151)
    at l (angular.min.js:103)
    at t (angular.min.js:108)
    at XMLHttpRequest.A.onload (angular.min.js:109) "Possibly unhandled rejection: {}"
```

**Comment by gizmocuz** [comment] 2020-09-06 10:52
@mzealey , Could you tell us what version of Domoticz you have, and what hardware type/subtype the switch is ?

**Comment by mzealey** [comment] 2020-09-06 11:51
domoticz v2020.2 , these are virtual switches. Taking the code from https://github.com/domoticz/domoticz/blob/2aae3498ec135bdf3468f2878aef9b4bd7600a64/www/js/domoticz.js#L77 and pasting it into devtool window fixes the issue so i guess this not being included somehow?

**Comment by gizmocuz** [comment] 2020-09-06 12:20
@mzealey , Sorry it is a bit unclear for me what the problem is.
You talk about b64DecodeUnicode , but on line 77 is the encode (b64EncodeUnicode)

You added a virtual switch to the system (Dummy hardware)
Then you pressed edit on the switch (from the switches tab), and you want to change the icon to something else

And this is not working ?

**Comment by mzealey** [comment] 2020-09-07 08:12
Yes, both b64DecodeUnicode & b64EncodeUnicode appear to be undefined (have refreshed cache etc to ensure its not old scripts hanging around) and this is meaning that hitting the save button never sends anything to the server. Manually pasting the code for them into the console fixes the issue.

**Comment by mzealey** [comment] 2020-09-07 12:38
OK for some reason domoticz.js was correct but domoticz.js.gz was not correct. I guess you removed some of the .gz files in a previous build but because they were not being removed via the updaterelease script they stay there and get served when chrome requests the compressed version of scripts.

**Comment by mzealey** [comment] 2020-09-07 12:47
(note to fix I did `find -name \*.js.gz -delete` and then `./updaterelease`. But presumably there should be something changed in the release updater to remove files which are no longer used?

**Comment by gizmocuz** [comment] 2020-09-07 14:15
@mzealey , yes that happened indeed a very long time ago.
Some files are not packed anymore (like domoticz.js.gz)
Your fix is indeed the correct way

**Closed as completed by gizmocuz** 2020-09-07 14:15 UTC
