### ISSUE TITLE
Set-Cookie different path

### ISSUE THREAD

**Issue by dongo11** [domoticz/domoticz#4796] opened 2021-04-21 20:03 UTC
Hello

I found a problem.
Login also has a cookie setting and logout also sets one. But one does not specify a path. This causes an error as it does not overwrite the logout on the client side so it cannot be logged in again.
The error occurs when you access through a proxy and not root uri.
I suggest remove set path.
The error is in cWebem.cpp

		void cWebemRequestHandler::send_remove_cookie(reply& rep)
		{
			std::stringstream sstr;
			sstr << "DMZSID=none";
			// RK, we removed path=/ so you can be logged in to two Domoticz's at the same time on https://my.domoticz.com/.
			sstr << "; HttpOnly; Expires=" << make_web_time(0);
			reply::add_header(&rep, "Set-Cookie", sstr.str(), false);
		}

		void cWebemRequestHandler::send_cookie(reply& rep, const WebEmSession & session)
		{
			std::stringstream sstr;
			sstr << "DMZSID=" << session.id << "_" << session.auth_token << "." << session.expires;
			sstr << "; HttpOnly; path=/; Expires=" << make_web_time(session.expires);
			reply::add_header(&rep, "Set-Cookie", sstr.str(), false);
		}

**Comment by kiddigital** [comment] 2021-04-22 05:20
Hi @dongo11 , can you supply some more info on how you have setup the proxy you use and some example(s) on how to reproduce your issue?

There is a PR (#4729) that add JWT support and also does some cleanup of the authorisation/cookie code, so I like to check if this also solves your problem or that I can fix it there as well.

Btw.. a client using JWT should make things easier to work behind proxies as the cookie is not needed anymore.

**Comment by dongo11** [comment] 2021-04-22 08:19
Hello

I have a server that has an NGINX server. There are several applications behind this, under different URIs.
Domoticz can be found, for example, at www.xx.com/domot/. There was no problem with this until the last update

Now I had two problems.
First: the application cache (sometimes did not follow the root link)
I simply turned this off (removed the manifest information in HTML)

The second, and what could only go with code modification, is cookie handling.
My domoticz instance  is user dependent. I have more users
The proxy was configured to pass the real ip and in domoticz I configured the Proxy ip.
     

-  That's why you're asking for login (good)

- A cookie is created after logging in (path: /)

- Works after login and then logout.

Here is the problem, because now another cookie (path: / domot) is created (content: none) and the other one exists.
(The goal would have been to delete the contents of the first coookie, but since it doesn't have the same path, it remains)

- After that if I want to log in again and it doesn't go. Not because it validates the first cookie, but it is no valid.

- I can only login if I manually delete the first cookie.

setup: 
location /domot {
               rewrite ^/domot/?(.*) /$1 break;
               proxy_http_version		1.1;
			   proxy_no_cache 1;
			   proxy_cache_bypass 1;
               proxy_read_timeout		90;
               proxy_set_header        Host $host;
               proxy_set_header        X-Real-IP $remote_addr;
               proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header        X-Forwarded_Proto $scheme;
               proxy_set_header		X-Scheme $scheme;
               proxy_set_header		Upgrade $http_upgrade;
               proxy_set_header		Connection $connection_upgrade;
               add_header				X-Frame-Options SAMEORIGIN;
               proxy_pass https://xx.xx.xx.xx:1443;
       }

RemoteProxyIPs:  127.0.0.1;xx.xx.xx.xx

**Comment by gizmocuz** [comment] 2021-04-22 11:39
Domoticz and the NGINX proxy runs on the same machine ? So proxy_pass is also https://127.0.0.1:1443; ?

All seems good as this also follows the recommendation in this guide

https://www.domoticz.com/wiki/WebServer_Proxy

Has been working forever

**Comment by dongo11** [comment] 2021-04-22 14:06
"Domoticz and the NGINX proxy runs on the same machine ?"  : yes
So proxy_pass is also https://127.0.0.1:1443; ? : No, because domoticz bind in local IP
machine have some IPs

```
void cWebemRequestHandler::send_cookie(reply& rep, const WebEmSession & session)
	{
		std::stringstream sstr;
		sstr << "DMZSID=" << session.id << "_" << session.auth_token << "." << session.expires;
	//	sstr << "; HttpOnly; path=/; Expires=" << make_web_time(session.expires);
	        sstr << "; HttpOnly; Expires=" << make_web_time(session.expires);             // Does this not solve the problem?
		reply::add_header(&rep, "Set-Cookie", sstr.str(), false);
	}
```

**Comment by kiddigital** [comment] 2022-12-28 14:22
@dongo11 , does this issue still exist? Please test with the latest Beta as they have significant changes in security and proxy handling.

**Comment by waltervl** [comment] 2023-05-02 07:04
Close this due to missing feedback

**Closed as completed by waltervl** 2023-05-02 07:04 UTC
Labels: PendingFeedback
