### ISSUE TITLE
Python Framework - PyO3 modules may only be initialized once per interpreter process

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#5717] opened 2023-06-13 10:53 UTC
It happens that a Python module is initialized more than once when doing plugin Stop / Start. 

This has been discussed in the [Domoticz forum](https://www.domoticz.com/forum/viewtopic.php?p=303514)

In addition,  from https://github.com/PyO3/pyo3/blob/7bdc504252a2f972ba3490c44249b202a4ce6180/guide/src/migration.md#each-pymodule-can-now-only-be-initialized-once-per-process that this is new behavior as of the 28 August release of 0.17 but it's not clear from that writeup what 'the ability to initialize a #[pymodule] more than once in the same process' means

In the domoticz forum , there is a very simple python3 plugin to duplicate the error

**Comment by d-EScape** [comment] 2023-08-03 05:33
Since Domoticz 2023.2 I see the same behavior with my plugin https://github.com/d-EScape/Domoticz_iDetect.
I'm running on Debian bullseye with python 3.9.2 in a docker container.

**Comment by d-EScape** [comment] 2023-08-19 10:24
Done some more testing. It looks like this might be a more generic issue. 

Whenever I restart a plugin that imports other (third party?) modules it leads to different errors for different modules, but it is reproducible. The imported modules don't even have to be used, just imported.

1. Install the officiel Docker/Docker:latest
2. Add the plugin.py (code below)
3. Choose a module to import (one at a time)
4. pip install the modules to be imported (use my examples or try others)
5. Start Domoticz and add the plugin as hardware
6. Restart Domoticz container (just to start fresh)
7. Update the Hardware with the update button and see what happens
8. repeat for different modules

My results:
- No problem with DomoticzEx, random or string module
- fritzconnection.FritzConnection > SystemError: initialization of md__mypyc did not return an extension module
- fritzconnection.lib.fritzwlan.FritzWLAN > Fatal Python error: Segmentation fault
- paramiko > ImportError: PyO3 modules may only be initialized once per interpreter process (as in original post)
- requests > Fatal Python error: Segmentation fault

The test plugin is nearly empty, so I don't see anything we can do about this by changing the plugins themselves. Can this be fixed in Domoticz/the plugin framework?

```
"""
<plugin key="testthing" name="Python Plugin Tester">
	<description>
		<h2>Test Python plugin framework</h2><br/>
	</description>
</plugin>
"""

import DomoticzEx
import random
import string

# from fritzconnection import FritzConnection # plugin restart (update) leads to >> SystemError: initialization of md__mypyc did not return an extension module
from fritzconnection.lib.fritzwlan import FritzWLAN # plugin restart (update) leads to >> Fatal Python error: Segmentation fault

# import paramiko # plugin restart (update) leads to >> ImportError: PyO3 modules may only be initialized once per interpreter process
# import requests # plugin restart (update) leads to >> Fatal Python error: Segmentation fault

def randomname():
    letters = string.ascii_lowercase
    return ''.join(random.choice(letters) for i in range(10))

class BasePlugin:

	def __init__(self):
		print("Initializing plugin tester")
		
	def onStart(self):
		if not "deviceA" in Devices:
			DomoticzEx.Unit(Name="First Device", Unit=1, DeviceID="deviceA", TypeName="Switch", Used=1).Create()
		if not "deviceB" in Devices:
			DomoticzEx.Unit(Name="Second Device", Unit=5, DeviceID="deviceB", TypeName="Switch", Used=1).Create()
# 		devname=randomname()
# 		DomoticzEx.Log("Creating:" + devname)
# 		DomoticzEx.Unit(Name=devname, Unit=1, DeviceID=devname, TypeName="Switch", Used=1).Create()
		DomoticzEx.Log("<<<<< onstart completed >>>>>")
		
	def onStop(self):
		DomoticzEx.Log("<<<<<<onstop>>>>>>")
		for d in Devices:
			DomoticzEx.Status('>> ' + str(d))
		DomoticzEx.Log("<<<<<<onstop completed>>>>>>")

global _plugin
_plugin = BasePlugin()

def onStart():
	global _plugin
	_plugin.onStart()
	
def onStop():
	global _plugin
	_plugin.onStop()
```

**Comment by gizmocuz** [comment] 2024-01-12 15:18
Is this still an issue?

**Comment by pipiche38** [comment] 2024-01-13 07:27
That is an issue for some python libs.

**Closed as completed** 2024-01-13 07:27 UTC

**Comment by d-EScape** [comment] 2024-01-15 16:52
Since this issue is marked as completed, but the problem still exists in build 15840, I would like to add some findings...

Looks like @pipiche38 is essentially right. It is an issue for some python libs. The question remains if the issue can be avoided by the plugin framework(?) Maybe by changing the way plugins are stopped or further separating the plugins from each other? I don't know, because this is way beyond my knowledge and skills. 

As far as I can tell (and I'm certainly no expert!): the affected python modules all seem to (directly or indirectly) use the cryptography module, which uses pyO3.

The changelog for version 0.17 (august 2022) of pyO3 shows:
```
Each #[pymodule] can now only be initialized once per process

To make PyO3 modules sound in the presence of Python sub-interpreters, for now it has been necessary to explicitly disable the ability to initialize a #[pymodule] more than once in the same process. Attempting to do this will now raise an ImportError.
```
source [https://pyo3.rs/main/migration.html](url)

This issue seems to be related:
[https://github.com/PyO3/pyo3/issues/3451](url)
