### ISSUE TITLE
Warning! Domoticz 4.10988 and higher incorporate an important OpenZWave update and re-interviews devices

### ISSUE THREAD

**Issue by petergebruers** [domoticz/domoticz#3530] opened 2019-07-13 09:45 UTC
OpenZWave Contributor here. This is not an issue, it is a warning. I've tried to send this info via private channel prior to release but that did not work, so I'll post it as an issue here and refer to it when needed...

A while ago a crash in OZW 1.6 was identified, affecting certain multilevel devices. A fix for that was tested on the OZW Dev branch and got merged, then incorporated into Domoticz Beta > 4.10988. This should be good news but there is always the possibility that it introduces problems. It should improve compatibility of devices, but there are simply too many to test.

One thing that is important to know is that this update will automatically "regenerate" your ozwcache file. It does that by looking at the "version" tag of your file. If it is < 4 then all devices will be re-interviewed. This is necessary to get the correct information.

This means battery devices won't be identified until they wake up (automatically based on wake up interval, or when you perform the right kind of clicks on a button on the device). Until that happens they will have no name and ID will be 0x0000.

As soon as you run this version, the first line of your ozwcache_* file will be updated to:

```
<Driver xmlns="https://github.com/OpenZWave/open-zwave" version="4"
```

If you have debug logging enable there will be a Warning in the OZW_Log.txt as well but by default Domoticz only logs Errors.

If you suspect an issue, please start a separate issue, don't post it here, I'd like to keep this for general information.

If you want to know what it actually does, this is the commit message:

"Originally, OZW would get the CC Version information much later in the interview cycle, but this was often too late for some classes that create ValueID's based on the version implemented by the device. The result was that after adding a device, the CC might be missing Values that are needed. This in particular was causing a crash in the SwitchMultiLevel, as we didn't create several Values during the creation of the CC, as we didn't have updated version information.

With this change, the interview orders have changed around a bit, and we also take the chance to do more interviewing of "static" information to save bootup times later on when reading from ozwcache."

**Comment by petergebruers** [comment] 2019-07-13 09:59
Based on user feedback, reverting to v4.10982 for now seems like the fastest way to solve this in production.

**Comment by petergebruers** [comment] 2019-07-13 11:25
If your node has multiple relays, but only shows one in ozwcp or only one works in Domoticz: the problem has been reported to OpenZWave and is under investigation.

**Comment by GravityRZ** [comment] 2019-07-13 11:59
checked my config files but do not see this line added
`<Driver xmlns="https://github.com/OpenZWave/open-zwave" version="4"`
is it in de config device files

i am running 993(without problems sofar)

**Comment by petergebruers** [comment] 2019-07-13 12:29
> checked my config files but do not see this line added

Sorry for the confusion, I've updated my post. The line mentioned is the first or second line in your ozwcache_*
Yes, the cache file has a version number too! And for years it has been version 3 but with this beta it is 4.

> i am running 993(without problems sofar)

Good. But maybe check nodes with eg multiple relays, if you can see and control all relays.

**Comment by TerrorSource** [comment] 2019-07-13 17:15
> Based on user feedback, reverting to v4.10982 for now seems like the fastest way to solve this in production.

Reverting back to the latest stable version of Domoticz (with importing the db file) doesnt work. Domoticz starts but wont load webpage.

I now returned to the latest beta 4.10997.
Only thing that doesnt work for me right now is having multi-relay switches like Fibaro Walli Double Switch and Neo CoolCam Wall Switch 2CH.
Any way to get that fixed manually?

**Comment by Ittiz** [comment] 2019-07-13 20:24
I have one switch with multiple relays and it has the issue.  I went so far as to re-enroll it and the issue wasn't fixed.  Good to know the issue is being looked into

**Comment by petergebruers** [comment] 2019-07-14 07:33
Hi for *those users building Domoticz + OpenZWave from source* for the time being the change to the interview order has been reverted, this is the first version without that change: OpenZWave Version 1.6-841-g85d47e56. The interview order (fix for certain multilevel switches) commit will be re-investigated (and probably re-introduced in a fixed or modified form)...

**Comment by GravityRZ** [comment] 2019-07-14 08:35
i am on Version: 1.6-838-g89433f08-dirty (build 993) and do not have any problems.
when i go to  a newer build (998) with the reverted openzwave, what problems will be intruduced again

1 the multi level switch crash
2 the OpenZWave: Value_Changed: Tried adding value, not succeeded! message.

if both stay gone i will be hapy to upgradew, otherwise it might be best to stick with build 993(no errors and crashes for me)

**Comment by gizmocuz** [comment] 2019-07-14 09:47
version 11005 has the reverted OZW code

**Comment by petergebruers** [comment] 2019-07-14 17:38
> if both stay gone i will be hapy to upgradew, otherwise it might be best to stick with build 993(no errors and crashes for me)

I recommend to stay on 993, the problem with the merge has been identified and OZW will re-introduce the fix for the interview... It is a bit hard to give ETA (we're volunteers). I'll post a note here when that happens.

**Comment by GravityRZ** [comment] 2019-07-14 18:58
Thanks. tried 998 today and that one is save also.
bummer that the fix works out great for me but not for others.

hopefully we get to the bottom of this.


> > if both stay gone i will be hapy to upgradew, otherwise it might be best to stick with build 993(no errors and crashes for me)
> 
> I recommend to stay on 993, the problem with the merge has been identified and OZW will re-introduce the fix for the interview... It is a bit hard to give ETA (we're volunteers). I'll post a note here when that happens.

**Comment by waltervl** [comment] 2022-02-12 22:56
Issue can be closed

**Closed as completed** 2022-02-13 08:51 UTC
