### ISSUE TITLE
Domoticz crashes immediately after start v10917 - OpenZWave: Unhandled value type: 1, OpenZWave.cpp:1689

### ISSUE THREAD

**Issue by nixalsschrott** [domoticz/domoticz#3344] opened 2019-06-22 22:03 UTC
Dear team,

actually switched to beta 10917 and now Domoticz crashes several seconds after startup.
Running on Synology NAS (by the way - on beta 10806 system was running quite stable).
Or domoticz crashes when I activate a multilevel switch  - eg Qubino shutter switch.

Added detailed log attachement for better investigation.

[domoticz.log](https://github.com/domoticz/domoticz/files/3326954/domoticz.log)

**Comment by GravityRZ** [comment] 2019-06-27 20:12
i think i have this same problem
also runnig synology platform and build by jumbotroll


build 891 with zwave Version: 1.6-748-g339d53d7-dirty runs without problems

later versions like 921 and 929 give this error and crashes
`2019-06-26 17:10:48.748 Error: OpenZWave: Unhandled Meter type: Power, class: 0x32 (METER), NodeID: 8 (0x08), Index: 8, Instance: 1
2019-06-26 17:10:48.749 Error: OpenZWave: Unhandled value type: 1, OpenZWave.cpp:1689
2019-06-26 17:10:48.751 Error: OpenZWave: Unhandled Meter type: Power, class: 0x32 (METER), NodeID: 11 (0x0b), Index: 8, Instance: 1
2019-06-26 17:10:48.751 Error: OpenZWave: Unhandled value type: 1, OpenZWave.cpp:1689
2019-06-26 17:10:48.751 Error: OpenZWave: Unhandled value type: 1, OpenZWave.cpp:1689
2019-06-26 17:10:48.751 Error: OpenZWave: Unhandled value type: 1, OpenZWave.cpp:1689
2019-06-26 17:10:48.751 Error: OpenZWave: Unhandled value type: 1, OpenZWave.cpp:1689
2019-06-26 17:10:48.754 Error: OpenZWave: Unhandled value type: 1, OpenZWave.cpp:1689
2019-06-26 17:10:48.754 Error: OpenZWave: Unhandled value type: 1, OpenZWave.cpp:1689
2019-06-26 17:10:48.755 Error: OpenZWave: Unhandled Meter type: Power, class: 0x32 (METER), NodeID: 17 (0x11), Index: 8, Instance: 1
2019-06-26 17:10:48.755 Error: OpenZWave: Unhandled value type: 1, OpenZWave.cpp:1689
2019-06-26 17:10:48.756 Error: OpenZWave: Unhandled Meter type: Power, class: 0x32 (METER), NodeID: 18 (0x12), Index: 8, Instance: 1
2019-06-26 17:10:48.756 Error: OpenZWave: Unhandled value type: 1, OpenZWave.cpp:1689




2019-06-26 17:11:13.711  Error: Domoticz(pid:19392, tid:19711('OZW-driver')) received fatal signal 11 (Segmentation fault)
2019-06-26 17:11:13.711  Error: siginfo address=0xfffffffffffffff8, address=0xb63d56
2019-06-26 17:11:13.719  Error: Failed to start gdb, will use backtrace() for printing stack frame

2019-06-26 17:11:13.722  Error: #0  /usr/local/domoticz/bin/domoticz() [0x552d80]
2019-06-26 17:11:13.722  Error: #1  /usr/local/domoticz/bin/domoticz() [0x553ae5]
2019-06-26 17:11:13.722  Error: #2  /lib/libpthread.so.0 :  + 0x101c0 [0x7fc324fd51c0]
2019-06-26 17:11:13.722  Error: #3  /usr/local/domoticz/bin/domoticz : std::string::_Rep::_M_dispose(std::allocator<char> const&) + 0x16 [0xb63d56]
2019-06-26 17:11:13.723  Error: #4  /usr/local/domoticz/bin/domoticz : std::string::assign(std::string const&) + 0x3b [0xb64905]
2019-06-26 17:11:13.723  Error: #5  /usr/local/domoticz/lib/libopenzwave.so.1.6 : OpenZWave::Internal::CC::Meter::HandleReport(unsigned char const*, unsigned int, unsigned int) + 0x1ca [0x7fc32547e89a]
2019-06-26 17:11:13.723  Error: #6  /usr/local/domoticz/lib/libopenzwave.so.1.6 : OpenZWave::Internal::CC::MultiInstance::HandleMultiChannelEncap(unsigned char const*, unsigned int) + 0x12f [0x7fc32548277f]
2019-06-26 17:11:13.723  Error: #7  /usr/local/domoticz/lib/libopenzwave.so.1.6 : OpenZWave::Internal::CC::MultiInstance::HandleMsg(unsigned char const*, unsigned int, unsigned int) + 0x4e [0x7fc32548390e]
2019-06-26 17:11:13.723  Error: #8  /usr/local/domoticz/lib/libopenzwave.so.1.6 : OpenZWave::Node::ApplicationCommandHandler(unsigned char const*, bool) + 0x125 [0x7fc3255392e5]
2019-06-26 17:11:13.723  Error: #9  /usr/local/domoticz/lib/libopenzwave.so.1.6 : OpenZWave::Driver::ProcessMsg(unsigned char*, unsigned char) + 0x3d9 [0x7fc3254fb719]
2019-06-26 17:11:13.723  Error: #10 /usr/local/domoticz/lib/libopenzwave.so.1.6 : OpenZWave::Driver::ReadMsg() + 0x71c [0x7fc3254fca9c]
2019-06-26 17:11:13.723  Error: #11 /usr/local/domoticz/lib/libopenzwave.so.1.6 : OpenZWave::Driver::DriverThreadProc(OpenZWave::Internal::Platform::Event*) + 0x468 [0x7fc3254fe8e8]
2019-06-26 17:11:13.723  Error: #12 /usr/local/domoticz/lib/libopenzwave.so.1.6 : OpenZWave::Internal::Platform::ThreadImpl::Run() + 0x13 [0x7fc3254e2893]
2019-06-26 17:11:13.723  Error: #13 /usr/local/domoticz/lib/libopenzwave.so.1.6 : OpenZWave::Internal::Platform::ThreadImpl::ThreadProc(void*) + 0x9 [0x7fc3254e28a9]
2019-06-26 17:11:13.723  Error: #14 /lib/libpthread.so.0 :  + 0x72c4 [0x7fc324fcc2c4]
2019-06-26 17:11:13.723  Error: #15 /lib/libc.so.6 : clone + 0x6d [0x7fc32437c10d]`

**Comment by petergebruers** [comment] 2019-06-27 20:28
Those are 2 unrelated bugs.

@nixalsschrott 

A fix for a crash with some "Mutlilevel Switch" devices like Roller Shutters has been available for a while on the Dev branch of OpenZWave.

@GravityRZ 
The "Meter" crash fix has been very recently merged into OpenZWave master, and it is also on the Dev branch.

You'll want both fixes but "Dev" has not been merged yet. We're still waiting to get more feedback on the "Dev" branch so you can help us. But please follow these instructions.

In Domoticz: enable debug logging on the OpenZWave controller.

Stop Domoticz.

Make a backup of Domoticz... database, scripts, config files, ...

Follow the Domoticz wiki to build from source. Check out the "Dev" branch of OpenZWave.

If you already had this "build from source setup" going then please do a "make clean" in the OZW repo. Also use latest commit of Domoticz repo. Then "make" OZW and then "make" Domoticz.

You'll need to re-interview all devices to properly test the Dev branch of OpenZWave.

To force interview, delete ozwcache_* file in your Config folder.

This means you'll have to wake up all sleeping nodes. How many nodes do you have and how many are battery operated? You'll have to judge, if it is doable to wake them up manually or if you can wait until they wake up at their set interval.

Then start Domoticz and please provide a full OZW_Log.txt from the start, this is important because the issue was caused by the order of commands issued during the interview.

If it crashes, drag and drop the OZW_Log.txt, ozwcache* and the Domoticz stack trace here as files.

**Comment by GravityRZ** [comment] 2019-06-28 08:01
@petergebruers
i got a new build from Jumbotroll so i will try this(to provide you with logs). one question where can i find the domoticz stack trace file?
how is it generated?
i am not able to compile or build things, i just use the build from jumbotroll

**Comment by nixalsschrott** [comment] 2019-06-28 08:38
@GravityRZ 
Where did you get the build from jumbotroll? I still see 6.2_4.0.10917-8.spk for all architectures.
I need package for apollolake.
Normally jumbotroll uses beta branch and not dev branch as I know.

**Comment by GravityRZ** [comment] 2019-06-28 08:41
i got it from his site

935 is up there for apollolae but as you mention it this might be indeed beta branch and not dev branche.

however jumbotroll can make a build with a specific open zwave library which he did in this case.

**Comment by nixalsschrott** [comment] 2019-06-28 08:50
Link missing ....

**Comment by GravityRZ** [comment] 2019-06-28 09:39
http://www.jadahl.com/domoticz_beta_6.2/?arch=apollolake

**Comment by nixalsschrott** [comment] 2019-06-28 10:09
OK. now I see - I am using package with python - that’s not finished yet.

**Comment by GravityRZ** [comment] 2019-06-29 18:09
i did the following
enabled logging in aeotec zwave device
stopped domoticz
removed log and cache files
upgraded domoticz to 735
started it.

running without problems now
i have added the logs but the problem is not there anymore
i suspect that when openzwave versions increase there might be problems when you do  an upgrade on a running version
Jumbotroll did a clean install but aparently stopping it and removing the cache files will solve problems


[OZW_Log.txt](https://github.com/domoticz/domoticz/files/3342169/OZW_Log.txt)

**Comment by GravityRZ** [comment] 2019-06-29 18:09
[ozwcache_0xcea80b03.txt](https://github.com/domoticz/domoticz/files/3342170/ozwcache_0xcea80b03.txt)

**Comment by petergebruers** [comment] 2019-06-29 18:18
> aparently stopping it and removing the cache files will solve problems

Correct. Some fixes need a "refresh" of the data in the ozwcache* and the easiest way to do that is to simply delete that file. If you know which device caused issues, a "Refresh Node Information" on that device should work as well.

**Comment by GravityRZ** [comment] 2019-06-29 19:12
oopss   spoke to soon.

my fgms001 sensor which was asleep has some problems

i cleared the logs, did a node refresh, stopped zwave and started zwave.

it appears to be working 
temp, lux and pir sensor work but where are these errors comming from

`2019-06-29 21:09:58.512 Status: OpenZWave: Alarm received (Home Security: Clear)
2019-06-29 21:09:58.334 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 21:09:58.421 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 21:09:58.422 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 21:09:58.492 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 21:09:58.492 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 21:09:58.510 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 21:09:58.512 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: `





`2019-06-29 20:11:27.849 Error: OpenZWave: Value_Changed: Unhandled value type ZDTYPE_SWITCH_NORMAL (2). Node: 16 (0x10), CommandClass: SENSOR MULTILEVEL, Label: X-Axis Acceleration, Instance: 1, Index: 52 (OpenZWave.cpp:2886)
2019-06-29 20:11:27.885 Error: OpenZWave: Value_Changed: Unhandled value type ZDTYPE_SWITCH_NORMAL (2). Node: 16 (0x10), CommandClass: SENSOR MULTILEVEL, Label: Y-Axis Acceleration, Instance: 1, Index: 53 (OpenZWave.cpp:2886)
2019-06-29 20:11:27.922 Error: OpenZWave: Value_Changed: Unhandled value type ZDTYPE_SWITCH_NORMAL (2). Node: 16 (0x10), CommandClass: SENSOR MULTILEVEL, Label: Z-Axis Acceleration, Instance: 1, Index: 54 (OpenZWave.cpp:2886)
2019-06-29 20:24:07.610 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:24:42.479 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:25:41.625 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:27:08.906 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:29:01.681 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:29:27.006 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:29:57.709 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:29:59.274 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:30:29.722 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:30:31.004 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:31:19.729 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:37:59.118 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:38:29.727 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:39:15.304 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:39:45.745 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:40:57.924 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:41:28.599 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:42:00.847 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:42:31.729 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:42:33.195 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:43:48.758 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:44:05.827 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:44:36.764 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:44:53.643 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:46:24.725 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:47:19.734 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:48:27.726 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:49:08.168 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:49:38.698 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:52:34.287 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:53:12.659 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:53:56.701 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
2019-06-29 20:54:43.671 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256`

**Comment by GravityRZ** [comment] 2019-06-29 19:16
ozw log was still running.
do not see anything strange but domotics aparently does

[domoticz.log](https://github.com/domoticz/domoticz/files/3342236/domoticz.log)

[OZW_Log.txt](https://github.com/domoticz/domoticz/files/3342234/OZW_Log.txt)

**Comment by petergebruers** [comment] 2019-06-29 19:16
> temp, lux and pir sensor work but where are these errors comming from

Correct, I expect those three to work. But the "Acceleration" and "Notification (Alarm)" are "Work In Progress". The FGMS is trickier than you might think ;)

**Comment by GravityRZ** [comment] 2019-06-29 19:23
it looks like the error is triggered when the pir sensor is activated.

`2019-06-29 21:21:55.285 Status: OpenZWave: Alarm received (Home Security: Motion Detected at Unknown Location)
2019-06-29 21:21:55.285 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 16 (0x10), CommandClass: ALARM, Label: Previous Event Cleared, Instance: 1, Index: 256
`

can i run it like this or will something crash eventually

**Comment by petergebruers** [comment] 2019-06-29 19:56
> it looks like the error is triggered when the pir sensor is activated.

Correct again! The FGMS reports motion as a sensor but also as a "Notification". It will also report tamper = when you hit the device, it shows "police or disco lights"...

It should not crash.

**Comment by nixalsschrott** [comment] 2019-07-01 06:00
beta V4.10939 on Synology appollolake is running now for several hours not crashing. Most error messages are solved up to now. I only get error for some multiswitches:

`Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 5 (0x05

kind regards
matty

**Closed as completed** 2019-07-03 15:47 UTC

**Comment by gizmocuz** [comment] 2019-07-03 16:24
@nixalsschrott good to hear! Could you post the complete log lines? The most important part is missing
