### ISSUE TITLE
latest beta: gersion `GLIBC_2.28' not found 

### ISSUE THREAD

**Issue by empierre** [domoticz/domoticz#3887] opened 2020-02-03 11:59 UTC
Hi,

   Distribution Ubuntu 18.04.4 LTS
   ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27

  Today upgrade to latest beta breaks on :

./domoticz
./domoticz: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by ./domoticz)

**Comment by rwaaren** [comment] 2020-02-03 12:15
Duplicate of #3880 
Also [forum post](https://www.domoticz.com/forum/viewtopic.php?f=6&t=31157&sid=ff791dc7d9245319ac467785ccb75dcf)

**Closed as completed by rwaaren** 2020-02-03 12:15 UTC
