### ISSUE TITLE
TempHum sensors are incorrectly reported (as seperate Temperature and Humidity sensors) as of 4.11324

### ISSUE THREAD

**Issue by akamming** [domoticz/domoticz#3634] opened 2019-09-20 10:25 UTC
Last night i upgraded to 4.11324  due to another issue (buienradar rain stats), which led to my my script for switching on the ventilation when someone takes a shower did not work anymore after that upgrade. 

This morning i did the analysis. The script is still working, but the Temperature/Humidity devices (the hardware is z-wave: type Philio Technology Corp PH-PAT02-B.eu Multisensor 2in1+) which I use for controlling the ventilation unit were not updated anymore. Instead new devices were created: seperate humidity and temperature devices. I have 3 of these sensors and they all have the same behaviour:

e.g. 

device 514:
![buitensensor](https://user-images.githubusercontent.com/30364409/65319677-7c68bd00-dba0-11e9-8d03-4303b64caabf.png)

is now reported as 555 and 557. 
![temphum](https://user-images.githubusercontent.com/30364409/65319773-b1750f80-dba0-11e9-82a8-a6a7a66c1087.png)

i suspect this is related to the "ozw code refactoring" commit…

**Comment by gizmocuz** [comment] 2019-09-20 11:20
Could be, but could you show the old and new id's

**Comment by gizmocuz** [comment] 2019-09-20 11:20
Don't you have a temp+hum sensor ?

**Comment by akamming** [comment] 2019-09-20 13:26
"Don't you have a temp+hum sensor ?"

Yes 514 is the temp+hum sensor. But that's the issue. The new beta caused that the temp+hum sensor is not updated anymore. Instead 2 new sensors (a temperature sensor and a humidity sensor) are created and updated when the node sends a measurement

**Comment by akamming** [comment] 2019-09-20 13:28
"Could be, but could you show the old and new id's"

Could you elaborate? I do not understand...

**Comment by rwaaren** [comment] 2019-09-20 14:27
After installing Beta V4.11311 (compiled locally) I noticed that some of my Zwave devices did not got updated anymore. No new devices were added to domoticz because I did not had my "accept new hardware set" Setting this to active and disabled / enabled my Zwave stick in the hardware tab. Introduced quite a number of new Zwave devices. Will update this post to show if the new devices replaced the old ones and are now receiving the updates that I expected to go to the old ones.
   
![Zwave](https://user-images.githubusercontent.com/24454798/65335782-5b669300-dbc5-11e9-95a8-82dcefbf1e24.png)

**Comment by gizmocuz** [comment] 2019-09-20 14:54
Could you try beta 11333, i think it is caused by the FindDevice function parameter change (and the option to specify -1 as instanceID)

**Comment by akamming** [comment] 2019-09-20 15:26
Tx. I just updated. I am hopeful. 

One of the temp+hum sensors already got an update. The newly created sensors were not updated anymore (which is expected behaviour, i will delete these as soon as this fix is confirmed)

**Comment by akamming** [comment] 2019-09-20 18:37
Update (a few hours later): for me the fix works. All my z-wave hum+temp sensors work correctly again!  Tx for the good work!

**Comment by rwaaren** [comment] 2019-09-20 20:34
All fine again using V4.11333

**Comment by gizmocuz** [comment] 2019-09-21 07:11
Thanks for the feedback... checking a uint8_t againt -1 seems not to work the way i expected to.
Closing issue

**Closed as completed by gizmocuz** 2019-09-21 07:11 UTC
