### ISSUE TITLE
Problem with Deconz PlugIn

### ISSUE THREAD

**Issue by salopette** [domoticz/domoticz#3328] opened 2019-06-16 13:40 UTC
since update today, I have constant errors

Version: 4.10915
Build Hash: 32abee2a5
Compile Date: 2019-06-16 09:41:06
dzVents Version: 2.4.23
Python Version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]

2019-06-16 15:36:55.230 (deconz) ### Request config
2019-06-16 15:37:05.253 (deconz) ### Request config
2019-06-16 15:37:05.253 Error: (deconz) More than 5s timeout, Your system seem frezzed, Forcing disconnect for : GET /api/5CCF8FFE49/config/ HTTP/1.1
2019-06-16 15:37:05.253 Host: 192.168.178.93:80
2019-06-16 15:37:05.253 User-Agent: Domoticz/1.0
2019-06-16 15:37:05.253 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
2019-06-16 15:37:05.253 Connection: keep-alive
2019-06-16 15:37:05.253

**Comment by gizmocuz** [comment] 2019-06-16 13:42
I have no idea what we are looking at here ? What is the problem, with what ? Hardware or script related ?

I do not think a message like "Your system seem frezzed" is coming from Domoticz ?

**Comment by salopette** [comment] 2019-06-16 13:44
The message comes from the Deconz PlugIn, before the update everything worked!

**Comment by Smanar** [comment] 2019-06-16 13:44
Nope there are coming from my plugin. I m searching where it s from, but It s not the only one with this bug.
No modifications on my side, problem with the connection framework.

**Comment by salopette** [comment] 2019-06-16 13:45
Let us know what it's all about!

**Comment by Smanar** [comment] 2019-06-16 13:53
I can confirm, same bug after update.
I m searching for a workaround or a solution.

**Comment by gizmocuz** [comment] 2019-06-16 14:18
From what version have you updated ? Could be that between the previous stable (9700) and the current stable/beta that something have changed

**Comment by Smanar** [comment] 2019-06-16 14:28
Ok So I have find something
`self.Request = Domoticz.Connection(Name="deCONZ_Com", Transport="TCP/IP", Protocol="HTTP", Address='www.google.com', Port='80')`

If I use 'www.google.com' as adress it work, but if I use '216.58.204.131' I haven't response, and both work on firefox.

Was working with last stable, and bug with last beta.

Edit:
My bad, it works with ip too, problem only with local IP.

**Comment by gizmocuz** [comment] 2019-06-16 14:35
@Smanar , last stable as in current stable ?
I am not working on the python plugin system, but quickly looked in PythonObject.cpp , could you add ', , Baud=0' at the end ?

self.Request = Domoticz.Connection(Name="deCONZ_Com", Transport="TCP/IP", Protocol="HTTP", Address='www.google.com', Port='80', Baud=0)

What is the Domoticz.Connection returning ? Do you check if self.Request is valid ?

**Comment by Smanar** [comment] 2019-06-16 14:42
Last beta with problem : V4.10915
Last working version : V4.4.10717 (not sure)

Someone have modified a lot the framework to implement webserver feature.

I receive data, but the OnMessage function is never trigger.

```
 2019-06-16 16:42:10.566 (deCONZ) 39 2d 30 34 2d 31 35 54 32 30 3a 30 39 3a 31 36 22 2c 22 6e 9-04-15T20:09:16","n
2019-06-16 16:42:10.566 (deCONZ) 61 6d 65 22 3a 22 50 68 6f 73 63 6f 6e 23 42 31 39 32 30 78 ame":"Phoscon#B1920x
2019-06-16 16:42:10.566 (deCONZ) 31 30 34 35 22 7d 2c 22 46 42 30 43 43 33 36 31 45 35 22 3a 1045"},"FB0CC361E5":
2019-06-16 16:42:10.566 (deCONZ) 7b 22 63 72 65 61 74 65 20 64 61 74 65 22 3a 22 32 30 31 39 {"create.date":"2019
2019-06-16 16:42:10.566 (deCONZ) 2d 30 34 2d 31 39 54 31 35 3a 30 38 3a 32 34 22 2c 22 6c 61 -04-19T15:08:24","la
2019-06-16 16:42:10.566 (deCONZ) 73 74 20 75 73 65 20 64 61 74 65 22 3a 22 32 30 31 39 2d 30 st.use.date":"2019-0
2019-06-16 16:42:10.566 (deCONZ) 34 2d 31 39 54 31 35 3a 31 30 3a 31 31 22 2c 22 6e 61 6d 65 4-19T15:10:11","name
2019-06-16 16:42:10.566 (deCONZ) 22 3a 22 50 68 6f 73 63 6f 6e 23 42 31 39 32 30 .. .. .. .. ":"Phoscon#B1920
2019-06-16 16:42:10.566 (deCONZ) Processing 'ReadEvent' message
2019-06-16 16:42:10.566 (deCONZ) Received 28 bytes of data
2019-06-16 16:42:10.567 (deCONZ) 78 31 30 34 35 22 7d 7d 2c 22 7a 69 67 62 65 65 63 68 61 6e x1045"}},"zigbeechan
2019-06-16 16:42:10.567 (deCONZ) 6e 65 6c 22 3a 31 31 7d .. .. .. .. .. .. .. .. .. .. .. .. nel":11} 
```

**Comment by gizmocuz** [comment] 2019-06-16 14:45
Sorry can't help you here... have you tried the plugins/HTTP.py example ?

**Comment by gizmocuz** [comment] 2019-06-16 14:48
Best to check here for changes

https://github.com/domoticz/domoticz/blob/development/hardware/plugins/PluginManager.cpp

**Comment by Smanar** [comment] 2019-06-16 14:59
Ok my bad, It works too with IP, it's broken only for local IP.

I m making test with the "Google Home page example" with localhost ip and another computer, same result.

I have tried with domoticz url and port, it's works, only the deconz server seem broken.

**Comment by salopette** [comment] 2019-06-16 17:38
it works again!!!
THX for the Fix!!!!

2019-06-16 19:37:11.434 Status: (deconz) Launching websocket on port 443
2019-06-16 19:37:11.486 Status: (deconz) Websocket Handshake : HTTP/1.1 101 Switching Protocols
***Upgrade: websocket
***Connection: Upgrade
***Sec-WebSocket-Accept: V0htEbn5FhIA1xfQRyG3yU1aG9c=
***Server: deconz
***Access-Control-Allow-Credentials: false
***Access-Control-Allow-Methods: GET
***Access-Control-Allow-Headers: content-type
***Access-Control-Allow-Origin: http://192.168.178.37
***Date: Sun, 16 Jun 2019 17:37:11 GMT
***
***

**Comment by Smanar** [comment] 2019-06-16 17:46
Hu ? Wich one fix ?

**Comment by salopette** [comment] 2019-06-16 18:02
Beta 

https://github.com/Smanar/Domoticz-deCONZ/tree/beta

**Comment by Smanar** [comment] 2019-06-16 19:49
ha, lol, I have made a workaround, I m using the python lib request instead of the domoticz framework.
But the bug is still present.

**Comment by Smanar** [comment] 2019-06-17 15:16
Ok, so wasn't a problem for me ATM, I m stoping using the domoticz connection framework for pure python, but I can still make tries.

So to resume the bug.
- It happen only with the deconz webserver, haven't find another webserver with this bug yet.
- Domoticz receive data but the OnMessage is not trigger. All is freezed, then timeout, but all datas are received.
- I think the bug is here since the last @dnpwwo modification.

**Comment by Smanar** [comment] 2019-06-18 15:59
Ok, so, some more information, here a complete log with a minimal exemple, I m using the test plugin "Google Home page example" with a deCONZ url.
```

2019-06-18 17:49:10.747 (google) Device count: 0
2019-06-18 17:49:10.747 (google) Pushing 'ProtocolDirective' on to queue
2019-06-18 17:49:10.747 (google) Pushing 'ConnectDirective' on to queue
2019-06-18 17:49:10.747 (google) Processing 'ProtocolDirective' message
2019-06-18 17:49:10.747 (google) Protocol set to: 'HTTP'.
2019-06-18 17:49:10.747 (google) Processing 'ConnectDirective' message
2019-06-18 17:49:10.747 (google) Transport set to: 'TCP/IP', 192.168.1.1:80.
2019-06-18 17:49:10.747 (google) Connect directive received, action initiated successfully.
2019-06-18 17:49:10.748 (google) Pushing 'onConnectCallback' on to queue
2019-06-18 17:49:10.797 (google) Processing 'onConnectCallback' message
2019-06-18 17:49:10.798 (google) Calling message handler 'onConnect'.
2019-06-18 17:49:10.798 (google) Google connected successfully.
2019-06-18 17:49:10.798 (google) Pushing 'WriteDirective' on to queue
2019-06-18 17:49:10.798 (google) Processing 'WriteDirective' message
2019-06-18 17:49:10.798 (google) Sending 200 bytes of data
2019-06-18 17:49:10.798 (google) 47 45 54 20 2f 61 70 69 2f 33 36 45 31 33 38 32 39 35 45 2f GET./api/36E138295E/
2019-06-18 17:49:10.798 (google) 6c 69 67 68 74 73 2f 32 20 48 54 54 50 2f 31 2e 31 0d 0a 43 lights/2.HTTP/1.1..C
2019-06-18 17:49:10.798 (google) 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 74 65 78 74 2f 78 6d ontent-Type:.text/xm
2019-06-18 17:49:10.798 (google) 6c 3b 20 63 68 61 72 73 65 74 3d 75 74 66 2d 38 0d 0a 48 6f l;.charset=utf-8..Ho
2019-06-18 17:49:10.798 (google) 73 74 3a 20 31 39 32 2e 31 36 38 2e 31 2e 31 3a 38 30 0d 0a st:.192.168.1.1:80..
2019-06-18 17:49:10.798 (google) 55 73 65 72 2d 41 67 65 6e 74 3a 20 44 6f 6d 6f 74 69 63 7a User-Agent:.Domoticz
2019-06-18 17:49:10.798 (google) 2f 31 2e 30 0d 0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a 20 6b 65 /1.0..Connection:.ke
2019-06-18 17:49:10.798 (google) 65 70 2d 61 6c 69 76 65 0d 0a 41 63 63 65 70 74 3a 20 43 6f ep-alive..Accept:.Co
2019-06-18 17:49:10.798 (google) 6e 74 65 6e 74 2d 54 79 70 65 3a 20 74 65 78 74 2f 68 74 6d ntent-Type:.text/htm
2019-06-18 17:49:10.798 (google) 6c 3b 20 63 68 61 72 73 65 74 3d 55 54 46 2d 38 0d 0a 0d 0a l;.charset=UTF-8....
2019-06-18 17:49:10.800 (google) Pushing 'ReadEvent' on to queue
2019-06-18 17:49:10.848 (google) Processing 'ReadEvent' message
2019-06-18 17:49:10.848 (google) Received 558 bytes of data
2019-06-18 17:49:10.848 (google) 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d 0a 41 63 63 HTTP/1.1.200.OK..Acc
2019-06-18 17:49:10.849 (google) 65 73 73 2d 43 6f 6e 74 72 6f 6c 2d 41 6c 6c 6f 77 2d 4f 72 ess-Control-Allow-Or
2019-06-18 17:49:10.849 (google) 69 67 69 6e 3a 20 2a 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 igin:.*..Content-Typ
2019-06-18 17:49:10.849 (google) 65 3a 20 61 70 70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 3b e:.application/json;
2019-06-18 17:49:10.849 (google) 20 63 68 61 72 73 65 74 3d 75 74 66 2d 38 0d 0a 43 6f 6e 74 .charset=utf-8..Cont
2019-06-18 17:49:10.849 (google) 65 6e 74 2d 4c 65 6e 67 74 68 3a 33 39 39 0d 0a 45 54 61 67 ent-Length:399..ETag
2019-06-18 17:49:10.849 (google) 3a 22 35 65 64 38 39 36 33 36 36 66 31 62 31 33 61 37 34 31 :"5ed896366f1b13a741
2019-06-18 17:49:10.849 (google) 63 35 63 32 32 63 37 31 32 63 37 37 63 37 22 0d 0a 0d 0a 7b c5c22c712c77c7"....{
2019-06-18 17:49:10.849 (google) 22 63 74 6d 61 78 22 3a 34 35 34 2c 22 63 74 6d 69 6e 22 3a "ctmax":454,"ctmin":
2019-06-18 17:49:10.849 (google) 32 35 30 2c 22 65 74 61 67 22 3a 22 35 65 64 38 39 36 33 36 250,"etag":"5ed89636
2019-06-18 17:49:10.849 (google) 36 66 31 62 31 33 61 37 34 31 63 35 63 32 32 63 37 31 32 63 6f1b13a741c5c22c712c
2019-06-18 17:49:10.849 (google) 37 37 63 37 22 2c 22 68 61 73 63 6f 6c 6f 72 22 3a 74 72 75 77c7","hascolor":tru
2019-06-18 17:49:10.849 (google) 65 2c 22 6d 61 6e 75 66 61 63 74 75 72 65 72 6e 61 6d 65 22 e,"manufacturername"
2019-06-18 17:49:10.849 (google) 3a 22 49 4b 45 41 20 6f 66 20 53 77 65 64 65 6e 22 2c 22 6d :"IKEA.of.Sweden","m
2019-06-18 17:49:10.849 (google) 6f 64 65 6c 69 64 22 3a 22 54 52 41 44 46 52 49 20 62 75 6c odelid":"TRADFRI.bul
2019-06-18 17:49:10.849 (google) 62 20 45 32 37 20 43 57 53 20 6f 70 61 6c 20 36 30 30 6c 6d b.E27.CWS.opal.600lm
2019-06-18 17:49:10.849 (google) 22 2c 22 6e 61 6d 65 22 3a 22 6c 61 6d 70 65 20 69 6b 65 61 ","name":"lampe.ikea
2019-06-18 17:49:10.849 (google) 22 2c 22 73 74 61 74 65 22 3a 7b 22 61 6c 65 72 74 22 3a 22 ","state":{"alert":"
2019-06-18 17:49:10.849 (google) 6e 6f 6e 65 22 2c 22 62 72 69 22 3a 32 35 34 2c 22 63 6f 6c none","bri":254,"col
2019-06-18 17:49:10.849 (google) 6f 72 6d 6f 64 65 22 3a 22 78 79 22 2c 22 65 66 66 65 63 74 ormode":"xy","effect
2019-06-18 17:49:10.849 (google) 22 3a 22 6e 6f 6e 65 22 2c 22 68 75 65 22 3a 30 2c 22 6f 6e ":"none","hue":0,"on
2019-06-18 17:49:10.849 (google) 22 3a 66 61 6c 73 65 2c 22 72 65 61 63 68 61 62 6c 65 22 3a ":false,"reachable":
2019-06-18 17:49:10.849 (google) 74 72 75 65 2c 22 73 61 74 22 3a 30 2c 22 78 79 22 3a 5b 30 true,"sat":0,"xy":[0
2019-06-18 17:49:10.849 (google) 2e 34 39 36 32 2c 30 2e 33 35 32 37 5d 7d 2c 22 73 77 76 65 .4962,0.3527]},"swve
2019-06-18 17:49:10.849 (google) 72 73 69 6f 6e 22 3a 22 31 2e 33 2e 30 30 32 22 2c 22 74 79 rsion":"1.3.002","ty
2019-06-18 17:49:10.849 (google) 70 65 22 3a 22 43 6f 6c 6f 72 20 6c 69 67 68 74 22 2c 22 75 pe":"Color.light","u
2019-06-18 17:49:10.849 (google) 6e 69 71 75 65 69 64 22 3a 22 39 30 3a 66 64 3a 39 66 3a 66 niqueid":"90:fd:9f:f
2019-06-18 17:49:10.849 (google) 66 3a 66 65 3a 38 33 3a 31 64 3a 31 37 2d 30 31 22 7d .. .. f:fe:83:1d:17-01"}
2019-06-18 17:49:10.579 Status: (google) Stopping threads.
2019-06-18 17:49:10.579 Status: (google) Stopped.
2019-06-18 17:49:10.580 Status: (google) Started.
2019-06-18 17:49:10.744 Status: (google) Entering work loop.
2019-06-18 17:49:10.744 Status: (google) Initialized version 2.2.6, author 'Dnpwwo'
2019-06-18 17:49:20.746 (google) Pushing 'onHeartbeatCallback' on to queue
2019-06-18 17:49:20.766 (google) Processing 'onHeartbeatCallback' message
2019-06-18 17:49:20.767 (google) Calling message handler 'onHeartbeat'.
2019-06-18 17:49:20.767 (google) onHeartbeat called, Connection is alive.
2019-06-18 17:49:30.747 (google) Pushing 'onHeartbeatCallback' on to queue
2019-06-18 17:49:30.783 (google) Processing 'onHeartbeatCallback' message
2019-06-18 17:49:30.783 (google) Calling message handler 'onHeartbeat'.
2019-06-18 17:49:30.783 (google) onHeartbeat called, Connection is alive.
2019-06-18 17:49:40.749 (google) Pushing 'onHeartbeatCallback' on to queue
2019-06-18 17:49:40.799 (google) Processing 'onHeartbeatCallback' message
2019-06-18 17:49:40.799 (google) Calling message handler 'onHeartbeat'.
2019-06-18 17:49:40.799 (google) onHeartbeat called, Connection is alive.
2019-06-18 17:49:50.751 (google) Pushing 'onHeartbeatCallback' on to queue
2019-06-18 17:49:50.767 (google) Processing 'onHeartbeatCallback' message
2019-06-18 17:49:50.767 (google) Calling message handler 'onHeartbeat'.
2019-06-18 17:49:50.767 (google) onHeartbeat called, Connection is alive.
2019-06-18 17:50:00.753 (google) Pushing 'onHeartbeatCallback' on to queue
2019-06-18 17:50:00.787 (google) Processing 'onHeartbeatCallback' message
2019-06-18 17:50:00.787 (google) Calling message handler 'onHeartbeat'.
2019-06-18 17:50:00.787 (google) onHeartbeat called, Connection is alive.
2019-06-18 17:50:10.754 (google) Pushing 'onHeartbeatCallback' on to queue
2019-06-18 17:50:10.803 (google) Processing 'onHeartbeatCallback' message
2019-06-18 17:50:10.803 (google) Calling message handler 'onHeartbeat'.
2019-06-18 17:50:10.803 (google) onHeartbeat called, Connection is alive. 
```

For information the code was already bugged before the last modification, I m using in the python code.
```
            self.BufferLenght += len(Data)
            l = Connection.BytesTransferred() - self.BufferLenght
            if l > 0:
                #Not complete frame
                return
```
To compare myself data that was already transfered and data given by header, to force a disconnect, because when all value was equal (mean all data was transfered to function), the framework still waiting for magic data.

But ATM, I can't use a workaround, because the onMessage() function is never trigger, so it's dead for me.

I have still more bugs to describe for this fonction if you want more ?

**Comment by pipiche38** [comment] 2019-06-18 20:02
@Smanar I known that @dnpwwo did some changes on the TCP layer on the Python Plugin Framework. Might be related to that as the changes came on 10901 (beta)

**Comment by Smanar** [comment] 2019-06-19 17:13
Yep, I know, and he have make change for you, it's your fault, I m searching a voodoo witch for a malediction on you ^^.
I have PM him on domoticz forum, for the moment I can wait, I will pull a version without asynchronous mode and see users return, but I don't think it will be a problem for local request.

I prefer waiting for @dnpwwo return first.

**Comment by dnpwwo** [comment] 2019-06-22 02:46
I can see the problem, the secure transport inherits from the non-secure one and overrides some functionality.  I thought I could combine the write functions but a second look shows I can't.

I'll re-introduce a specific secure write function today

**Comment by Smanar** [comment] 2019-06-22 09:03
Thx a lot ^^.
Will be hard for me to recompile code for the moment, so I will wait for future beta release to confirm.

**Comment by Smanar** [comment] 2019-06-29 07:36
Working like before with 0.410935 on my side (but as it s not my issue, I can't close it)

**Closed as completed** 2019-06-29 08:02 UTC
