### ISSUE TITLE
RTL_433 -R option in HW devices is not working after update of beta Domoticz

### ISSUE THREAD

**Issue by geschriever** [domoticz/domoticz#4205] opened 2020-06-04 11:55 UTC
Since a few days the -R option in RTL433 device is not working anymore.
Without these parameters it is working however I get also a lot of other sensor and that I do not like :).
Please can you have a look to this. A screenshot is added were you can see what is in my log of Domoticz, I did wait for 5 minutes to see anything is happen (normally at least every minute). I accidentally added the -R option to the name of the sensor, please do not get confused by it.

p.s. Im on beta Domoticz version 12119

![screenshot 2020-06-04 om 13 52 56](https://user-images.githubusercontent.com/60884808/83753544-c8925980-a66a-11ea-94b6-ad68c2c25750.jpg)

**Comment by FredrikFornstad** [comment] 2020-06-04 20:49
Probably a missing space in a pull request that was merged a few days ago is the cause. I just did a new PR that I think should fix this. #4210

**Comment by geschriever** [comment] 2020-06-04 21:25
👍

Op 4 jun. 2020, om 22:49 heeft FredrikFornstad <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:



Probably a missing space in a pull request that was merged a few days ago is the cause. I just did a new PR that I think should fix this. #4210<https://github.com/domoticz/domoticz/pull/4210>

—

**Closed as completed** 2020-06-05 11:15 UTC
