### ISSUE TITLE
Year/Month compare graph does not display correct icon

### ISSUE THREAD

**Issue by gizmocuz** [domoticz/domoticz#5025] opened 2021-11-18 06:01 UTC
I think the icons are in the wrong direction

![Screenshot_2021-11-18-06-49-05-83_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/2265299/142360824-356827ce-a4c1-4119-9c82-5cbe60126626.jpg)

See for example the bottom one... Should not be green as usage is more then previous month

**Comment by waltervl** [comment] 2021-11-18 08:52
I think it is meant to be the difference with the month before on the same year. So in your example that October 2021 is lower than september  2021 and that October 2020 was higher than september 2020.

**Comment by Olifant1990** [comment] 2021-11-21 13:33
@waltervl is correct. I made that same mistake myself too. Had to find out it is compared to previous month in the same year.
But indeed, that is not expected, I also want to see in the same month over the years if it increased or decreased

**Comment by gizmocuz** [comment] 2021-11-21 15:24
I think we should compare over the years here 👍

**Comment by michahagg** [comment] 2021-11-21 19:41
You're probably right. Do you want me to change it? Should be no problem.

**Comment by GravityRZ** [comment] 2021-12-05 15:43
installed 13.872 but it seems this change ha not gone through.

**Comment by gizmocuz** [comment] 2021-12-05 15:44
Would be great if you can change it

**Comment by michahagg** [comment] 2021-12-10 15:02
Hi @gizmocuz the PR #5047 contains the fix for this issue

**Comment by GravityRZ** [comment] 2021-12-10 15:38
any idea how i can get rid of this faulty value.
the graphs show it happened in 2020 but shift leftclick states it is an entry from 1970.
shift leftclick can not remove this item.

![image](https://user-images.githubusercontent.com/16853535/145600495-77baf0d2-2319-4186-b42d-46f01f6b5921.png)

**Comment by michahagg** [comment] 2021-12-10 22:09
Hi @GravityRZ it makes no sense deleting points from the compare chart as it shows aggregated data only. But nevertheless the data shown seems incorrect. Probably it's a counter loop that is not being recognized.

If you let me analyse the data, I might just find a way to fix it. Could you execute the following query on the database?

`select * from Meter_Calendar where DeviceRowID = [device-id] and Date >= '2020-01-01'`

Fill in the index of the device at [device-id].

**Comment by GravityRZ** [comment] 2021-12-11 08:20
here it is.
the list is rather long but here i see things which look strange
0 numbers or big negative number

87	283	332976	2020-10-25
87	228	333204	2020-10-26
87	216	333420	2020-10-27
87	0	333420	2020-10-28
87	0	333420	2020-10-29
87	282	364723	2020-10-31
87	269	364995	2020-11-01
87	233	365228	2020-11-02
87	242	365470	2020-11-03
87	230	365700	2020-11-04
87	269	-360715	2020-11-06
87	281	-360434	2020-11-07
87	252	-360182	2020-11-08
87	0	-18185974	2020-11-10
87	2	-18185972	2020-11-11
87	0	-18185972	2020-11-12
87	0	-18185972	2020-11-13
87	0	-18185972	2020-11-14
87	0	-18185972	2020-11-15
87	0	-18185972	2020-11-16
87	0	-18185972	2020-11-17
87	0	-18185972	2020-11-18
87	0	-18185972	2020-11-19
87	0	389300	2020-11-21
87	0	389300	2020-11-22
87	0	389300	2020-11-23
87	0	389300	2020-11-24
87	0	389300	2020-11-25
87	0	389300	2020-11-26
87	0	389300	2020-11-27
87	180	389480	2020-11-28
87	296	389776	2020-11-29
87	267	390043	2020-11-30
87	269	390312	2020-12-01
87	270	390582	2020-12-02
87	291	390873	2020-12-03
87	308	391181	2020-12-04
87	306	391487	2020-12-05
87	330	391820	2020-12-06
87	280	392100	2020-12-07
87	297	392397	2020-12-08
87	294	392691	2020-12-09
87	316	393007	2020-12-10
87	337	393344	2020-12-11
87	342	393686	2020-12-12
87	305	394935	2020-12-14
87	312	395247	2020-12-15

**Comment by michahagg** [comment] 2021-12-12 15:48
@GravityRZ I added a commit to PR #5047 to ignore negative values. Hopefully it fixes your case.

I don't know how the device registered negative values! Has something happened to your setup during that period around 2020-11-15?

**Comment by kiddigital** [comment] 2021-12-12 17:45
Negative values can come from overflowing values. Somewhere during processing either precision or signed vs unsigned goes wrong.

Is it from a specific device or hardware module that has the weird values?

What is your platform?

**Comment by GravityRZ** [comment] 2021-12-12 19:46
@michahagg 
thanks for the fix

the device is a qubino zwavre switching device with power usage.

all my power devices are set to computed instead of getting the complete power usage from the device
i noticed that when i change the computed to from device i sometimes get a negative amount.

maybe this is what happened with this device last year but is is strange.
also last year we had a transitioning from zwave 1.4 to 1.6 which might have caused this

**Comment by michahagg** [comment] 2021-12-12 21:37
Hi @GravityRZ, I might have caused some of the trouble with a programming error. In SQLHelper.cpp, upon an Update, the new power and energy values are computed. Unfortunately I made a mistake that caused the power to be updated from the DeviceStatus instead of from the Update. That can result in the power value not being updated and therefore the energy value to be calculated with the wrong power value everytime an update occurred.

I have just pushed the fix for this in the PR #5047.

**Comment by GravityRZ** [comment] 2021-12-17 12:27
tested build 945.
icons are ok now and compare to the month selected.
also the spike in relation to negative numbers are gone.
there are other spikes but they are related to strange jumps in readouts.
i suspect that this wa caused by changing the decice from device to computed and back.

setting the devices to computed give the best and stable readouts

looking good

**Comment by gizmocuz** [comment] 2021-12-17 12:43
Works perfectly here as well ! Thank you for fixing!!!

**Comment by gizmocuz** [comment] 2021-12-17 15:00
I seem to have another painting issue:

![image](https://user-images.githubusercontent.com/2265299/146563617-666dcdde-a3af-4e98-b818-f3f9dadebc70.png)

I don't have this boundry issue with all months:

![image](https://user-images.githubusercontent.com/2265299/146563881-fa0fa46a-6319-4d73-8160-da0df493cd19.png)

As you can see this month is wider then the previous

**Comment by GravityRZ** [comment] 2021-12-17 15:08
i do not have this issue with any of my kWh devices
i did not clear cache after reinstalling

**Comment by gizmocuz** [comment] 2021-12-18 08:09
Well I do, and I do clear my cache a lot, another example:

![image](https://user-images.githubusercontent.com/2265299/146634362-701993e2-bcb3-4c6f-8188-030be6d4d903.png)

Using Edge browser

Do we have any control over the width of the popups ? Maybe this can be set to a fixed width ?

**Comment by GravityRZ** [comment] 2021-12-18 09:53
cleared cache but everything as it should
no problems when using chrome browser
tried it with edge
i only noticed it once where the bottom border was a bit close but not as extreme as gizmocuz

also trying to reproduce it again but it seems it is gone(looks like it is autoscaling the window)

**Comment by michahagg** [comment] 2021-12-19 11:42
@gizmocuz It should be fixed with #5075!

**Comment by GravityRZ** [comment] 2021-12-29 09:36
@michahagg 

can you tell me how the usage bars are calculated?
i need to make some manual corrections to values.

i thought the month totals were calculat4d by substracting the  monthend meter total- month beginning total.

i noticed however that it also take in account the begin/end of the previous/next month

eg. the meter numbers needs to be in linre witrh eachother.

eg
jan 1th 10
jan 31th 40
januari usage 30

feb 1th 41
feb 28th  51
februari usage 10

but when meter numbers in the database  are wrong(because of fluctuations)

jan 1th 10
jan 31th 40
januari usage 30

feb 1th 60
feb 28th  71
februari usage 61 (should be 11)

if i know what formulsa is used per month i am able to correct the begin/end values per month
in my case when i correct 1 monthe de difference is addd to the next month

**Comment by michahagg** [comment] 2021-12-30 06:28
Hi @GravityRZ didn't you ask a question about how the chart calculates its values?

It does it the following way. 
It uses the Meter_Calendar (or MultiMeter_Calendar) table. This table contains a record for each day, and each record contains the Value (amount of energy used that day) and Counter (the counter-value at the end of that day).
Then it re-calculates for each record the value by taking the difference between the counter and the counter of the previous record. (Sometimes the value of the record is off. I take it that the counter value is always correct.)
Then it sums all those re-calculated values for each month, quarter or year, depending on which viewmode you choose for the compare-chart.
For a normal situation it would be possible to do the calculation using the last counters of all periods (month, quarter, year), but it happens that a counter is reset to zero (for example when a meter is changed). In that case, it does use the value recorded for that day instead of the difference between counters.

Hope this is of any help, after all.

**Comment by GravityRZ** [comment] 2021-12-30 09:22
Hi @michahagg
Yes i did ask a question because i neeeded an easy fix of some values.
i noticed however that one column holds the usage of the day and the second one the counter.

since a lot of my counter values were strange and were jumping i decided to recreate the entire table.
in my case the usage values are correct but the meter values were not.
I took the start value of the counter and added the usage of that day to the total counter of the second day.
real easy fix if you do it in Excel and then copy/paste it back
The nice part is i did not fix some high values but i now have the exact values like they should be
thanks for your help

![image](https://user-images.githubusercontent.com/16853535/147738528-09969486-764e-4402-b6d6-c9c449208f16.png)

**Closed as completed** 2022-01-08 03:12 UTC
