### ISSUE TITLE
EventHelpers.lua:305: attempt to index local 'pfile' (a nil value)

### ISSUE THREAD

**Issue by mikkel75** [domoticz/domoticz#2973] opened 2019-01-16 07:40 UTC
Hi,

There seems to be a problem in the /dzVents/runtime/EventHelpers.lua, where the popen(cmd) in line 304 sometimes returns pfile as nil causing line 305 to fail tying to index a nil pointer:

`/dzVents/runtime/EventHelpers.lua:305: attempt to index local 'pfile' (a nil value)`

I have read that LUA 5.2 sometimes have this error with popen.
So either LUA should be updated or this error should be catched before line 305.

Thanks,
Mikkel

**Comment by rwaaren** [comment] 2019-01-16 10:31
Hi Mikkel,

I have send you a PM on the forum on Monday. Can you please have a look and test the proposed change in EventHelpers.lua (add the following at line  302)  
 **cmd = 'ls -a "' .. directory .. '"**
That could help in identifying what triggers this crash.

**Comment by mikkel75** [comment] 2019-01-16 13:42
Done...I'll write back when I have news.

/Mikkel

p.s. I also added a catch if popen() returns nil and prints in log - just in case it should happen again. Can't have Domoticz crash completely as it controls some lights as well :)

**Comment by mikkel75** [comment] 2019-01-28 07:51
Hi,

So it happen again :( Even when I catch the nil index it crashes, but with a different error (See below).
Could it be a secondary error, where the real problem is why the popen returns nil?

(Also - why is it that the ls-command is run  up to 10 times per second!? Seems a bit unnecessary.)

/Mikkel

Modified EventHelpers.lua...

> 
                if (sep == '/') then
                        cmd = 'ls -a "' .. directory .. '"'
                else
                        -- assume windows for now
                        cmd = 'dir "' .. directory .. '" /B'
                end
                cmd = 'ls -a "' .. directory .. '"'
                t = {}
                local pfile = popen(cmd)
                if (pfile == nil) then
                        utils.log('!! CATCHED pfile == nil !! ', utils.LOG_ERROR)
                        return t, namesLookup
                end
                for filename in pfile:lines() do

> 

`
2019-01-26 11:03:55.171  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:03:55.732  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:03:55.755  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:03:55.842  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:00.476  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:00.550  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:00.606  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:00.716  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:00.844  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:00.908  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:00.958  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:01.008  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:01.937  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:02.002  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:02.052  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:02.102  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:02.199  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:02.263  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:02.313  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:02.336  Status: dzVents: Error (2.4.9): !! CATCHED pfile == nil !!
2019-01-26 11:04:02.385  Error: Domoticz(pid:30113, tid:30131('EventSystemQueu')) received fatal signal 6 (Aborted)
2019-01-26 11:04:02.386  Error: siginfo address=0x75a1, address=0x7fa71f2464
2019-01-26 11:04:02.456  Error: Failed to start gdb, will use backtrace() for printing stack frame

2019-01-26 11:04:02.460  Error: #0  /home/hac/domoticz/domoticz :  + 0x8f8390 [0x557c001390]
2019-01-26 11:04:02.460  Error: #1  /home/hac/domoticz/domoticz :  + 0x8f8644 [0x557c001644]
2019-01-26 11:04:02.460  Error: #2  /home/hac/domoticz/domoticz : signal_handler(int, siginfo_t*, void*) + 0x28c [0x557c0018dc]
2019-01-26 11:04:02.460  Error: #3  linux-vdso.so.1 : __kernel_rt_sigreturn + 0 [0x7fa753b6c0]
2019-01-26 11:04:02.460  Error: #4  /lib/aarch64-linux-gnu/libc.so.6 : raise + 0xb0 [0x7fa71f24d8]
`

**Comment by rwaaren** [comment] 2019-01-28 09:54
Even when I force pfile to be nil,  domoticz  does not crash on me. So my guess is that the repetitive failing popen commands bring domoticz to it's knees. Either triggered by the event system or by one of the other threads.

**Comment by rwaaren** [comment] 2019-08-08 21:28
Closing as according to [ this forum post ](https://www.domoticz.com/forum/viewtopic.php?f=6&t=26240&p=207251) it was caused by an OS/Driver issue on a M4 board

**Closed as completed by rwaaren** 2019-08-08 21:28 UTC
